### ISSUE TITLE
How to allow requests without `Accept` header? Error 406 Not Acceptable

### ISSUE THREAD

**Issue by khal3d** [FriendsOfSymfony/FOSRestBundle#1000]
I'm facing a serious problem with some services like Pingdom (Transaction Check) and Gmail images proxy & with our mobile development team.

The issue is when someone want to comunicate with my application he supposed to send `Accept` header, but that is not always possible to do, and when you are not sending `Accept` header you will get 406 response. for example, I'm using LiipImagineBundle for images resizing, and when I send images in email, Gmail will use their own proxy to fetch the images and that proxy doesn't send `Accept` header :disappointed: 

Here is my format listener rules:
```
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false}
            - { path: '^/', priorities: ['html', 'json', '*/*'], fallback_format: ~, prefer_extension: true }
```

I tried to add the following line to format listener, but it didn't work!
```
- { path: '^/media/', priorities: ['jpeg', 'gif', 'jpg', 'png'], fallback_format: jpg, prefer_extension: true }
```

Also, I figured out that 406 response is throwing from `FormatListener`

**Comment by lsmith77** [comment]
maybe you can use this new feature in 1.5.0 to stop the format listener rules at a defined point: http://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#disabling-the-format-listener-via-rules

**Comment by khal3d** [comment]
Thanks alot @lsmith77, it worked :+1:
