### ISSUE TITLE
Problem with camel case serialization and login form

### ISSUE THREAD

**Issue by nschurmann** [FriendsOfSymfony/FOSRestBundle#1009]
I'm using the `fos_rest.normalizer.camel_keys` serialization, so when i receive objects in javascript with underscore they will be transformed into camel case. The problem is that the `login_check` uses `_username` and `_password` values, so symfony receives the data as `Username` and `Password`

So i'm looking for 1 of 2 options:

1. Don't serialize for `login_check`
2. Override how the data is received.

The best would be the first, because serializing the data 2 times is overhead.

**Comment by lsmith77** [comment]
can you elaborate a bit more about the entire request/response data flow so that I can understand the issue a bit better?

**Comment by nschurmann** [comment]
Of course,

when i send a request to the symfony2 server, the data sent in the POST request is 
    {
        '_username': 'john',
        '_password': 'mypassword'
    }

and because of the serialization, the server respond a 'bad credentials.' exception. My guess is that the option `fos_rest.normalizer.camel_keys` is "taking away" the underscore before `username` and `password`, therefore it doesn't recognise the fields which is used to work the security bundle. I'm using FOSRestBundle with FOSUserBundle.

Hope this makes things more clear.

**Comment by florianv** [comment]
This is the same issue than https://github.com/FriendsOfSymfony/FOSRestBundle/issues/760.

**Comment by lsmith77** [comment]
maybe the fix is just to just add a flag to ignore keys with leading underscores which is not camel case anyway

**Comment by stof** [comment]
@nschurmann as a workaround until it is implemented, note that the security system allows to configure the field names

**Comment by lsmith77** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1267

**Comment by cve** [comment]
Is it in the 2.0? I still have the issue...

**Comment by xabbuh** [comment]
@cve Can you provide the necessary steps to reproduce your issue?
