### ISSUE TITLE
One to many relation, how to post/put?

### ISSUE THREAD

**Issue by grzegorztomasiak** [FriendsOfSymfony/FOSRestBundle#1014]
I need a help, 'cause I am stuck now.
I don't know how to post (how should JSON structure should look like) when data is related one to many.

Basically, I have a entity called Member and it contains the following property
 * @ORM\OneToMany(targetEntity="MemberTranslation", mappedBy="member")
 * @Expose

private $translations;

Now I want to PUT data to translations but I have no idea how can I do that through JSON.

Here is more at stackoverflow: http://stackoverflow.com/questions/29504086/fosrestbundle-put-one-to-many-relation

Would be nice if someone could help me out.

**Comment by grzegorztomasiak** [comment]
I have solved the issue by changing the structure, so I dropped one to many relation.

**Comment by Bencsi** [comment]
How did you solved? I'am stuck with problem.

**Comment by grzegorztomasiak** [comment]
I did not find the solution to this so I had to drop the idea and redesign the database.

My previous setup was to have Member entity that can have multiple MemberTranslation entities,  because at that time I thought it's going to be best way.

Member:
    MemberTranslation: 1, pl, Witaj
    MemberTranslation: 2, en, Hello
    MemberTranslation: 3, it, Ciao

Now translatable properties (columns) are only in Member entity

Member: 1, array('pl' => 'Witaj', 'en' => 'Hello', 'it' => 'Ciao')
