### ISSUE TITLE
How to serialize an instance of stdClass to Json ?

### ISSUE THREAD

**Issue by oliver13** [FriendsOfSymfony/FOSRestBundle#1016]
Hello,

I would like to serialize an instance of stdClass with setData($instance_of_stdclass). 
But I get an empty json string in my request response.

Controller:
```php
    /**
     * @Rest\View
     * @return View
     */
    public function getAction(Request $request, $id)
    {       
        $view = View::create();
        
        [...]

        $view->setStatusCode(Response::HTTP_OK);      
        $view->setData($instance_of_stdclass);  
        return $this->handleView($view);
    } 
```

Would be nice to get a hint how to solve this. Thanks in advance.

**Comment by lsmith77** [comment]
this is an issue with JMS serializer. one option would be to cast it to an array.

**Comment by lsmith77** [comment]
this might help https://github.com/schmittjoh/serializer/pull/429

**Comment by oliver13** [comment]
Thank you for the hint. I will try it soon with the stdClass handler.
For the moment a hack helped me: 

$data = json_decode(json_encode($instance_of_stdclass), true);
