### ISSUE TITLE
No route found

### ISSUE THREAD

**Issue by dotlg** [FriendsOfSymfony/FOSRestBundle#1021]
Hi all,

I have an issue with FOSRestBundle. When I use a parameter with a format extension (for instance "file_to_delete.mp4") in the URL I get a "No route found" error. Looks like the parser stops at the "." and since it's in this case .mp4 and not the .json it fails.

Request URL
/api/encoderrecordedfiles/{filename}.{_format}
DELETE /api/encoderrecordedfiles/file_to_delete.mp4.json

I tried to add "include_format: false" in config.yml and it's working, but then I'm not able to choose the format anymore (json/xml).

Did I miss something ?

Thanks

**Comment by lsmith77** [comment]
I am not surprised that you are running into issues there. using extensions to "pick" the input/output format is really a kludge. you should instead send the proper ``Content-Type`` and ``Accept`` headers, ie ``application/json`` and ``application/xml``.

**Comment by dotlg** [comment]
Hello and thanks for the answer.

So I'll keep the "include_format: false".

But I still have difficulties to understand how I can choose the input/output format. If I'm not mistaken I should be able to choose the input format with "Content-type", and choose the output format with "Accept". But when I'm trying to output an xml body response with the "Accept" "application/xml" header I still get a non-xml response.

Can I send a POST request with a json content ("Content-Type", "application/json" header added), but with an XML output ("Accept", "application/xml" header added)? It's not working for me right now.

My FOSRestBundle configuration is:

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
        include_format: false

**Comment by lsmith77** [comment]
I think your issue is that you have not specified any rules or the ``format_listener`` .. but yes you should be able to process json input with the body listener and generate XML with the view handler as output the way you describe.

**Comment by dotlg** [comment]
Ok thanks a lot. I've added rules and it's working fine now :)

format_listener:
        rules:
            - { path: ^/api/, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
