### ISSUE TITLE
Using this bundle next to non-rest controllers

### ISSUE THREAD

**Issue by raulferras** [FriendsOfSymfony/FOSRestBundle#1026]
I've been using this bundle to deploy some actions as a REST interface, but been having problems with the non-REST ones.
Specifically with the CSRF token validations.

As the `DisableCSRFExtension` is included, csrf validation is disabled when the user has the required role (ex: is authenticated). This has sense for REST requests/interfaces, but for those non-REST interfaces CSRF protection is still required and as the CSRF token generation is disabled this exposes some security problems (also, some non carefull templates fail when trying to render form._token as it is not defined anymore).

This leads me to think this bundle is not to be thrown in those applications with non-REST interfaces.

Am I right? Or Am I facing a total different problem?

**Comment by lsmith77** [comment]
Your question should be answered via:
http://symfony.com/doc/master/bundles/FOSRestBundle/2-the-view-layer.html#csrf-validation

If not please reopen.
