### ISSUE TITLE
Name Prefix Ignored in Yaml

### ISSUE THREAD

**Issue by jtherin** [FriendsOfSymfony/FOSRestBundle#1029]
I have a small naming problem with name_prefix parameter.

Here is the configuration used :

**app/config/routing.yml**
```
_company_api:
    resource: routing/api.yml
    prefix:   /api
    type:     rest
```
**app/config/routing/api.yml**
```
_company_api_v1:
    type:     rest
    resource: api_v1.yml
    prefix:   /v1
    name_prefix: api_v1_
```
**app/config/routing/api_v1.yml**
```
company_api_v1_somethingbundle:
    type:     rest
    resource: "@CompanyApiV1SomethingBundle/Resources/config/routing.yml"
```
**src/Company/Api/V1/SomethingBundle/Resources/config/routing.yml**
```
company_api_v1_somethingbundle_first:
    type:     rest
    resource: Company\Api\V1\SomethingBundle\Controller\FirstController

company_api_v1_somethingbundle_second:
    type:     rest
    resource: Company\Api\V1\SomethingBundle\Controller\SecondController
```

With an `app/console router:debug`, I get :

```
 get_first                         GET      ANY    ANY  /api/v1/first
 get_second                        GET      ANY    ANY  /api/v1/second
```

But I was expecting something like this :

```
 api_v1_get_first                  GET      ANY    ANY  /api/v1/first
 api_v1_get_second                 GET      ANY    ANY  /api/v1/second
```

The `name_prefix: api_v1_` parameter seems to be ignored :(.
How can I fix this?

**Comment by lsmith77** [comment]
i think I seem to remember having seen this noted before .. best would be to investigate the code inside the Routing namespace in this Bundle to try and come up with a fix.

**Comment by tim96** [comment]
Hello @jtherin , @lsmith77 .
I suggest this solution #1047 .
