### ISSUE TITLE
Symfony setTemplate() function clarification

### ISSUE THREAD

**Issue by webgear** [FriendsOfSymfony/FOSRestBundle#1030]
Hello,

I was curious as to what the setTemplate() method should do. Take, for a simple example, the following code:

    public function getObjectsAction()
    {
        $objects = $this->getDoctrine()->getRepository('SomeBundle:Object')->findAll();

        $view = $this->view($objects, 200);

        return $this->handleView($view);
    }

This correctly returns a JSON object containing all the properties of the object. But in the symfony official documentation found here: http://symfony.com/doc/current/bundles/FOSRestBundle/2-the-view-layer.html there is a call to setTemplate() and some setTemplateVar() calls. I was wondering what the setTemplate was for. I mean, how am I supposed to use the twig file passed in to that function and for what purpose? Is it even necessary?

I realize this might be obvious, but I couldn't find any documentation related to this, so if possible, please point me to the right direction. Thank you in advance.

**Comment by lsmith77** [comment]
the method is only relevant if you do not use the serializer but instead use the templating. but default html will use templates, while json/xml will use the serializer. this is configurable as per the view Bundle configuration. the idea is to enable controllers that can serve both html and xml/json etc.
