### ISSUE TITLE
FOSRestBundle setup for return JSON but still asking for Twig template

### ISSUE THREAD

**Issue by paquitodev** [FriendsOfSymfony/FOSRestBundle#1031]
I have configured FOSRestBundle as following:

    #FOSRestBundle
    fos_rest:
        param_fetcher_listener: true
        body_listener: true
        format_listener:
            rules:
                - { path: ^/, priorities: [ json, html ], fallback_format: ~, prefer_extension: true }
            media_type:
                version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    
        body_converter:
            enabled: true
            validate: true
    
        view:
            mime_types:
                json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
            view_response_listener: 'force'
            formats:
                xml:  false
                json: true
            templating_formats:
                html: true
    
        exception:
            codes:
                'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
                'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            messages:
                'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
        allowed_methods_listener: true
        access_denied_listener:
            json: true

And I have this at controller:

namespace PDI\PDOneBundle\Controller\Rest;

use FOS\RestBundle\Controller\FOSRestController;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use FOS\RestBundle\Controller\Annotations\QueryParam;
use FOS\RestBundle\Controller\Annotations\Get;

    class RepresentativeRestController extends FOSRestController
    {
        /**
         * Get all representatives.
         *
         * @return array
         *
         * @ApiDoc(
         *   resource = true,
         *       https = true,
         *   description = "Get all representatives.",
         *   statusCodes = {
         *      200 = "Returned when successful",
         *      400 = "Returned when errors"
         *   }
         * )
         * @Get("/api/v1/reps")
         */
        public function getRepsAction()
        {
            $em = $this->getDoctrine()->getManager();
            $entities = $em->getRepository('PDOneBundle:Representative')->findAll();
    
            if(!$entities)
            {
                return $this->view(null, 400);
            }
    
            return $this->view($entities, 200);
        }
    }

But when I try the following URL `app_dev.php/api/v1/reps` I got this error:

> Unable to find template "". 500 Internal Server Error -
> InvalidArgumentException 3 linked Exceptions: Twig_Error_Loader »
> InvalidArgumentException » InvalidArgumentException »

I expect that API return a well formed JSON as the following example:

    {
       "id":"30000001",
       "veeva_rep_id":"0055648764067SwzAAE",
       "display_name":"John Know",
       "avatar_url":"http://freelanceme.net/Images/default%20profile%20picture.png",
       "rep_type":"VEEVA",
       "username":"john@mail.com",
       "first":"John",
       "last":"Know",
       "title":"Sales Representative",
       "phone":"800-555-1212",
       "email":"john@mail.com",
       "territory_id":"200454001",
       "inactive":"no",
       "total_contacts":"6",
       "total_shares":"0",
       "totalViews":"0",
       "lastLoginAt":"2015-05-05 15:45:57",
       "lastVeevaSyncAt":"2015-05-05 15:45:57",
       "createdAt":"2015-05-05 15:45:57",
       "updatedAt":"2015-05-05 15:45:57"
    }

Is not FOSRestBundle configured for return JSON? Why still asking for Twig template? How can I fix this?

__First test:__

I have tried using Postman and after set the header `Content-Type` to `application/json` the error turns into this 

> Malformed JSON

so, the FOSRestBundle is not setting up headers as should be and controller is not returning a valid JSON, how do I fix those ones?

__Second test:__

I have run this test:

    /**
     * Get all representatives.
     *
     * @return array
     *
     * @ApiDoc(
     *   resource = true,
     *       https = true,
     *   description = "Get all representatives.",
     *   statusCodes = {
     *      200 = "Returned when successful",
     *      400 = "Returned when errors"
     *   }
     * )
     * @Get("/api/v1/reps")
     * @View()
     */
    public function getRepsAction()
    {
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository('PDOneBundle:Representative')->findAll();

        $temp = array("1", "2", "3");

        $view = $this->view($temp, Codes::HTTP_OK);
        return $this->handleView($view);
    }

And still the same issue:

> Unable to find template "". 500 Internal Server Error -
> InvalidArgumentException 3 linked Exceptions: Twig_Error_Loader »
> InvalidArgumentException » InvalidArgumentException »

What else can be wrong here? Did I'm missing something at configuration? 

I forgot to add `app/config/routing.yml` and `src/PDI/PDOneBundle/Resources/config/routing.yml` at first so here them goes, perhaps this is the missing piece on the puzzle and give you a better idea of where the problem comes from:

    #app/config/routing.yml
    #PDOne
    pdone:
        resource: "@PDOneBundle/Resources/config/routing.yml"
    
    template:
        resource: "@TemplateBundle/Resources/config/routing.yml"
    
    #FOSUserBundle
    fos_user:
        resource: "@FOSUserBundle/Resources/config/routing/all.xml"
        prefix: /
    
    #NelmioApiDocBundle:
    NelmioApiDocBundle:
        resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
        prefix:   /api/doc
    
    #SonataAdmin
    admin:
        resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
        prefix: /admin
    
    _sonata_admin:
        resource: .
        type: sonata_admin
        prefix: /admin

    #src/PDI/PDOneBundle/Resources/config/routing.yml
    pdone:
        resource: "@PDOneBundle/Controller/"
        type:     annotation
        prefix:   /

__Third test:__

Definitely something is wrong with request from client side, if I use a tool like `Postman` and set proper headers I got the entities as I want, see pic below:

![enter image description here][1]

I can't find where the problem is so I desperately need someone's help here because I was already out of ideas

  [1]: http://i.stack.imgur.com/X4Bsp.png

**Comment by lsmith77** [comment]
you are using the ViewResponseListener, do you also have the SensioFrameworkExtraBundle installed and if yes did you configure it according to the documentation of the ViewResponseListener?

**Comment by paquitodev** [comment]
I'm also change a bit the config for FOSRest, see below the current one:

    fos_rest:
        param_fetcher_listener: true
        body_listener: true
        format_listener:
            rules:
                - { path: ^/, priorities: [ json, html ], fallback_format: ~, prefer_extension: false }
            #media_type:
            #    version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    
        body_converter:
            enabled: true
            validate: true
    
        view:
            view_response_listener: 'force'
            formats:
                xml: true
                json: true
            templating_formats:
                html: true
            force_redirects:
                html: true
            failed_validation: HTTP_BAD_REQUEST
            default_engine: none
            mime_types:
                json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
    
        exception:
            codes:
                'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
                'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            messages:
                'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
        allowed_methods_listener: true
        access_denied_listener:
            json: true
        routing_loader:
            default_format: json

**Comment by lsmith77** [comment]
did you set a an Accept header to ``application/json`` the Content-Type defines the encoding of your request body, the Accept header defines what you expect as the format for the response body.

**Comment by paquitodev** [comment]
I'm confused,how I do that? What are you trying to show me? Did you see my latest configuration?

**Comment by paquitodev** [comment]
@lsmith77 do I need to setup any Twig view or anything else? If I change this:

        rules:
            - { path: ^/, priorities: [ json, html ], fallback_format: ~, prefer_extension: false }

To this:

        rules:
            - { path: ^/, priorities: [ json ], fallback_format: ~, prefer_extension: false }

I'm able to view the JSON response but then all my HTML content stop working and I got sources in plain text, why?

**Comment by lsmith77** [comment]
You said the following:
```I have tried using Postman and after set the header Content-Type to application/json the error turns into this```

What I am telling you is that the Content-Type is irrelevant for the output format, you instead need to set the Accept header in your request.
