### ISSUE TITLE
PUT form "multipart/form-data" empty request (only on nginx)

### ISSUE THREAD

**Issue by benjaminb-** [FriendsOfSymfony/FOSRestBundle#1032]
Hi,

When i make a put request on a form with enctype "multipart/form-data" the request become empty.
It seems the problem appears only on nginx ? My local version with apache is working.

Thanks in advance

**Comment by lsmith77** [comment]
i think in general multipart message handling is not ideal in the Request class in general. our BodyListener is also not really ready for it either.

**Comment by benjaminb-** [comment]
Ok so i transform my PUT request into POST request and it's working (it's not RESTful but i didn't find any other easy way to make working it)

Thanks

**Comment by ianfp** [comment]
Can we reopen this issue? I'm having the same problem. It seems like PHP does not populate the $_POST superglobal for PUT requests.

**Comment by Ener-Getick** [comment]
@ianfp this is not related to FOSRestBundle but to php itself.

**Comment by ianfp** [comment]
@Ener-Getick Yes, but isn't the purpose of FOSRestBundle to help us do these sorts of things? I realize this issue is a feature request and not a bug.

**Comment by xabbuh** [comment]
@ianfp In fact, the content type (not the HTTP method) is important when you build the request (it has to be `application/x-www-form-urlencoded`). And there is nothing we can do about that else as this is a limitation given by PHP.
