### ISSUE TITLE
Allow use of placeholders as requirements in Query/RequestParam

### ISSUE THREAD

**Issue by rpg600** [FriendsOfSymfony/FOSRestBundle#1039]
It could be nice to be able to replace placeholders with the service container parameters just like the symfony Router (see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L131).

For example : 
```@QueryParam(name="user_uuid", requirements="%regex_uuid%")```
instead of
```@QueryParam(name="user_uuid", requirements="^[0-9a-f]{6}-[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")```

The drawback is that we need to inject to container into the ParamFetcher.

What do you think ?

**Comment by lsmith77** [comment]
yeah .. why not
