### ISSUE TITLE
Support for Symfony2.3 dropped as weel with version 1.6.0

### ISSUE THREAD

**Issue by moroine** [FriendsOfSymfony/FOSRestBundle#1045]
I see releases changelog and I see you dropped support for Symfony2.2.

I am on symfony/symfony: v2.3.28 and v2.3.4.

When I run `composer update` I got: 
```
PHP Fatal error:  Declaration of FOS\RestBundle\Request\RequestBodyParamConverter::apply() must be compatible with Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface::apply(Symfony\Component\HttpFoundation\Request $request, Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationInterface $configuration) in /var/www/Adsum/adsum-studio/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/Request/RequestBodyParamConverter.php on line 21
```

If I come back to 1.5.* all works fine.

**Comment by stof** [comment]
Your issue is not related to Symfony 2.3 at all, but to SensioFrameworkExtraBundle, which has its own versioning.

The bundle now supports both SensioFrameworkExtraBundle 2 and 3, but you could indeed have an issue in case you boot your project with an old cache (which happens in no-debug mode when calling the ``cache:clear`` command). the solution is to remove the outdated cache manually with ``rm -rf app/cache/prod`` (adapt it for your environment). The fact that clearing the cache requires to be able to boot the kernel with the new code but with the old cache is a known issue in Symfony (and not easy to fix)

**Comment by moroine** [comment]
I realized I didn't give enough information.

First of all I know this bundle require SensioFrameworkExtraBundle, so the two versions tag I gave was :
  - Symfony: v2.3.28
  - SensioFrameworkBundle: v2.3.4

Then the problem didn't appears on `composer update` but when I call `php app/console cache:clear` (it appears for me cause I call automatically `cache:clear` after updating dependencies).

So I tried your solution and message error is always here (I also remove dev cache folder).

I investigate the problem and I think I found the compatibility issue: 

`FOSRestBundle:Request:RequestBodyParamConverter` extends `FOSRestBundle:Request:AbstractRequestBodyParamConverter` witch implements `FrameworkExtraBundle:Request:ParamConvertor:ParamConverterInterface`

So second parameter `$configuration` of `RequestBodyParamConverter:apply` need to implements `Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationInterface` according to `ParamConverterInterface` declaration. But `$configuration` is instance of `Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter` witch do not implement the required interface.

Hopping this will be helpful.

**Comment by lsmith77** [comment]
I personally do not use param converters .. so it would be great if you could try and fix this. In the end we might need some logic in the DI extension to detect which version of the SensioFrameworkExtraBundle is installed and adjust the DI config accordingly.

**Comment by xabbuh** [comment]
@lsmith77 Wouldn't it be sufficient to revert the changes related to the `BodyParamConverter` from a336335826934d96ec572bfdb283e047f79becfd?

**Comment by lsmith77** [comment]
yeah .. looks like we need to reintroduce ``RequestBodyParamConverter20``

**Comment by lsmith77** [comment]
anyone have time to work on this today? would love to release 1.6.1 ideally tonight

**Comment by lsmith77** [comment]
basically it just requires reverting the relevant code but should ideally also contain a new test so that we will catch this in the future

**Comment by xabbuh** [comment]
I'm working on it.

**Comment by xabbuh** [comment]
see #1057
