### ISSUE TITLE
problems updating from 1.5.3 to 1.6 = unusable

### ISSUE THREAD

**Issue by gondo** [FriendsOfSymfony/FOSRestBundle#1048]
config has changed between `1.5.*` and `1.6` but there is no info about how it should be updated.
looking at http://symfony.com/doc/master/bundles/FOSRestBundle/configuration-reference.html
things i can see:
`param_fetcher_listener` is not ` value` anymore but `array` and also it works somehow differently by looking at code change
same for `view_response_listener`

my biggest problem is with `mime_types` as mentioned here #438 
`charset=UTF-8` is not added to response anymore and therefore any output is unusable

**Comment by lsmith77** [comment]
can you paste your config (or better yet add a test case with your config)? we tried to make provisions so that no changes to existing configuration is necessary.

**Comment by gondo** [comment]
sure, here:
```

fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    service:
        inflector: app_utill_noopInflector #disable pluralization of routes
    view:
        view_response_listener: force
        mime_types:
            json:
                - "application/json; charset=UTF-8"
                - "application/json"
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    serializer:
        serialize_null: true
```

**Comment by lsmith77** [comment]
oh and what is the error you are seeing?

**Comment by gondo** [comment]
the first "error" was, that response is served without `charset=Utf-8` and therefore its unreadable
than i tried to downgrade to different RC and started to receive errors regards invalid config, but i assume those were fixed or silenced in none RC release of 1.6.
now i am not sure if my config is still working or just silently being accepted, but the only real problem is the encoding. as mentioned in #438

**Comment by lsmith77** [comment]
#1053 should fix the issue

**Comment by gondo** [comment]
thx
