### ISSUE TITLE
Change `_method` to `methods`

### ISSUE THREAD

**Issue by Padam87** [FriendsOfSymfony/FOSRestBundle#1051]
Hi,

As of symfony 2.7, every route defined with the rest bundle annotations creates a deprecation warning.

We have about 65 routes, generating 90% of our warnings. Should I create a pr replacing `_method` everywhere? Since the bundle requires 2.3, it should be fine IMO.

What do you think?

**Comment by stof** [comment]
Yes, please send a PR doing the upgrade

**Comment by lsmith77** [comment]
will be fixed in 1.7.0
