### ISSUE TITLE
body_listener & php://input

### ISSUE THREAD

**Issue by dotlg** [FriendsOfSymfony/FOSRestBundle#1059]
Hello,

I'm trying to use HTTP PUT to load (big) files and send them directly to a S3 bucket. For that I have to use fopen('php://input', "r") in the function, I cannot use the $request object.

It's working fine when I set the body_listener to false in the fos_rest config. When I do that my Post functions are not working anymore (they use the $request object). If I set the body_listener to true my Post functions are working fine but I cannot use the fopen('php://input', "r") anymore.

How can I avoid that ? Can I set the body_listener to false just for one function ?

Thanks.

**Comment by lsmith77** [comment]
as of 1.6.0 there is an extension point for this: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1034

**Comment by dotlg** [comment]
Thanks for your quick answer :)

But how/where do you use this extention point to exclude a specific function from the body_listener ? I searched in the documentation, but I was unable to find anything about that.

**Comment by lsmith77** [comment]
you set a custom service as the listener and implement custom logic in the isDecodeable method

**Comment by dotlg** [comment]
Ok thanks, got it !

**Comment by lsmith77** [comment]
that being said .. if you make it work .. maybe you can update the docs with that example?

**Comment by dotlg** [comment]
sure, will do !
