### ISSUE TITLE
JSON response with additional data

### ISSUE THREAD

**Issue by edamov** [FriendsOfSymfony/FOSRestBundle#1061]
I need to extend json response with some additional data.
For, example:

```
getAction($id)
{
    return $this->container->get('doctrine.entity_manager')->getRepository('Products')->find($id);
}
```
This action return data in format:
```
{
   "id": 1,
   "name": "phone",
   "price": 100.00
}
```

But I need to extend all responses on GET requests with some additional data:
```
{
   "data": {
       "id": 1,
       "name": "phone",
       "price": 100.00
   },
   "options": {...},
   "relations": {...},
   "version": {...}
}
```

What is the best way to do it?

**Comment by lsmith77** [comment]
You can maybe do something via a JMS visitor. Alternatively you can extend the base ``ViewHandler`` in this Bundle. Finally you could introduce your own ``View`` base class that decorates the data automatically.
