### ISSUE TITLE
Update DisableCSRFExtension

### ISSUE THREAD

**Issue by peshi** [FriendsOfSymfony/FOSRestBundle#1063]
Update for 2.7+

SecurityContextInterface, setDefaultOptions(OptionsResolverInterface).

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Form/Extension/DisableCSRFExtension.php#L28

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Form/Extension/DisableCSRFExtension.php#L34

**Comment by lsmith77** [comment]
can you work on this?

**Comment by peshi** [comment]
@lsmith77 There's no BC layer
