### ISSUE TITLE
Allow use of Constants in Annotations

### ISSUE THREAD

**Issue by bmeynell** [FriendsOfSymfony/FOSRestBundle#1073]
When used in annotations, constants do not appear to be interpolated and are interpreted as literal strings.

In the following example, *Category::TYPE_BOOKS* is returned from $paramFetcher->get('categories')

```php
use MyCompany\Category;
/**
 * @QueryParam(name="categories", default="Category::TYPE_BOOKS", description="Category filters.")
*/
public function getGuideAction(ParamFetcher $paramFetcher)  
{                                                                              
    var_dump($paramFetcher->get('categories'));exit;
}
```

Both [doctrine2](http://doctrine-common.readthedocs.org/en/latest/reference/annotations.html#constants) and [JmsDiExtraBundle](http://jmsyst.com/bundles/JMSDiExtraBundle/master/annotations#observe) support constants in annotations so it seems viable to also support here.

**Comment by lsmith77** [comment]
sure .. can you investigate how they are able to support this and submit a PR for this?

**Comment by Ener-Getick** [comment]
Why did you put parenthesis ? 
You should write:
```php
/**
 * @QueryParam(name="categories", default=Category::TYPE_BOOKS, description="Category filters.")
 */
```

**Comment by bmeynell** [comment]
@Ener-Getick is right: Both `default=Category::TYPE_BOOKS` and `default={Category::TYPE_BOOKS, Category::TYPE_ELECTRONICS}` work. Closing.
