### ISSUE TITLE
FOSRestBundle 2.0

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#1076]
It seems like its time to break some BC (see #1074), so what else should be change?

See also https://github.com/FriendsOfSymfony/FOSRestBundle/milestones/2.0
Of course some better solution for API versioning would be great but someone needs to make it happen too.

Also check https://github.com/FriendsOfSymfony/FOSRestBundle/milestones/1.8 and the open PRs/tickets in general.

For new stuff it would be best to open a ticket/PR. Then make sure to mention the ticket/PR of existing or newly created tickets here so that I can take care of adding the milestone.

**Comment by lsmith77** [comment]
BTW .. there might also be things from FOSRestBundle that we could consider pushing into 2.8/3.0 which would result in the question what the target version for FOSRestBundle 2.0 is .. right now I would say 2.7 but 2.8/3.0 is also a possibility.

**Comment by stof** [comment]
I think supporting 2.7 is a must-have for now (2.8 is not even released). It depends on the date at which you plan to release it though

**Comment by florianv** [comment]
> so what else should be change?

I read that some people complain about the size of this Bundle (it's quite big indeed). I think it's not easy for newcomers to apprehend it.

I was thinking that some features like the annotations could be moved to a `FOSRestExtraBundle` ? The idea would be to keep only the *core* features to have a functional api.
