### ISSUE TITLE
Using setTemplateData on annotation actions

### ISSUE THREAD

**Issue by gtrias** [FriendsOfSymfony/FOSRestBundle#1078]
I'm trying to get my controllers format agnostic and I really would like to be able to use the @View annotations in conjunction with the method setTemplateData in order to pass variables to template not to serialize.

As in documentation but for the @View annotation actions:

```
        $view = $this->view($products, 200)
            ->setTemplate("MyBundle:Category:show.html.twig")
            ->setTemplateVar('products')
            ->setTemplateData($templateData)
        ;
```

Is there any way to accomplish this? I cannot found anything on documentation either stackoverflow, etc...

**Comment by lsmith77** [comment]
this should already work .. what behavior are you experiencing that makes you believe it doesn't?

**Comment by gtrias** [comment]
Well, I would like to have my actions something like this:

```
    /**
     * @Rest\View()
     */
    public function indexAction()
    {
        ...
        $dataNotToSerialize = array();
        $this->setTemplateData($dataNotToSerialize); // This is the functionality that I missing
        return $data;
    }
```

Instead of this: 

```
    public function indexAction()
    {
        ...
        $view = $this->view($entities, 200)
            ->setTemplate("ACSACSPanelBundle:Domain:index.html.twig")
            ->setTemplateVar("entities")
            ->setTemplateData($dataNotToSerialize)
        ;
        return $this->handleView($view);
    }
```
I would like to omit the setTemplate and setTemplateVar as it could be handled by the View annotation.. 
Is it possible to be achieved what I want?

**Comment by lsmith77** [comment]
yes from memory it should be possible to do ``@Rest\View(template="..",templateVar="..")``
if this works feel free to send a PR to illustrate this in the docs

**Comment by gtrias** [comment]
Ok I see, 

So this works well.

```
    /**
     * @Rest\View()
     */
    public function indexAction()
    {
        ...
        $view = $this->view($entities, 200)
            ->setTemplateData($dataNotToSerialize)
        ;
        return $this->handleView($view);
    }
```

I would like to have a way to return directly the data to be serialized as you can do with the View annotation but keeping the possibility to set data not to be serialized. But this approach is OK for me.

Should I create a PR to illustrate this scenario in the docs?

**Comment by lsmith77** [comment]
well you cannot return 2 pieces of data, the serialized data and the template data, without a structure of sorts and this structure is a View instance.

what you can do however if add a simple if in your controller to determine if the output format will use the serializer or not using ``$viewHandler->isFormatTemplating($request->getRequestFormat()``

**Comment by gtrias** [comment]
Thank you, @lsmith77 

I had a mistake with the previous message I haven't tested the action on html format calls. 
So now I can confirm that way doesn't works as expected. If you use the `return $this->handleView($view);` all the annotation stuff is ignored :(

So, the conclusion is if you need to set templateData you only can do it using the `handleView`  and there's nothing you can do with annotations...

**Comment by lsmith77** [comment]
``return $this->handleView($view)`` will return a ``Response`` instance, which will need have the result of not triggering the listener responsible for the ``View`` annotation. In other words to use the ``View`` annotation you must not return a ``Response`` but either a ``View`` instance or anything else.

**Comment by gtrias** [comment]
Yes! That make the trick. I've tried returning the $view object directlly and it works like charm.

Thank you a lot @lsmith77

**Comment by lsmith77** [comment]
ok great.
