### ISSUE TITLE
requirement: RequestParam and latin characters

### ISSUE THREAD

**Issue by juliomatcom** [FriendsOfSymfony/FOSRestBundle#1079]
I don't know if this is a improvement or an issue but if we use the annotation:

 @RequestParam(name="name", requirements="[a-zA-Z\s]+")

and in the Request name is like "César" (note the é character) then ParamFetcher->get('name') returns:

{
    ["code"]=>
    int(400)
    ["message"]=>
    string(11) "Bad Request"
  }
}

The thing is that this error not mention/show the field affected, and the developers got confused, otherwise if the name is '44b' then the field 'name' is mention in the error, so you can fix it.

**Comment by lsmith77** [comment]
hmm so it seems like something is breaking with non ascii characters badly so that we cannot report the error properly? can you investigate to see what happens differently in the two cases?

**Comment by juliomatcom** [comment]
hey, i try this again but its just happened that i was on prod environment and messages was like this.. 
im sorry , there is no issue with latin character at all :+1: 

<pre><code>
{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  }
}
...
</pre>
</code>

and in prod

<pre><code>
{
  "error": {
    "code": 400,
    "message": "Bad Request",
    "exception": [
      {
        "message": "Request parameter nombre value 'César' violated a constraint (Request parameter value 'César', does not match requirements '[a-zA-Z]')",
...
</code>
</pre>
