### ISSUE TITLE
RestBundle routes doesnt support hostname matching

### ISSUE THREAD

**Issue by brpaz** [FriendsOfSymfony/FOSRestBundle#1082]
In standard Symfony routing, you can say that a specific route will only match if the hostname matches a defined parameter. See http://symfony.com/doc/current/components/routing/hostname_pattern.html

FosRestBunlde seems to npt support this behaviour.

In RestYamlCollectionLoader "host" parameter is not read from configs. I think its a simple fix. I can try to make a PR

**Comment by lsmith77** [comment]
sure .. I think this feature was added later on .. please make sure to also update the tests (and docs if necessary)

**Comment by pedroresende** [comment]
@lsmith77 This is a possible PR for this

**Comment by xabbuh** [comment]
This was fixed by #1564.
