### ISSUE TITLE
Customize XML handleView

### ISSUE THREAD

**Issue by angezanetti** [FriendsOfSymfony/FOSRestBundle#1083]
Hey guys, 

Is there a way to customize the XML return when using handleview()?

The default XML looks like:

````
<result>
    <entry>
         <eval>0</eval>
    </entry>
</result>
````

It does not fit my needs, i would like to change the `result` and `entry` tags. I read the docs, saw that you can use custom views, but it does not seems to work the way i would like.

Any tips ?

**Comment by lsmith77** [comment]
yes its possible. look at the documentation of the serializer that you use. you will then need to add relevant mapping information to your entities.
