### ISSUE TITLE
How to add new property to api? [This form should not contain extra fields]

### ISSUE THREAD

**Issue by edouardkombo** [FriendsOfSymfony/FOSRestBundle#1084]
Hi,

I'm using SonataUserBundle and I am stucked since hours.

I've overrided User entity and added new properties correctly.
Now, I want these new properties to be accessible through the api, but the error I get is that:

    {"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."]...

I've overrided the FOSUserbundle seializer config with the new fields I want, but still have nothing.

Any answer?

**Comment by lsmith77** [comment]
this is an issue with Symfony forms .. and not related to this Bundle or the serializer
