### ISSUE TITLE
Routing annotation conflicts

### ISSUE THREAD

**Issue by murilolobato** [FriendsOfSymfony/FOSRestBundle#1086]
The annotations @Get, @Post, etc.. are being incorrectly loaded by Symfony Annotation loader

```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin

api:
    type: rest
    resource: "@AppBundle/Resources/config/api_routing.yml"
```

My web controllers are defined in the namespace AppBundle\Controller and my API's controllers are defined in AppBundle\Controller\Api

This is causing the following controller:
```
namespace AppBundle\Controller\Api;

// ...
class ResettingController extends Controller
{
    /**
     * @Post("/resetting")
     */
    public function postResettingAction(Request $request)
    {
      // ..
    }
}
```

to be loaded 2 times, as:

/admin/resetting and /api/v1/resetting

There is a way to say to annotation loader to skip a folder? Or even, fix the @Post annotation to not be loaded by symfony annotation route louder.

**Comment by lsmith77** [comment]
I do not think that there is a way.

/cc @stof

**Comment by lsmith77** [comment]
you can try something like this:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Tests/Fixtures/Controller/AnnotatedConditionalUsersController.php#L100

**Comment by Ener-Getick** [comment]
We can't fix that as our annotations extend the annotations of symfony.

**Comment by murilolobato** [comment]
The solution for this, is to have two folders inside Controller: Web and Api, as suggested on 3:27 at this video https://knpuniversity.com/screencast/symfony-rest/post
