### ISSUE TITLE
ViewResponseListener test failing with FrameworkExtraBundle >= 3.0.10

### ISSUE THREAD

**Issue by alekitto** [FriendsOfSymfony/FOSRestBundle#1088]
I ran the test suite against the `master` branch and i discovered that `ViewResponseListenerTest::testOnKernelViewWhenControllerResultIsNotViewObject` is failing when testing with framework-extra-bundle >= 3.0.10

Specifically, i noticed that the line containing
```
$this->container->get('templating')
```
that was expected to be called, was moved and is not reached anymore causing the test to fail.

**Comment by lsmith77** [comment]
@alekitto can you identify which PR and who made the change in the SensioFrameworkExtraBundle and point them at this ticket?

**Comment by sarcher** [comment]
I ran into this as well just now after catching up my dependencies on a rebase. The relevant PR is sensiolabs/SensioFrameworkExtraBundle#369 (ping @derrabus)

Since the test is just verifying the code path, a simple fix is to replace this:

```php
        $request = new Request();

        $event = $this->getResponseEvent($request, array());
        $event->expects($this->never())
            ->method('setResponse');

        $this->container->expects($this->once())
            ->method('get')
            ->with($this->equalTo('templating'))
            ->will($this->returnValue($this->templating));

        $this->listener->onKernelView($event);
```

With this:

```php
        $request = new Request();

        $event = $this->getResponseEvent($request, array());
        $event->expects($this->never())
            ->method('setResponse');

        $this->assertEquals(array(), $this->listener->onKernelView($event));
```

But maybe there is something better?

**Comment by lsmith77** [comment]
sounds good to me .. can you submit a PR?

**Comment by sarcher** [comment]
All set, the above change is in there now. Everything passes on my end and Travis looks good.

**Comment by derrabus** [comment]
Sorry for breaking your test. ;-)

The failing test made assertions on the behavior of FrameworkExtraBundle which is obviously not its purpose. @sarcher's change sounds reasonable to me. I've tested #1091 with FrameworkExtraBundle 3.0.10 as well as 3.0.9 and the test passed in both cases.
