### ISSUE TITLE
@QueryParam with POST

### ISSUE THREAD

**Issue by dotlg** [FriendsOfSymfony/FOSRestBundle#1089]
Hello,

I get a "Query parameter \"provider\" is empty" error when I try to use a @QueryParam annotation with a POST request.

I know I could add a parameter in the URL like this **/api/v1_0/{provider}/live/entry**. But I need to use an url parameter like this **/api/v1_0/live/entry?provider=xxx**. It's working for GET requests, but I cannot get it to work with POST requests.

Is it standard behavior or it should work (maybe a fosrest config) ?

```
/**
     * @QueryParam(name="provider", nullable=false, strict=true, description="Name of the service provider")
     * @ApiDoc(
     *  description="Create StreamingLiveEntry",
     *  section="Streaming Live"
     * )
     */
    public function postV1_0LiveEntryAction(ParamFetcherInterface $paramFetcher, Request $request) {
        dump($paramFetcher->all());
        ...
    }
```

Many thanks.

**Comment by lsmith77** [comment]
honestly I am not sure if we intentionally prevent POST from working .. the relevant code is here https://github.com/FriendsOfSymfony/FOSRestBundle/tree/master/Request .. maybe you can investigate

**Comment by dotlg** [comment]
Ok thanks, I'll check there.

**Comment by Ener-Getick** [comment]
The parameters are taken directly from the request which is filled by the symfony core.
It might be a symfony bug but I don't think so.

Try to set a default value for this param and check if you get the default value or something else.

**Comment by Ener-Getick** [comment]
Did you try with the last version or the dev version ?
