### ISSUE TITLE
ExceptionController configuration within fos_rest

### ISSUE THREAD

**Issue by gsdevme** [FriendsOfSymfony/FOSRestBundle#1090]
Hi,

Im working on an application that has the following configuration within its `Twig:` however this causes the 2.6 feature for previewing error pages to not work. 

`exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'`

The follow documentation states I can add it within the `fos_rest` configuration however I don't see anykind of support for this with the `Configuration.php` nor does it work.

http://symfony.com/doc/current/bundles/FOSRestBundle/4-exception-controller-support.html

Other cases of people noticing the docs are not inline with the code. 
http://stackoverflow.com/questions/24979499/fosrestbundle-show-my-custom-exception-message#comment42828411_25608481

Given this configuration stops the preview of the error pages working I thought Id raise this issue and to highlight the documentation mismatch. 

Error Page Preview: http://symfony.com/blog/new-in-symfony-2-6-error-page-previews

**Comment by lsmith77** [comment]
hmm .. IIRC this PR should have fixed this https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1024/files

**Comment by gsdevme** [comment]
Thanks, looks like its included in 1.6.0. Should this stay open for a note of the documentation? if not please close it.

**Comment by lsmith77** [comment]
dont think we need to note anything specific in the docs for this ..
