### ISSUE TITLE
Documentation of exception_wrapper_handler is missing

### ISSUE THREAD

**Issue by magnetik** [FriendsOfSymfony/FOSRestBundle#1098]
In the file `Resources/doc/4-exception-controller-support.rst`, the documentation states:

    See `this example configuration`_ for more details.

The link is: https://github.com/liip-forks/symfony-standard/blob/techtalk/app/config/config.yml

But it seems that the relevant config is not present there.

**Comment by lsmith77** [comment]
see here https://github.com/liip-forks/symfony-standard/blob/techtalk/app/config/config.yml#L38

**Comment by ReservedDeveloper** [comment]
From what I can see, this ticket is still valid. The above linked example does not mention `exception_wrapper_handler` in any way. Not sure if something has changed in that branch or not, but as  it stands usage is a little unclear, though the [Upgrade Doc](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING.md) does allude to it being service-based now.

**Comment by Ener-Getick** [comment]
Removed in #1358
