### ISSUE TITLE
[Route Annotation] Route override [may be route match order] when using same method

### ISSUE THREAD

**Issue by ihsanudin** [FriendsOfSymfony/FOSRestBundle#1102]
I have route

```php
@Get("/a")
```
and then i define

```php
@Get("/{param}")
```
The second route is never match and can't accessed but registered.

Any suggestion?

**Comment by xabbuh** [comment]
Do you define both routes in the same file?

**Comment by ihsanudin** [comment]
@xabbuh : Yes... you are right

**Comment by lsmith77** [comment]
then you need to ensure that they are (ie. the methods) defined in the desired order
