### ISSUE TITLE
ensure Symfony 3.0 compatibility

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#1106]

**Comment by casparcrop94** [comment]
I still can't do composer update with the FOSRestBundle, because the bundle requires an 2.* http-kernel

**Comment by stof** [comment]
@casparcrop94 you need to use the ``2.0.*@dev`` versions of the bundle, as the Symfony 3 support is not yet available in released versions of the bundle (and not in the 1.7 branch either).

@lsmith77 any plan to make 1.x compatible with Symfony 3 ?

**Comment by Ener-Getick** [comment]
What do you mean? all the constraints are updated in 2.0 https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json

**Comment by stof** [comment]
@Ener-Getick 2.0 is a dev version, not a released version, so this is not what people are using

**Comment by lsmith77** [comment]
@stof this is somewhat undecided at this point .. originally I wanted to have 2.0 release by now already. a few things came up but imho we can release very quickly if we decide to.

In the mean time this idea of a BC layer came up which would go into a 1.8 release and there we could in theory also enable 3.0 but with deprecation notices. I guess we can have a meeting on Saturday to discuss this and maybe pull in @Ener-Getick via video chat?

**Comment by Ener-Getick** [comment]
Sure sorry I didn't see your message... To support symfony 3.0, we would have to create bc layers. We should discuss about this, it depends too if the 2.0 will be released soon or not.

**Comment by Ener-Getick** [comment]
Why not @lsmith77, but I do not understand English as well orally as writing :/
