### ISSUE TITLE
Empty content-type for DELETE requests

### ISSUE THREAD

**Issue by ktounet** [FriendsOfSymfony/FOSRestBundle#1108]
Hi,

There is a the following function in the BodyListener :
```php
private function isNotAnEmptyDeleteRequestWithNoSetContentType($method, $content, $contentType)
{
    return false === ('DELETE' === $method && empty($content) && null === $contentType);
}
```

When sending a DELETE request with no content-type, It works with apache server but not with nginx. In the latter case, the content-type is equal to an empty string, not a null value.

Does the condition should be changed to ```empty($contentType)``` for compatibility with nginx ?

PS : I checked several times that the content-type header was not sent, and even tried clearing the header with nginx module "HttpHeadersMoreModule". So I don't think it's a bug from nginx, maybe caused by Symfony ?

Thanks.

**Comment by lsmith77** [comment]
yeah, I think this could be done .. please submit a PR for the 1.7 branch
