### ISSUE TITLE
Routing doc isn't relevant

### ISSUE THREAD

**Issue by faost** [FriendsOfSymfony/FOSRestBundle#1109]
In docs you can see example:

    public function postUserCommentVoteAction($slug, $id)
    {} // "post_user_comment_vote" [POST] /users/{slug}/comments/{id}/vote

But in fact you will get route in plural:

    [POST] /users/{slug}/comments/{id}/votes

**Comment by lsmith77** [comment]
yeah .. this is indeed a typo .. can you submit a PR to fix this in the docs .. it will indeed be "votes"

**Comment by lsmith77** [comment]
please target the 1.7 branch for the fix
