### ISSUE TITLE
Extend ViewHandler->getDataFromView(View $view)

### ISSUE THREAD

**Issue by andreas-glaser** [FriendsOfSymfony/FOSRestBundle#1111]
Hi Guys,

I'm trying to create a small extension of your ViewHandler. However, the function I'd like to extend is "private" and I cannot see why that would be?

private function getDataFromView(View $view){}

Is there a reason behind this and if so what is the best way of altering that method's behavior?

Thanks

**Comment by stof** [comment]
The reason we use private visibility is that it makes maintenance much easier: anything protected needs to be taken into account for backward compatibility.

what is your use case exactly for extending this method ?

**Comment by andreas-glaser** [comment]
I'd basically like to throw an exception if there is a form and it has not been submitted; instead of returning 200 + forms children.

Something like:
```php
    /**
     * Returns the data from a view. If the data is form with errors, it will return it wrapped in an ExceptionWrapper
     *
     * @param View $view
     *
     * @return mixed|null
     */
    private function getDataFromView(View $view)
    {
        $form = $this->getFormFromView($view);

        if (false === $form) {
            return $view->getData();
        }

        if ($form->isValid()) {
            return $form;
        } elseif (!$form->isSubmitted()) {
            /** @var ExceptionWrapperHandlerInterface $exceptionWrapperHandler */
            $exceptionWrapperHandler = $this->container->get('fos_rest.exception_handler');

            return $exceptionWrapperHandler->wrap(
                [
                    'status_code' => $this->failedValidationCode,
                    'message'     => 'No data received',
                    'errors'      => $form,
                ]
            );
        }

        /** @var ExceptionWrapperHandlerInterface $exceptionWrapperHandler */
        $exceptionWrapperHandler = $this->container->get('fos_rest.exception_handler');

        return $exceptionWrapperHandler->wrap(
            [
                'status_code' => $this->failedValidationCode,
                'message'     => 'Validation Failed',
                'errors'      => $form,
            ]
        );
    }
```

Btw. thanks for the great work, stof! :)

**Comment by lsmith77** [comment]
hmm not sure if we shouldn't just add a new method to "validate the form" .. or we can introduce an option for this. indeed the current behavior is mostly intended for controllers that deal with both HTML and JSON/XML requests, but it doesn't make so much sense for pure JSON/XML controllers.

another option which feels unclean but might be the most flexible and least risky to cause incompatibilities between controllers would be to add a flag (or closure) to the ``View`` class to determine the behavior

**Comment by Ener-Getick** [comment]
will be possible with #1358

**Comment by andreas-glaser** [comment]
thanks
