### ISSUE TITLE
How do I get a properly formed XML from a raw associative array?

### ISSUE THREAD

**Issue by naroga** [FriendsOfSymfony/FOSRestBundle#1120]
Suppose the following snippet:

    $view = $this->view(['name' => 'Pedro'], 200)
        ->setTemplate("AppBundle:Dashboard:index.html.twig")
        ->setTemplateVar('dashboard');

    return $this->handleView($view);

Using a JSON format, I get the correct output: `{"name":"Pedro"}`. However, for the XML format, I would expect something along the lines:

    <result>
        <name> 
            <![CDATA[ Pedro ]]>
        </name>
    </result>

However, the output does **not** contain a `name` node. It's renamed `entry` for some reason:

    <result>
        <entry> 
            <![CDATA[ Pedro ]]>
        </entry>
    </result>

Is there any way to make sure the XML is generated with the proper keys? I understand that if I use an object instead of an array, the output is generated correctly, but I don't want to map my output to an object. Are there any reasons for the key to be renamed 'entry'?

**Comment by lsmith77** [comment]
assuming you are using JMS serializer: http://jmsyst.com/libs/serializer/master/reference/annotations#xmlvalue

**Comment by lsmith77** [comment]
ah actually misunderstood the question .. generally JMS serializer requires you to work with objects to get proper serialization results.

**Comment by naroga** [comment]
Thank you, @lsmith77.

I've disabled JMS/Serializer and enabled the Symfony Serializer instead. It works as intended now.
