### ISSUE TITLE
composer update - dependency problem to willdurand/negotiation

### ISSUE THREAD

**Issue by filipjakubowski** [FriendsOfSymfony/FOSRestBundle#1124]
In my project I was using
"friendsofsymfony/rest-bundle": "dev-master"
that require: 
"willdurand/negotiation":         "~1.2"

but when I perform: composer update
I got: 
friendsofsymfony/rest-bundle dev-master requires willdurand/negotiation ^2.0.0-alpha1 -> no matching package found.

any help?

**Comment by xabbuh** [comment]
This is probably due to the fact that the `minimum-stability` option in your `composer.json` file is `stable`. Thus, non-stable dependencies that are required by your dependencies won't be pulled in automatically. You can add the `willdurand/negotation` package to your project's `composer.json` file or lower the `minimum-stability` setting for now.

**Comment by filipjakubowski** [comment]
Hi, 

Thnaks, 

I have tried every of those in my **composer.json**:
adding **negotiation** 
```"willdurand/negotiation":         "~1.2",```
removing **minimum-stability** and adding **prefer-stable**
```"minimum-stability": "stable",
"prefer-stable": true,```
and still got error on *composer update*:
```
 Problem 1
    - friendsofsymfony/rest-bundle dev-master requires willdurand/negotiation ^2.0.0-alpha1 -> no matching package found.
    - friendsofsymfony/rest-bundle dev-master requires willdurand/negotiation ^2.0.0-alpha1 -> no matching package found.
    - Installation request for friendsofsymfony/rest-bundle dev-master -> satisfiable by friendsofsymfony/rest-bundle[dev-master].
```

**Comment by stof** [comment]
Well, if you force depending on ``~1.2``, you indeed won't be able to install the dev version of FOSRestBundle which relies on the dev version of willdurand/negotiation 2.0. these would be conflicting requirements

**Comment by filipjakubowski** [comment]
Thanks @stof, 

my bad - I think I took look on wrong version dependency in rest bundle. 
It helped. :-) Still need to upgrade to newer version of Symfony ;-)
