### ISSUE TITLE
Bug with the RequestBodyParamConverter

### ISSUE THREAD

**Issue by Ener-Getick** [FriendsOfSymfony/FOSRestBundle#1127]
There is an error when I use the ``RequestBodyParamConverter``:
``Cannot create an instance of FOS\\RestBundle\\Request\\ParamFetcher from serialized data because its constructor requires parameter \"paramReader\" to be present.``.

```php
    public function postTradingsAction(ParamFetcher $paramFetcher)
    {
    }
```

I didn't define any ``ParamConverter`` anotations but the ``RequestBodyParamConverter`` tries to convert ``$paramFetcher`` ...

We should probably think about defining a priority of ``-1`` to this param converter in https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/config/request_body_param_converter.xml

**Comment by lsmith77** [comment]
yeah .. probably best to first create a functional test (we already have a few of those) to reproduce the issue ..
