### ISSUE TITLE
Impossible to override View Class as ViewHandlerInterface use View. There is no ViewInterface.  

### ISSUE THREAD

**Issue by vishalmelmatti** [FriendsOfSymfony/FOSRestBundle#1130]
Hi,

I need to override View class as it uses SerializationContext. I have my own custom SerializationContext. 

    public function getSerializationContext()
    {
        if (null === $this->serializationContext) {
            $this->serializationContext = new MySerializationContext();
        }

        return $this->serializationContext;
    }

To override it, I have created MyView class but as ViewHandlerInterface::handle uses View class as type of $view parameter, it is impossible to pass any other type of view class. 

Also serialization context is private property so its not possible to extend and override above method. All code needs to be copied just to override one method. 

Is there any possibility of creating ViewInterface and use that as type everywhere ?

**Comment by lsmith77** [comment]
did you check out the master branch? we have introduced an interface there to make it easier to support different serializers.

**Comment by vishalmelmatti** [comment]
Ah thats great. I am using 1.7.1. Thanks will close this issue.

**Comment by vishalmelmatti** [comment]
jsm serializer supports adding custom exclusion strategy, how to add it in same serializer context which fosresbundle creates ? I don't want to create separate serialization context to avoid doing in each controller.

**Comment by lsmith77** [comment]
you can set a context on the ``View`` instance in your action. but if you want to add this strategy in all cases, then indeed you should override the ``getSerializationContext()`` method in the ``ViewHandler`` and call the parent method and then add the relevant calls on the ``$context`` instance.

**Comment by vishalmelmatti** [comment]
Thanks I can override but just wanted to know Isn't it worth having a feature to allow adding custom strategies ? May be having some tagged services as strategies and fosrestbundle should add them in context ?

**Comment by lsmith77** [comment]
i think it might make more sense to add this to JMSSerializerBundle some how .. I do not want to add any more features to the Bundle that is just specific to one serializer.

**Comment by vishalmelmatti** [comment]
Yeah right. JMSSerializerBundle already allows to add custom strategies but we need to access serializer context. I wanted to add strategies in same context created by fosrest.  May be ability to configure serialization context in fos_rest configuration make sense? That way it will decouple fosrest from JmsSerializer SerializationContext.

**Comment by lsmith77** [comment]
my point is JMSSerializerBundle should have a config to automatically add exclusion strategies, since we use the serializer from that Bundle it should then also work for FOSRestBundle without any additional code.

right now it seems like JMSSerializerBundle just allows configuring custom visitors but not exclusion strategies.

**Comment by vishalmelmatti** [comment]
Thanks @lsmith77 for your help and time. Will post it on JMSSerializerBundle bundle.
