### ISSUE TITLE
Composer update throws error

### ISSUE THREAD

**Issue by taliah** [FriendsOfSymfony/FOSRestBundle#1131]
friendsofsymfony/rest-bundle dev-master requires willdurand/negotiation ^2.0.0-alpha1 -> no matching package found.

When I search for willdurand/negotiation there is only a 2.0-dev version available. Maybe it's better to require a version like ~2.0 to avoid same issues later?

**Comment by lsmith77** [comment]
the release should be there
https://packagist.org/packages/willdurand/negotiation#v2.0.0-alpha1
