### ISSUE TITLE
API Key in the rest route prefix and pre-authorization

### ISSUE THREAD

**Issue by MavenSean** [FriendsOfSymfony/FOSRestBundle#1132]
I need to be able to extract the api key from the route while pre-authorizing requests.

```
some_rest_route:
    resource: "@SomeBundle/Resources/config/routing.yml"
    prefix: /v1.0/{apiKey}
```

The route works fine, however in my pre-authorization if I do $request->query->get('apiKey') I'm getting back null -- obviously I understand the apiKey is not being passed as a query parameter.

Is there a way to fetch the apiKey from the route?  Without having to explode the entire request string -- that would be ideal.

The implementation is that I have a firewall rule setup to pre-authorize all API requests using the supplied apiKey.  It of course works fine if I add the ?apiKey=lakjdsflkj, but my preference is to build it into the route as I have defined.

Thanks!

**Comment by lsmith77** [comment]
this should just work like any placeholder in the route pattern: http://symfony.com/doc/current/book/routing.html#routing-in-action

ie. just add ``$apiKey`` to your controller action signature

**Comment by MavenSean** [comment]
That only works for a controller.  In this case as I mentioned I'm doing preauthorization.

The firewall intercepts the call before its passed to the controller, so I can't access route placeholders like you would in a normal controller.

/v1.0/{apiKey} in this case routes -> Firewall rule -> authenticationHandler -> userProvider -> restController

I need to retrieve the api key at the point of the authenticationHandler.  For the time being, I'm just exploding the URL to get the value, but that's a very dirty way of doing it.

**Comment by lsmith77** [comment]
I fear there isn't anything the FOSRestBundle can do here ..

**Comment by xabbuh** [comment]
@MavenSean FYI, route parameters are available through the request's attributes like this:

```php
$request->attributes->get('apiKey');

// or if you prefer to refer to the route params:
$request->attributes->get('_route_params')['apiKey'];
```

**Comment by MavenSean** [comment]
@xabbuh Thank you, that answers my question exactly.  It didn't even occur to me to check the attributes and it worked exactly as I needed.
