### ISSUE TITLE
[Question] Disable _format for one REST Controller only

### ISSUE THREAD

**Issue by Sydney-o9** [FriendsOfSymfony/FOSRestBundle#1146]
I'm aware that we can totally remove `_format` in FOSRestBundle:

````
fos_rest:
    routing_loader:
        include_format:       false
````
But is there a way to disable it only for a particular controller?

````
# This controller uses _format for our API
nam_plasmid_api:
    resource: Nam\PlasmidBundle\Controller\PlasmidController
    type:     rest
    prefix:   /api
````

````
# This one is for our Browser Based Application and we would like to remove _format ...
nam_plasmid:
    resource: Nam\PlasmidBundle\Controller\PlasmidController
    type:     rest
    name_prefix: nam_plasmid_
````
So, for now we have `_format` for both:
![screen shot 2015-10-05 at 10 14 15 pm](https://cloud.githubusercontent.com/assets/1480617/10279093/73bff0a8-6bae-11e5-8bf3-b1d1bd1a6679.png)

Note: As you can see, we are using the same REST Controller but simply use different routes for our API and our Web Browser Based Application

**Comment by lsmith77** [comment]
no .. you will need to manually define the routes in this case.

for 2.0 this might become possible if someone works on an implementation of this concept here https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1139#issuecomment-145364181

**Comment by Sydney-o9** [comment]
Awesome - good to know @lsmith77. Thank you!
