### ISSUE TITLE
merge fileParam in version 1.7 

### ISSUE THREAD

**Issue by pinouf** [FriendsOfSymfony/FOSRestBundle#1148]
hello ,
I need the FileParams annotation in the bundle =). 
Could you please merge in the version 1.7 ?

thank you =)

**Comment by Ener-Getick** [comment]
This feature makes bc breaks, you can still use the dev version of the bundle if you want 😉

**Comment by pinouf** [comment]
@Ener-Getick hi -)
what should use in composer.json to take the dev version master ?
Indeed, i use          "friendsofsymfony/rest-bundle": "dev-master" and composer only take me the version 1.7-dev ... 

    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",

        "twig/extensions": "v1.3.0",

        "jms/security-extra-bundle": "1.5.*",
        "jms/di-extra-bundle": "1.5.*",
        "jms/serializer-bundle": "1.0.*",
        "friendsofsymfony/rest-bundle": "dev-master",
        "doctrine/doctrine-fixtures-bundle": "v2.2.1",
        "stof/doctrine-extensions-bundle":"v1.2.1",
        "knplabs/knp-paginator-bundle": "~2.4.",
        "seld/jsonlint": "1.3.*",
        "friendsofsymfony/user-bundle": "v1.3.6",
        "guzzle/guzzle": "v3.9.3",
        "friendsofsymfony/jsrouting-bundle": "1.5.4",
        "knplabs/knp-menu-bundle": "v2.0.0",

        "fpn/doctrine-extensions-taggable": "dev-master",

        "knplabs/knp-gaufrette-bundle": "v0.1.7",
        "fpn/tag-bundle": "dev-master",
        "willdurand/expose-translation-bundle": "1.0.0",
        "friendsofsymfony/oauth-server-bundle": "1.4.2",
        "nelmio/api-doc-bundle": "2.9.*",
        "oldsound/rabbitmq-bundle": "v1.7.0",
        "sensio/generator-bundle": "v2.5.3",
        "liuggio/excelbundle": "^2.0",
        "nelmio/cors-bundle": "^1.4"
    },

**Comment by Ener-Getick** [comment]
Hum that's strange ``dev-master`` works for me. There may have conflicts, I'll check.

**Comment by Ener-Getick** [comment]
Your configuration has conflicts between the ``fpn/*`` packages.

I changed several package version: 
```json
{
	"require": {
		"php": ">=5.3.9",
		"symfony/symfony": "2.7.*",
		"doctrine/orm": "~2.2,>=2.2.3,<2.5",
		"doctrine/dbal": "<2.5",
		"doctrine/doctrine-bundle": "~1.4",
		"symfony/assetic-bundle": "~2.3",
		"symfony/swiftmailer-bundle": "~2.3",
		"symfony/monolog-bundle": "~2.4",
		"sensio/distribution-bundle": "~4.0",
		"sensio/framework-extra-bundle": "~3.0,>=3.0.2",
		"incenteev/composer-parameter-handler": "~2.0",

		"twig/extensions": "v1.3.0",

		"jms/security-extra-bundle": "1.5.*",
		"jms/di-extra-bundle": "1.5.*",
		"jms/serializer-bundle": "1.0.*",
		"friendsofsymfony/rest-bundle": "dev-master",
		"doctrine/doctrine-fixtures-bundle": "v2.2.1",
		"stof/doctrine-extensions-bundle": "v1.2.1",
		"knplabs/knp-paginator-bundle": "~2.4.",
		"seld/jsonlint": "1.3.*",
		"friendsofsymfony/user-bundle": "v1.3.6",
		"guzzle/guzzle": "v3.9.3",
		"friendsofsymfony/jsrouting-bundle": "1.5.4",
		"knplabs/knp-menu-bundle": "v2.0.0",

		"fpn/doctrine-extensions-taggable": "^0.9",
		"fpn/tag-bundle": "dev-master",

		"knplabs/knp-gaufrette-bundle": "v0.1.7",
		"willdurand/js-translation-bundle": "^1.0",
		"friendsofsymfony/oauth-server-bundle": "1.4.2",
		"nelmio/api-doc-bundle": "2.9.*",
		"oldsound/rabbitmq-bundle": "v1.7.0",
		"sensio/generator-bundle": "v2.5.3",
		"liuggio/excelbundle": "^2.0",
		"nelmio/cors-bundle": "^1.4"
	}
}
```

It should work now ;)

Ps: You should use the ``^major.minor`` syntax when you select a specific version of a package, you doesn't have the new features/bugs fixes.

**Comment by pinouf** [comment]
thank you @Ener-Getick !! it seem the that work but i have another problem.
I will like to test with your exemple in another ticket.
    /**
     * 
     * @POST("/v2/contents/upload")
     * @View(statusCode=200)
     * @ApiDoc(
     *   section= "contents",
     *   description="Upload content"
     * )
     * @FileParam(name="fooFile")
     * In this example, if firstName and fooFile are defined at the time,
     * ParamFetcher::get("fooFile") will throw an error.
     * Otherwise, if the file is valid, it will return a Symfony\Component\HttpFoundation\File\UploadedFile.
     * See http://api.symfony.com/2.7/Symfony/Component/HttpFoundation/File/UploadedFile.html
     *
     * @FileParam(name="myJsonFile", requirements={"mimeTypes"="application/json", "maxSize"="2k"}, strict=true)
     * The ParamFetch will throw an error if the file passed is not a json file or is bigger than 2,000 bytes.
     * See all file possible requirements: http://symfony.com/doc/current/reference/constraints/File.html
     *
     * @FileParam(name="avatar", requirements={"mimeTypes"="application/json", "minWidth"="200"}, image=true)
     * The ParamFetch will throw an error if the file passed is not an image and is not larger than 2O0px.
     * See all image possible requirements: http://symfony.com/doc/current/reference/constraints/Image.html
     *
     * @FileParam(name="identityCard", image=true, default="noPicture")
     * If "identityCard" is not an image, paramFetcher will return "noPicture"
     * @param  integer $id
     * @return array
     */
    public function uplaodContentAction(ParamFetcher $paramFetcher)
    {

    }
i got error
UndefinedMethodException in FormatNegotiator.php line 94:
Attempted to call an undefined method named "normalizePriorities" of class "FOS\RestBundle\Negotiation\FormatNegotiator".

Should i use another bundle?

**Comment by Ener-Getick** [comment]
This bug is fixed by #1149, this is the problem of the dev version ...
You can fix the code directly in your vendors waiting this PR is merged.
It's this line: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1149/files#diff-fb25b174c69c239c848f3c46379a7c2cR89.

**Comment by pinouf** [comment]
@Ener-Getick lol it seem that it is very hard to manage that -) 

I got another error : 


 InvalidMediaType in Accept.php line 20:

in Accept.php line 20
at Accept->__construct('html') in Negotiator.php line 12
at Negotiator->acceptFactory('html')
at array_map(array(object(FormatNegotiator), 'acceptFactory'), array('html', '*/*')) in AbstractNegotiator.php line 28
at AbstractNegotiator->getBest('text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', array('html', '*/*')) in FormatNegotiator.php line 78
at FormatNegotiator->getBest('', array()) in ExceptionController.php line 199
at ExceptionController->getFormat(object(Request), 'html') in ExceptionController.php line 60
at ExceptionController->showAction(object(Request), object(FlattenException), object(Logger))
at call_user_func_array(array(object(ExceptionController), 'showAction'), array(object(Request), object(FlattenException), object(Logger))) in bootstrap.php.cache line 3109
at HttpKernel->handleRaw(object(Request), '2') in bootstrap.php.cache line 3071
at HttpKernel->handle(object(Request), '2', false) in bootstrap.php.cache line 3222
at ContainerAwareHttpKernel->handle(object(Request), '2', false) in ExceptionListener.php line 50
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
at call_user_func(array(object(ExceptionListener), 'onKernelException'), object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher)) in WrappedListener.php line 61
at WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher))
at call_user_func(object(WrappedListener), object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher)) in classes.php line 1828
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent)) in classes.php line 1757
at EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in TraceableEventDispatcher.php line 124
at TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in bootstrap.php.cache line 3141
at HttpKernel->handleException(object(InvalidMediaType), object(Request), '1') in bootstrap.php.cache line 3077
at HttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 3222
at ContainerAwareHttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 2444
at Kernel->handle(object(Request)) in app_dev.php line 37

=/

**Comment by Ener-Getick** [comment]
Hum this is another bug we try to solve :P
Use in your config text/html instead of html ;) 
If you have another error like that, try to replace the formats (``json``, ``html``, ...) to their mime-type form (``application/json``, ``text/html``, ...).

**Comment by pinouf** [comment]
same error -).
I think i am giving up lol ...
    format_listener:
        rules:
            - { path: '^/api', priorities: ['application/json'], fallback_format: json, prefer_extension: true }
            - { path: '^/data', priorities: ['application/json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: ~, prefer_extension: true }

Maybe you have another solution for me?
i have to develop a rest api who allow to a client javascript to uplaod a file ...

**Comment by lsmith77** [comment]
``'/'`` doesn't work .. try ``*/*`` instead

**Comment by pinouf** [comment]
I tested with

- { path: '^/api', priorities: ['application/json'], fallback_format: json, prefer_extension: true }
- { path: '^/data', priorities: ['application/json'], fallback_format: json, prefer_extension: true }
- { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: ~, prefer_extension: true }

and got errors -)

i gave up the dev-master version and return to the 1.7 stable version.
I found another solution, and will use the fileParam annotation when it will be stable.

t

**Comment by xabbuh** [comment]
@pinouf Would you mind creating issues with the error messages you got so that it will be easier to fix possible existing bugs and to help stabilising the bundle for 2.0?

**Comment by pinouf** [comment]
@xabbuh 
ok , I'll do it tonight or tomorrow when I have some time . =)

**Comment by xabbuh** [comment]
@pinouf great :)

**Comment by lsmith77** [comment]
ping
