### ISSUE TITLE
re-add support for formats as priorities

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#1151]
right now we just support mime types.

relates to https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1149

**Comment by Ener-Getick** [comment]
I tried to use the current ``Request::getMimeType()`` function. It supports the main mime types but not the aliases...

**Comment by lsmith77** [comment]
exactly .. @Tobion what do you think are the chances to add a method to read ``Request::format`` from the outside?

**Comment by lsmith77** [comment]
@Ener-Getick right now the only option I see is forcing the user to configure the entire mapping again

**Comment by Ener-Getick** [comment]
Another solution is to copy the ``Request::format`` at least temporarily. We can also search if there is no component that contains this mime types map.

**Comment by lsmith77** [comment]
the Negotiation lib used to provide such a mapping in version 1.x ..

**Comment by Ener-Getick** [comment]
If this is too complicated we can always revert to willdurand/negotiation 1.x...
