### ISSUE TITLE
scrutinizer code coverage statistics

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#1163]
```
Hi Lukas, 

I believe you are sending us code coverage information from multiple builds, however in your configuration, you only have set the ``runs`` to 1. So, my guess is that depending on which of your builds finishes first, we get different data and hence you see these changes in coverage depending on which of your builds sends in the data first.

An easy way to fix that would be to just send us code coverage from the same build or increase the number of runs to the total number of builds (the latter being a bit more maintenance intensive if you change the number of builds).

Let me know if that solves it.

Best

--
Thomas Müller from Scrutinizer
On Wed, Oct 7, 2015 at 08:35 PM, "Lukas Kahwe Smith" <smith@pooteeweet.org> wrote: 
the test coverage keeps jumping up and down by 17% on https://scrutinizer-ci.com/g/FriendsOfSymfony/FOSRestBundle/ ..

is there something I can do to prevent this?
```

@stof IIRC you initially set this up .. what do you think .. only send data for one build or increase the builds?

**Comment by Ener-Getick** [comment]
What about using the scrutinizer code coverage integrated feature?

**Comment by stof** [comment]
@lsmith77 I went for the simple configuration at first. I never went to uploading coverage on a single Travis job in my projects for now. It might be worth changing this though to run the coverage only once and upload it always from this job

> What about using the scrutinizer code coverage integrated feature?

This would require running tests on scrutinizer itself, which is not worth it IMO. No need to maintain 2 testing environments (and we need travis to be able to test multiple versions of PHP)
