### ISSUE TITLE
rest controllers could not be put outside a bundle controller directory.

### ISSUE THREAD

**Issue by makasim** [FriendsOfSymfony/FOSRestBundle#1164]
let's say I have src/Backoffice/Api directory which is where I want to keep all my rest controllers. Right now I cannot do it because of the exception.

```
Exception "The "Backoffice\Api\CartController" class does not look like a controller class (it must be in a "Controller" sub-namespace and the class name must end with "Controller")""
```

Which is thrown from `Sensio\Bundle\FrameworkExtraBundle\Templating\TemplateGuesser` line 57.

This happens if I use `@Rest\View()` annotation (without template attribute set). Configuring it like this `@Rest\View(template="FrameworkExtraBundleTriesToGuessTemplateAndFailsThisIsWorkaround")`

solves the problem.

Pay attention to I am using only json in the api, and guessing template on every request, even if it is not needed looks strange to me.

**Comment by lsmith77** [comment]
sounds more like an issue that should be fixed in the SensioFrameworkExtraBundle?

**Comment by makasim** [comment]
@lsmith77 I dont think so, The _template is forced in fos rest bundle code https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener/ViewResponseListener.php#L52

The SensioFrameworkExtraBundle sees this attribute and tries to do its job.

**Comment by lsmith77** [comment]
I am not on my laptop atm .. so I cannot investigate what we could do in the case that we are not using a template. I guess we could check if the output format requires a template and only then set the request attribute?

**Comment by Ener-Getick** [comment]
@makasim You can use [this](https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/398) to guess templates in an uncommon directory but this can't be fixed in FOSRestBundle as we do not manage the template name guess...
