### ISSUE TITLE
Format listener configuration

### ISSUE THREAD

**Issue by murilolobato** [FriendsOfSymfony/FOSRestBundle#1172]
If I configure the format_listener parameter simply as true, what happen?

In my tests I couldn't see any differences, in all tests it does nothing, this makes me feel frustrated. So I was thinking, that if it actually don't do anything it could be remove from getting started docs.

Here: http://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html 

For someone new, it passes the idea that is just set this parameter to true, and I will not even need to send the extension anymore because it will start to be guessed by the listener according to the 'Accept' header on request.

At least for me this was not true, or maybe I'm using something wrong. I had to set my config like this to achieve what I was looking for:

    # app/config/config.yml

    fos_rest:
        body_listener: true
        routing_loader:
            default_format: html
        view:
            view_response_listener: force
        format_listener:
            rules:
                - priorities: [html, json]
                - fallback_format: html

    sensio_framework_extra:
        view:    { annotations: false }

So now, I can use my app as a regular web app, but when I make a request with Accept: application/json or with .json at the end, I have a nice API.

@stof

**Comment by lsmith77** [comment]
i think this part of the docs might be out dated. afaik right now we do indeed require configuration of a rule in order for the format listener to do anything useful.

**Comment by xabbuh** [comment]
Then we should also trigger some warning/error when there is no rule configured.

**Comment by Ener-Getick** [comment]
fixed by https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1265
