### ISSUE TITLE
Every parent controller must have `get{SINGULAR}Action($id)` method when i have multi level sub resource in FOS Rest Bundle

### ISSUE THREAD

**Issue by ghanbari** [FriendsOfSymfony/FOSRestBundle#1173]
I get following error, when i use three sub resource level in fos rest bundle,

```
[InvalidArgumentException]                                           
  Every parent controller must have `get{SINGULAR}Action($id)` method  
  where {SINGULAR} is a singular form of associated object 
```

[please see my post in stack] (http://stackoverflow.com/questions/33087657/every-parent-controller-must-have-getsingularactionid-method-when-i-have/33087821#33087821)

**Comment by lsmith77** [comment]
could you either create a failing test or illustrate the issue by forking https://github.com/gimler/symfony-rest-edition ?

**Comment by ghanbari** [comment]
I ask my question in [stackoverflow](http://stackoverflow.com/questions/33087657/every-parent-controller-must-have-getsingularactionid-method-when-i-have) and `@dlporter98` answer to my question, thank you
