### ISSUE TITLE
return a json a good json format

### ISSUE THREAD

**Issue by pinouf** [FriendsOfSymfony/FOSRestBundle#1174]
hello,

i have a simple api who take a array and return a json.

by exemple :

```php
    /**
     * 
     * @Put("/v2/contents/delete")
     * @View(statusCode=200)
     * )
     *
     * @param  integer $id
     * @return array
     */
    public function putContentDeleteAction()
    {

        $contentRequest = array();
        $contentRequest[0]['test'] = 'toto';
        $contentRequest[0]['result'] = 'ok';    
        $contentRequest[1]['test'] = 'titi';
        $contentRequest[1]['result'] = 'nok';       
     
         return json_encode($contentRequest);
    }
```

the return is

```json
"[{\"test\":\"toto\",\"result\":\"ok\"},{\"test\":\"titi\",\"result\":\"nok\"}]"
```

i will like to have in the return ..

```json
[
  {
    "test": "toto",
    "result": "ok"
  },
  {
    "test": "titi",
    "result": "nok"
  }
]
```

**Comment by pinouf** [comment]
here my config =)

fos_rest:
    serializer:
        serialize_null: false
    view:
        view_response_listener: 'force'
        formats:
            json: true
            xml: true
            yml: true
            rss: false
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
            xml: 'application/xml'
            yml: 'text/yaml'
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\HttpKernel\Exception\HttpException': true

    format_listener:
        rules:
            - { path: '^/api', priorities: ['application/json'], fallback_format: json, prefer_extension: true }
            - { path: '^/data', priorities: ['application/json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: ~, prefer_extension: true }

    routing_loader:
        default_format: json

    param_fetcher_listener: true

Thanks !

**Comment by Ener-Getick** [comment]
You should not use ``json_encode``, ``FOSRestBundle`` manages this.

**Comment by stof** [comment]
@pinouf the issue is that you give a string to FOSRestBundle and ask it to return it as JSON. If you want to make the json encoding yourselves, return a Response object. And if you want to use the view system of FOSRestBundle, return the data themselves (your ``contentRequest`` variable)

**Comment by pinouf** [comment]
@stof  @Ener-Getick 
That's work . thanks !
