### ISSUE TITLE
disable_csrf_role not functioning with 2.8 ?

### ISSUE THREAD

**Issue by peshi** [FriendsOfSymfony/FOSRestBundle#1175]
disable_csrf_role: ROLE_API not functioning with symfony 2.8 ?

adding 'csrf_protection' => false in form type works.

**Comment by lsmith77** [comment]
AFAIK there were some changes there indeed, can you investigate if this can be fixed in the 1.7 branch? otherwise it might have to wait until the 2.0 stable release

**Comment by peshi** [comment]
It looks like something was added in the 1.7 branch, but there's no tagged version.
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7/Form/Extension/DisableCSRFExtension.php#L81

However it is not in the master branch. I suppose 'Symfony\Component\Form\Extension\Core\Type\FormType' should be added to master - if master is a version without BC layers.

**Comment by lsmith77** [comment]
FYI I just released https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/1.7.2

As for master, it requires 2.7+ and therefore should not require BC hacks

**Comment by peshi** [comment]
Thanks, 1.7.2 BC layer works for 2.8 - so back to master branch.

Since getExtendedType 'form' was replaced in 2.8 I suppose master would be for 2.8 + else we would have to add the backward compatibility in master as well.

Check for getExtendedType.
https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md

Shall I create a small PR for the master branch and replace 'form' ?

**Comment by lsmith77** [comment]
master is 2.7+  so I guess we can just apply the same change there with out any BC hack

**Comment by lsmith77** [comment]
so yes a PR would be good :)

**Comment by peshi** [comment]
Great :) i'll close this issue, thank you for quick feedback and support.

**Comment by peshi** [comment]
Sorry for the inconvenience - it has to be compatible with 2.7 also ? if yes i'll have to apply the patch from 2.3-2.8

**Comment by peshi** [comment]
I reckon 2.7 has to be included due to its long support time to May 2019. So I'll apply the patch for 2.3-2.8  otherwise just let me know in PR.

**Comment by lsmith77** [comment]
like I said .. master needs to work with 2.7+ .. ie. 2.7, 2.8, 3.0 ..
