### ISSUE TITLE
QueryParam requirements and default from container parameters

### ISSUE THREAD

**Issue by ufik** [FriendsOfSymfony/FOSRestBundle#1176]
As documentation states, it should be possible to use container parameters (from config/parameters.yml).

```php
/**
     * Use the "locale" parameter as the default value
     * @QueryParam(name="language", default="%locale%")
     *
     * The "baz" container parameter is used here as requirements
     * Can be used for complex or auto-generated regex
     * @QueryParam(name="foo", requirements="%baz%")
     *
     * The percent sign must be escaped
     * @QueryParam(name="val", default="75 %%")
     */
    public function getArticlesAction(ParamFetcher $paramFetcher)
    {
        ...
    }
```

config/parameters.yml

```yml
parameters:
    locale: en
```

But it doesn't work, instead of parameter from container there is the value with percent sign (%locale% for instance).
```php
echo $paramFetcher->get('language');
```
Will print %locale%

**Comment by Ener-Getick** [comment]
This feature will only be available in the 2.0. Which version of ``FOSRestBundle`` do you use ?

(Doc of the 1.7: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7/Resources/doc/param_fetcher_listener.rst)

**Comment by ufik** [comment]
I am sorry my bad, I was reading newer version.

**Comment by ufik** [comment]
I found it here http://symfony.com/doc/current/bundles/FOSRestBundle/param_fetcher_listener.html, but it's showing version 1.7 with this feature, so maybe at least fix this doc, so it won't confuse others in the future.

**Comment by pinouf** [comment]
hello,

Have you use this?

fos_rest:
    param_fetcher_listener: true

**Comment by ufik** [comment]
Hello, nope I haven't, but that is imho something completely different, because this feature will just pass query params as parameters into controller action, which is not exactly the thing I was mentioning :)

Anyway, we already figured this out, because it's just wrong version of documentation on the link above. This feature will be introduced in version 2.0, which is not stable yet.

Not sure if I have to close this issue right away and maybe create another one for wrong documentation on Symfony web (perhaps it's not connected) or ?

**Comment by lsmith77** [comment]
@javiereguiluz I guess it would be good to use the 1.7 branch on the symfony.com website for now
