### ISSUE TITLE
FOSRestBundle returns error 500 for NotFoundHttpException

### ISSUE THREAD

**Issue by mnapoli** [FriendsOfSymfony/FOSRestBundle#1177]
The [ExceptionController](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/ExceptionController.php#L90-L94) is catching any exception and returning an error 500. That means that when the router cannot find a route (e.g. we ask for a weird URL), instead of getting a 404 (`Symfony\Component\HttpKernel\Exception\NotFoundHttpException`) we get a 500 (no route found for '…').

Is that a problem with FOSRestBundle or am I doing something wrong?

Here is my config:

```yaml
fos_rest:
    routing_loader:
        default_format: json
    routing_loader:
        include_format: false
    exception:
        codes:
            '…\Exception\NotFound': 404
        messages:
            '…\Exception\NotFound': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
```

**Comment by lsmith77** [comment]
The Bundle uses the exception code mapping and otherwise just returns the status code as its defined in the Exception. see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/ExceptionController.php#L178

That being said the Exception you note above should default to 404:
https://github.com/symfony/http-kernel/blob/master/Exception/NotFoundHttpException.php#L30

**Comment by mnapoli** [comment]
That sounds absolutely reasonable to me but that's not what I see happening unfortunately. In the [ExceptionController](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/ExceptionController.php#L90-L94) the status code is `Response::HTTP_INTERNAL_SERVER_ERROR`.

OK if I remove the `exception:` key, then I indeed get a 404. But if I add it, I get a 500.

In other words, if I have that in my config then I get a 500:

```yaml
    exception:
        codes:
            '…\Exception\NotFound': 404
        messages:
            '…\Exception\NotFound': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
```

**Comment by lsmith77** [comment]
do you literally have "..." in there?

**Comment by lsmith77** [comment]
can you debug if the above mentioned method is called and if it returns the status code you would expect? ie. if we later on for some reason end up with a different error code (for example because an exception is thrown inside the ExceptionController which would explain why it ends up as a 500)

**Comment by mnapoli** [comment]
> do you literally have "..." in there?

Nope :)

Will debug more, I first wanted to make sure there was no obvious mistake in my config.

**Comment by mnapoli** [comment]
OK indeed I was confused by the 500 error message (*No route found for "GET /promotions"*) which was actually hiding an exception in the code:

> InvalidArgumentException The template "TwigBundle:Exception:exception_full.html.twig" does not exist.

I'm using the PHP templating engine (not Twig). Is there some config to make that work without Twig?

Here is what I tried:

```yml
fos_rest:
    ...
    view:
        default_engine: php
```

I still get the same error.

If I install Twig and the Bundle and enable it, I get this when running in prod environment (but with a correct 404 header):

![capture d ecran 2015-10-19 a 10 13 46](https://cloud.githubusercontent.com/assets/720328/10572666/b87afab6-764a-11e5-9a0d-08d2ab2354f8.png)

Anyway I don't want to install Twig.

**Comment by lsmith77** [comment]
the default ExceptionController stuff is all inside TwigBundle .. I fear the relevant templates are missing for php. I guess what might work is putting the relevant templates into ``app/Resources/TwigBundle`` .. not sure if that will do the trick though.

**Comment by mnapoli** [comment]
OK I understand thanks. Should I close this issue?

**Comment by lsmith77** [comment]
can you look if the docs need tweaking to clarify this?
maybe the docs should also add a note that if you receive a 500 then it could be that its because an exception was thrown in the controller
