### ISSUE TITLE
parent/child resource error: Every parent controller must have `get{SINGULAR}Action($id)` method

### ISSUE THREAD

**Issue by pstephenson02** [FriendsOfSymfony/FOSRestBundle#1185]
In [this gist](https://gist.github.com/pstephenson02/d254712a8968d37fb4d8), I have 3 controllers defined. I want to establish a parent/child relationship between the cah_annotation and the standard_proposal resource. I cannot find the reason for this error:

``` bash
$ ./app/console debug:router


  [Symfony\Component\Config\Exception\FileLoaderLoadException]                                                    
  Every parent controller must have `get{SINGULAR}Action($id)` method                                             
  where {SINGULAR} is a singular form of associated object in /var/www/html/cdpaccess/src/ICC/ProposalBundle/Res  
  ources/config/routing.yml (which is being imported from "/var/www/html/cdpaccess/app/config/routing.yml").      


  [InvalidArgumentException]                                           
  Every parent controller must have `get{SINGULAR}Action($id)` method  
  where {SINGULAR} is a singular form of associated object             
```

The weird thing is, if I modify routing.yml and set the parent resource on cah_annotation to proposal:

``` yml
cah_annotation:
    parent: proposal
```

It works fine. Even if I delete the proposal resource entry all together I get the same error.

What am I doing wrong here? These controllers are _very_ similar, how is it that it works with the proposal resource but not standard_proposal?

``` bash
$ php composer.phar show -i | grep rest
friendsofsymfony/rest-bundle               1.7.2                 This Bundle provides various tools to rapidly...
```

**Comment by xabbuh** [comment]
Can you check #1173?

**Comment by pstephenson02** [comment]
I did first check https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1173 and its associated [stackoverflow](http://stackoverflow.com/questions/33087657/every-parent-controller-must-have-getsingularactionid-method-when-i-have) question.

I made sure that was not the issue here. The method parameters are defined correctly (or rather: are not incorrect in the way they were shown in the stack question)

**Comment by xabbuh** [comment]
@pstephenson02 Instead of `getStandardProposalAction()` try `getAction()` instead.

**Comment by xabbuh** [comment]
Though I think the error message should indeed be improved.

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954
