### ISSUE TITLE
Can't use FileParam on PUT method

### ISSUE THREAD

**Issue by pilotepro** [FriendsOfSymfony/FOSRestBundle#1186]
Hello,
When I use FileParam on a POST method to upload a file with FileParam there is no problem, but when I use it on a PUT method, ParamFetcher doesn't return an UploadedFile object.

Here is my code :
```
/**
  * @Rest\FileParam(name="image", default="none", nullable=true)
*/
public function putPostAction(ParamFetcher $params, $id)
{
      $image = $params->get('image'); // $image equals 'none'
}
```
Thank you.

**Comment by Ener-Getick** [comment]
It seems that PHP doesn't support the file uploads on ``PUT`` requests https://stackoverflow.com/questions/12005790/how-to-receive-a-file-via-http-put-with-php.

**Comment by pilotepro** [comment]
Hello,
So to respect REST conventions (I can't update an item on a POST method) what do recommend.

**Comment by Ener-Getick** [comment]
I don't know if there is really a clean solution... 
You can use ``php://input`` (corresponds to ``Request::getContent()`` if I'm not wrong) but it won't work as $_FILES (only one file per request is supported...). 
http://php.net/manual/en/features.file-upload.put-method.php

You should search if other people have the same problem and what solution they use.

**Comment by pilotepro** [comment]
That's not a problem for me I just need to upload one file at once, but thank you for your help.
