### ISSUE TITLE
Manual routes do not respect security access_control

### ISSUE THREAD

**Issue by mamartins** [FriendsOfSymfony/FOSRestBundle#1187]
If I manually set a route like this:
```
    /**
     * @Post("/admin/token")
     */
```

and having this on my security.yml:
```
    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
```

I would expect that the route would only be accessible to ROLE_ADMIN but don't. I had to add 
``` @Security("has_role('ROLE_ADMIN')") ```

for it to actually limit access to that action

**Comment by lsmith77** [comment]
this cannot be caused by FOSRestBundle .. all the bundle does is configure routes and the access control's are checked way before the routing system is triggered by symfony.

**Comment by lsmith77** [comment]
please review http://symfony.com/doc/current/cookbook/security/access_control.html

FOSRestBundle has no impact on how the access_control system works.

**Comment by mamartins** [comment]
apparently it is correctly configured, on it.

**Comment by xabbuh** [comment]
@mamartins Would you mind sharing your complete `security.yml` file?
