### ISSUE TITLE
XML routing configuration does not work

### ISSUE THREAD

**Issue by iooK** [FriendsOfSymfony/FOSRestBundle#1195]
When we use xml routing configuration, the xml is not valid. XmlLoader does not use [FOSRest schema routing](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/config/schema/routing/rest_routing-1.0.xsd) defintion, but the symfony [standard schema routing](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd) definition.
```php
// XmlFileLoader.php
const SCHEME_PATH = '/schema/routing/routing-1.0.xsd';
```
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/XmlFileLoader.php#L184  
  
This declaration
```xml
<routes xmlns="http://friendsofsymfony.github.com/schema/rest"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://friendsofsymfony.github.com/schema/rest https://raw.github.com/FriendsOfSymfony/FOSRestBundle/master/Resources/config/schema/routing/rest_routing-1.0.xsd">
```
is useless (except in IDE).

Presently, if we use standard routing schema declaration with missing attributes in definition ("id" and "parent"). Schema will be valided by XmlLoader and the bundle load the configuration like a charm. 
Moreover, it's a dirty "patch" of a core symfony's component.

By the way, FOSRest documentation shows an xml example, it could be nice to remove it temporarily to prevent developers using this one.  http://symfony.com/doc/1.7/bundles/FOSRestBundle/6-automatic-route-generation_multiple-restful-controllers.html#resource-collection

Regards.

**Comment by lsmith77** [comment]
yeah .. I guess nobody is taking care of the XSD :(
see also https://github.com/FriendsOfSymfony/FOSRestBundle/issues/343

would be great if you could do a PR for the 1.7 and 2.0 branch for this.

**Comment by iooK** [comment]
Sorry, my bad.

I forgot to read something in documentation, everything is fine.
Without it, symfony default XmlLoader load the configuration instead of the Fos XmlLoader.

```
It is also necessary to add type: rest to the routing.yml file:
# app/config/routing.yml
acme_hello:
    type: rest
    resource: "@AcmeHelloBundle/Resources/config/users_routes.yml"
```

It would nice to put this part of documentation at the top of the page.

Sorry for inconvenience.
