### ISSUE TITLE
Make tests fail on deprecation notices ?

### ISSUE THREAD

**Issue by Ener-Getick** [FriendsOfSymfony/FOSRestBundle#1197]
Actually, the deprecations notices don't make the Travis build fail.
(https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/.travis.yml#L5)

To avoid as much as possible to have deprecations in the bundle, IMO we should remove this env parameter.

/cc @lsmith77 @stof

**Comment by stof** [comment]
this has been added temporarily because Symfony stable versions currently trigger deprecation warnings of Twig 1.23

**Comment by Ener-Getick** [comment]
Ok... Then we will have to remove this and to set this variable for the legacy build (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/.travis.yml#L28) (see https://github.com/KnpLabs/KnpMenuBundle/blob/master/.travis.yml#L19 for an example).
