### ISSUE TITLE
Make a better marriage between body and param converter

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSRestBundle#1198]
From the [docs](http://symfony.com/doc/current/bundles/FOSRestBundle/request_body_converter_listener.html):

> You will probably want to disable the automatic route generation (@NoRoute) for routes using the body converter, and instead define the routes manually to avoid having the deserialized, type hinted objects ($post in this example) appear in the route as a parameter.

And that's unfortunately true, I have to redefine entirely the route:

``` php
/**
 * @param Server     $server
 * @param ServerStat $stat
 *
 * @Route("/servers/{server}/stats")
 * @Security("is_granted('ROLE_ADMIN')")
 * @ParamConverter("stat", converter="fos_rest.request_body")
 *
 * @return View
 */
public function postAction(Server $server, ServerStat $stat)
{
}
```

That works, but it is very painful IMHO.

There is any way to improve this management in order to avoid this?

If you can give me some clue, I could maybe work on it. :+1:

**Comment by Ener-Getick** [comment]
I guess we can detect the ``fos_rest.request_body`` converter and remove it from the route.

**Comment by lsmith77** [comment]
we have a static list of arguments to ignore:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L412

we could either make this lyst "dynamic" by also looking for ParamConverter annotations. another approach could be to simply ignore all type hinted parameters but I think this could also have unwanted side effects. I have personally never used ParamConverter's ..

**Comment by gijsstegehuis** [comment]
Whats the status on this?
