### ISSUE TITLE
[Body Converter] Docs to manage errors

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSRestBundle#1199]
Doc ref: http://symfony.com/doc/current/bundles/FOSRestBundle/request_body_converter_listener.html#validation

In this part, you explain how to activate body converter and validation, but there is not specification or recommendation of how to manage it.

I mean, with [form type](http://symfony.com/doc/current/bundles/FOSRestBundle/2-the-view-layer.html#forms-and-views) with example, you just have to return the form and a http error response with form data will be created.

Does this system have a similar workflow? What is the best practice to do?

Thanks.

**Comment by lsmith77** [comment]
FOSRestBundle is a toolbox that can be combined but doesn't have to be .. the body converter is about accepting request data .. output is beyond its scope .. this is where for example the view layer is relevant. feel free to send a PR for the docs to reference the view layer section ..

**Comment by Soullivaneuh** [comment]
@lsmith77 maybe can I have some advice about this view layer? :-)
