### ISSUE TITLE
Error when combining @QueryParam and @Secure annotation

### ISSUE THREAD

**Issue by cedricduffournet** [FriendsOfSymfony/FOSRestBundle#1209]
I encounter the same issue described few yours ago : #242 .

Applying same modification to Request/ParamFetcher.php seems to fix it : 

Import ClassUtils
```php
use Doctrine\Common\Util\ClassUtils;
```

And change : 

```php
$params = $this->paramReader->read(
            new \ReflectionClass($this->controller[0]),
            $this->controller[1]
        );
````

to 

```php
$params = $this->paramReader->read(
            new \ReflectionClass(ClassUtils::getClass($this->controller[0])),
            $this->controller[1]
        );
```

**Comment by Ener-Getick** [comment]
It seems that this class resolves the real class path of a proxy. 
Can you make a pr and add a comment with a link to this issue to prevent it to be removed again?
