### ISSUE TITLE
NelmioApiDoc can not generate documentation

### ISSUE THREAD

**Issue by cedricduffournet** [FriendsOfSymfony/FOSRestBundle#1218]
Since  AbstractScalarParameter::$array as been renamed to  ::$map, NelmioApiDoc can not generate documentation anymore.

Should I add an issue on NelmioApiDoc repository ?

**Comment by Ener-Getick** [comment]
I'll make a PR. But isn't NelmioApiDoc not compatible with FOSRestBundle 2.0?

**Comment by willdurand** [comment]
It is not supported at least.

**Comment by cedricduffournet** [comment]
Ok I didn't know, actually It was working on my project before the modification

**Comment by willdurand** [comment]
Well, it should work I guess except for some edge cases just like this one. I did not test to be honest, but I'd be interested in bringing FOSRestBundle 2.0 support into NelmioApiDocBundle.

**Comment by Ener-Getick** [comment]
The problem is that this parameter doesn't have the same meaning in 2.0.
It is renamed to ``map`` and means that the parameter value will be validated row per row...

I think that we should create a new ``type`` option that would be more powerful.

**Comment by Ener-Getick** [comment]
This is fixed in ``NelmioApiDocBundle`` 2.11.
