### ISSUE TITLE
ParamFetcherListener problem with callables

### ISSUE THREAD

**Issue by xocasdashdash** [FriendsOfSymfony/FOSRestBundle#1221]
Hi!
We've found this error during development but we're not 100% sure if it's a bug or a feature

In symfony during a kernel.controller event you can change the controller resolved for the request, and because symfony accepts it you can set it to a callable like this:
```php
  $event->setController(function() use ($redirectUrl) {
        return new RedirectResponse($redirectUrl);
    });
```
But we, painfully, found out that this approach breaks if you mix this up with FOSRestBundle 1.4.2, specifically it breaks on the following file:

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/82b8388975e272fb6d1748262d02c553a9b0ca4d/EventListener/ParamFetcherListener.php#L90

because it expects to receive an array as an argument when it gets a callable

I couldn't manage to find any kind of documentation about this behaviour on release notes or upgrade guides but it managed to break our build for a while.

Is using a callable as a controller supported? Is there any more info about this?

**Comment by Ener-Getick** [comment]
This is actually not supported in FOSRestBundle: some parts of the code have to be changed to support this.

Could you make a PR ?

**Comment by xocasdashdash** [comment]
I could look into it yes. Thanks for the quick answer!

**Comment by Ener-Getick** [comment]
What output do you have ? [This](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener/ParamFetcherListener.php#L62-L64) should make it work...
