### ISSUE TITLE
[question] fos rest 2 release date

### ISSUE THREAD

**Issue by Ma27** [FriendsOfSymfony/FOSRestBundle#1242]
hey there,
I'm planning to update my projects to symfony 3, but there's no stable version of FOSRest supporting it, so I'd like to know when  fosrest 2 will be released

**Comment by Ener-Getick** [comment]
``FOSRestBundle`` 1.7 now supports symfony 3.0.

**Comment by Ma27** [comment]
awesome! thank you :)

**Comment by xabbuh** [comment]
Well, actually the tag for that fix isn't created yet (you can expect that tomorrow), but the `1,7` branch already contains the necessary changes.

**Comment by Ma27** [comment]
seen it, but it'll take some days until I'll bump the version to 3.x :)

2015-12-04 23:58 GMT+01:00 Christian Flothmann <notifications@github.com>:
