### ISSUE TITLE
Unrecognized option "versioning" under "fos_rest"

### ISSUE THREAD

**Issue by gtrias** [FriendsOfSymfony/FOSRestBundle#1262]
Using version 1.7. Throws the error: ``Unrecognized option "versioning" under "fos_rest"``

I've followed all the steps in the official documentation and I can't use versioning feature.
Other thing I'm wondering is why the documentation points to FOSRestBundle 2.0 version if such version still doesn't exists?

Should I use other version? I can see the last release is 1.7.4, the one I have installed. And there isn't the ``versioning`` key on ``Configuration.php``. Is this feature available?

Thanks

**Comment by gtrias** [comment]
Ok, I can see in master is defined the option in Configuration.php so, I guess there's not a release with this feature yet?

**Comment by stof** [comment]
Indeed. This feature is not yet released.

Regarding the doc, symfony.com displays the master branch by default for bundles. But there is a version switcher to see the 1.7 doc

**Comment by Ener-Getick** [comment]
We can probably easily port this feature to 1.8

**Comment by gtrias** [comment]
I would appreciate to be able to use this feature for a project I'm working in :), so if this can be easily port to 1.8 here you have my :+1:

**Comment by lsmith77** [comment]
@gtrias just FYI 1.8 will not be released before 2.0 though .. but it will be easier to switch from 1.7 to 1.8
