### ISSUE TITLE
Add namespace to documentation

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSRestBundle#1266]
The current documentation does not contain any namespaces.
http://symfony.com/doc/current/bundles/FOSRestBundle/2-the-view-layer.html

I think this namespace should be used in the example:
```
namespace AppBundle\Controller;
```

Or what's about ``ApiBundle\Controller``?

**Comment by Ener-Getick** [comment]
:+1:
I think that we should follow the [symfony standards](http://symfony.com/doc/current/contributing/documentation/standards.html) and use the ``AppBundle`` at least for the first code block of each page then we can just add the file path.

IMO we should also remove all the ``<?php`` tag.

**Comment by lsmith77** [comment]
@JHGitty would you be motivated to work on a PR?
