### ISSUE TITLE
weird fails when trying to install FOSRestBundle 1.7.5

### ISSUE THREAD

**Issue by Ma27** [FriendsOfSymfony/FOSRestBundle#1271]
hello there.
at one of my open source projects we tried to update FOSRestBundle to 1.7.5, but then we got a lot of weird failures such as "FOS\RestBundle\Util\COdes" not found.
I know that this class will be removed in 2.0, but not in a patch release. The result of that issue was the following commit:https://github.com/Sententiaregum/Sententiaregum/commit/c246cda2cfc34799f74d2549f6b92430827b2dd9

I just had a look on your releases section and it seems as you tagged the 1.7.5 from the wrong branch.
(it says that 1.7.5 is 9 commits to __master__ and not to 1.7)

/cc @benbieler

**Comment by piotrantosik** [comment]
Is a bug with tag - 1.7.5 is tagged as 2.0 release https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7.5/composer.json

**Comment by Ener-Getick** [comment]
Arf yeah that's a mistake, sorry... 
I just [released ``1.7.6``](https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/1.7.6).

**Comment by Ma27** [comment]
thx :+1:
