### ISSUE TITLE
[1.8] Class 'Negotiation\FormatNegotiator' not found

### ISSUE THREAD

**Issue by fsevestre** [FriendsOfSymfony/FOSRestBundle#1277]
While adding some tests for #1224, I ended up with this error:

```
PHP Fatal error:  Class 'Negotiation\FormatNegotiator' not found in .../FOSRestBundle/Util/FormatNegotiator.php on line 34
```

It installed the v2.0.2 of https://github.com/willdurand/Negotiation which don't have the `FormatNegotiator` class anymore.

**Comment by Ener-Getick** [comment]
Did you try to run ``composer update``?
``1.8`` doesn't support ``willdurand/negotiation`` 2.0 (see [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.8/composer.json))

**Comment by fsevestre** [comment]
Sorry my bad, you are right.
