### ISSUE TITLE
Response should not be automatically 204 if empty

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSRestBundle#1278]
The response is automatically on status code 204 if the response is empty.

```php
$view = $this->view(null, 200);
return $this->handleView($view);
```
.. results in a 204 response. I've expected status code 200.

**Comment by Ener-Getick** [comment]
Well IMO, if the status code is manually defined by the user, we should not override it.
(that's your case)

But in the case that the status code is not specified, I think that we should override it if the response is empty.

**Comment by JHGitty** [comment]
@Ener-Getick Sure - but why happened it on my code? :smile:

**Comment by Ener-Getick** [comment]
Because we actually don't make any difference between this two cases.
Could you create a PR on master?

**Comment by lsmith77** [comment]
+1

**Comment by JHGitty** [comment]
Thanks @Ma27 @lsmith77 @Ener-Getick

**Comment by Ma27** [comment]
you're welcome
