### ISSUE TITLE
Displaying only 404 error messages on JSON (FOSRestBundle)

### ISSUE THREAD

**Issue by Zoumourrouda** [FriendsOfSymfony/FOSRestBundle#1280]
I used FOSRestBundle in order to convert the error messages format to JSON.

This is the fos_rest config part in config.yml :
```
fos_rest:
    routing_loader:
        default_format: json
        include_format: true                           # We do not include format in request, so that all responses
    view:
        view_response_listener: force
        force_redirects:
            html: true
    format_listener:
        rules:
            - { path: '^/', fallback_format: json}
    param_fetcher_listener: force
    body_listener: true
    exception:
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
```
The problem is that all pages (even with status code = 200) are converted and not only when error occurs (404, 500, ...)

**Comment by Ener-Getick** [comment]
What do you mean?
The pages are converted when an error occurs and your configuration only defines which status code to use for this classes. 
You have to catch your exception in your controller if you want it to not be converted.

**Comment by Zoumourrouda** [comment]
In fact, I want to change the format of the 404 error pages into JSON. But that does not exactly happened.
I noticed that this line : 
```
 format_listener:
        rules:
            - { path: '^/', fallback_format: json}
```
changes the format of all pages

**Comment by Ener-Getick** [comment]
What's your use case? 
I don't understand why you want to have a different format for an error page than the normal page. 

You actually can't do such thing and I don't think that we should support it.
The route matchers covers most of the cases (if not all).

**Comment by Zoumourrouda** [comment]
Actually, I thought that it was possible to change only the error pages format by following this guide http://symfony.com/doc/current/bundles/FOSRestBundle/4-exception-controller-support.html

Is it really impossible? Do I have to give up? :(

**Comment by Ener-Getick** [comment]
No it's impossible you can only change their status and their content but not their format which is the same as the corresponding normal page.

**Comment by Ener-Getick** [comment]
You can still create your own exception controller extending the FOSRestBundle's exception controller.

**Comment by Zoumourrouda** [comment]
Ok thank you for your help :)

**Comment by Ener-Getick** [comment]
You're welcome :-)
If you think this should be added you can still leave this issue opened but I think even if we wanted to support it, it would complicated technically.

ping @xabbuh @lsmith77

**Comment by xabbuh** [comment]
I agree with @Ener-Getick. Supporting this in a generic way only complicates things and honestly I do not thing that this is an everyday use case. Maybe you can even just register another listener that intercepts before the one from FOSRestBundle and only steps into when an exception occurred.

**Comment by basma-yangui** [comment]
@xabbuh  Can you explain more your solution please?
