### ISSUE TITLE
FOSRestExtension.php on line 447

### ISSUE THREAD

**Issue by xorgxx** [FriendsOfSymfony/FOSRestBundle#1300]
Hi thank for this bundle.

i have probleme on production : i get this error 
```
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /srv/data/web/vhosts/www.dede-sacs.com/htdocs/vendor/friendsofsymfony/rest-bundle/DependencyInjection/FOSRestExtension.php on line 447
```
it's impossible to try any command line on server production (gandi) but i get not probleme on local server Xampp on windows 10 64

can you try to help?
thank

**Comment by xabbuh** [comment]
It seems that your production server does not run on PHP 5.5 or higher yet (the `class` constant was introduced in PHP 5.5) while your local development environment does.

There's nothing we can do about that in FOSRestBundle (the 2.0 version will not support PHP versions before 5.5 anymore). So I'll close this issue. But please feel free to ask if you still have questions.

**Comment by xorgxx** [comment]
thank. it look correct ver server local PHP Version 5.5.11 and on gandi PHP Version 5.4.45-0+deb7u2
