### ISSUE TITLE
Missing reference for mime type listener link

### ISSUE THREAD

**Issue by yceruto** [FriendsOfSymfony/FOSRestBundle#1304]
https://github.com/FriendsOfSymfony/FOSRestBundle/blame/master/Resources/doc/format_listener.rst#L89

**Comment by Ener-Getick** [comment]
Can you create a PR please?

**Comment by yceruto** [comment]
@Ener-Getick I'm not sure what the correct URL link. :(

**Comment by Ener-Getick** [comment]
I think that we can just add a link to the ``Listener`` documentation:
```rst
:doc:`Mime Type Listener <3-listener-support>`.
```

**Comment by yceruto** [comment]
> Note that the format needs to either be supported by the ``Request`` class
natively or it needs to be added as documented here or using the
`mime type listener` explained in the Symfony documentation.

``.. _`mime type listener`: http://symfony.com/doc/current/cookbook/request/mime_type.html`` ??

**Comment by Ener-Getick** [comment]
This doc is outdated. In ``master`` the mime types need to be added in the ``FOSRestBundle`` documentation. See [here](http://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#mime-type-listener)
