### ISSUE TITLE
Argument 1 passed to FOS\RestBundle\Decoder\ContainerDecoderProvider::__construct() must implement interface

### ISSUE THREAD

**Issue by shakaran** [FriendsOfSymfony/FOSRestBundle#1313]
I am using Symfony v2.7.9 and in the last update from composer of friendsofsymfony/rest-bundle I see:

  * - Removing friendsofsymfony/rest-bundle (dev-master 6ebbd6d)
  * - Installing friendsofsymfony/rest-bundle (dev-master ce3f183)

Now I am getting the trace:

    [2016-01-15 11:30:32] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to FOS\RestBundle\Decoder\ContainerDecoderProvider::__construct() must implement interface Symfony\Component\DependencyInjection\ContainerInterface, array given, called in /home/myapp/public/releases/20151216130325/app/cache/prod/appProdProjectContainer.php on line 749 and defined at /home/myapp/public/shared/vendor/friendsofsymfony/rest-bundle/Decoder/ContainerDecoderProvider.php line 32) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to FOS\\RestBundle\\Decoder\\ContainerDecoderProvider::__construct() must implement interface Symfony\\Component\\DependencyInjection\\ContainerInterface, array given, called in /home/myapp/public/releases/20151216130325/app/cache/prod/appProdProjectContainer.php on line 749 and defined at /home/myapp/public/shared/vendor/friendsofsymfony/rest-bundle/Decoder/ContainerDecoderProvider.php:32)"} []

So I am not sure if it is a bug in my app or the update of friendsofsymfony/rest-bundle breaks my application since I cannot figure out which line breaks the code in my app with the trace.

Any idea?

**Comment by Ener-Getick** [comment]
@shakaran did you clean your cache? If yes, do you have a service extending ``fos_rest.decoder_provider`` or using ``FOS\RestBundle\Decoder\ContainerDecoderProvider``?

**Comment by shakaran** [comment]
Hi @Ener-Getick 

I think that I don't have any piece of code directly using the fos_rest.decoder_provider or FOS\RestBundle\Decoder\ContainerDecoderProvider directly, but I don't know if some bundle or dependancy is using it.

As far I see grepping all the folder I see this:

    # grep -rin "fos_rest.decoder_provider" /home/myapp/public/current
    /home/myapp/public/current/app/cache/prod/appProdProjectContainer.php:113:            'fos_rest.decoder_provider' => 'getFosRest_DecoderProviderService',
/home/myapp/public/current/app/cache/prod/appProdProjectContainer.php:707:        $this->services['fos_rest.body_listener'] = $instance = new \FOS\RestBundle\EventListener\BodyListener($this->get('fos_rest.decoder_provider'), false);
/home/myapp/public/current/app/cache/prod/appProdProjectContainer.php:725:        return $this->services['fos_rest.decoder_provider'] = new \FOS\RestBundle\Decoder\ContainerDecoderProvider($this, array('json' => 'fos_rest.decoder.json', 'xml' => 'fos_rest.decoder.xml'));

    # grep -rin "ContainerDecoderProvider" /home/myapp/public/current
    /home/myapp/public/current/app/cache/prod/appProdProjectContainer.php:725:        return $this->services['fos_rest.decoder_provider'] = new \FOS\RestBundle\Decoder\ContainerDecoderProvider($this, array('json' => 'fos_rest.decoder.json', 'xml' => 'fos_rest.decoder.xml'));

After I force the delete of cache with symfony command and with:

    # rm -rf /home/myapp/public/current/app/cache/prod/*

It is still generating the same lines of code.

**Comment by shakaran** [comment]
And reverting to 6ebbd6d the bug seems dissappear.

**Comment by Ener-Getick** [comment]
It don't seem to be related to ``FOSRestBundle``... 

Any idea @xabbuh ?

**Comment by xabbuh** [comment]
This is weird as the error message doesn't match the generated container code (as you can see the first argument is `$this` which clearly is not an array but the actual container).

**Comment by xabbuh** [comment]
@shakaran Can you show the line from the generated container that is mentioned in the error message?

**Comment by Ener-Getick** [comment]
ping @shakaran

**Comment by shakaran** [comment]
Sorry for delay, I treat to reproduce today the bug, but it seems that depdencies or updates didn't broke again the code or some codebase was changed, so not sure if it is really fixed or only hidden. Probably you can close it and I will reopen if I see it again.

**Comment by xabbuh** [comment]
Thanks for the feedback. Just let use know in case you experience this again.

**Comment by mpbzh** [comment]
For anyone debugging his code and getting the same exception: I got it when I tried to run a Symfony 2.8 application with some bundles that required PHP 5.6 on a server that was running PHP 5.4. Updating the server to 5.6 fixed the problem.

**Comment by shakaran** [comment]
@mpbzh probably could be my exact workaround (but I didn't know it), since I was using php 5.4 too and now I am using 5.6.11 by the Ubuntu updates.
