### ISSUE TITLE
branch 1.7 is broken

### ISSUE THREAD

**Issue by ktounet** [FriendsOfSymfony/FOSRestBundle#1318]
due to commit e637ce6b7f3763b973b917ba29b00b928193c46a

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7/Routing/Loader/Reader/RestActionReader.php#L355

```php
Warning: is_subclass_of() expects at least 2 parameters, 1 given
```
This : 
```php
is_subclass_of($argumentClass, $className)
```

Instead of : 
```php
is_subclass_of($className)
```

**Comment by xabbuh** [comment]
fixed in #1319
