### ISSUE TITLE
Patch request don't work with file

### ISSUE THREAD

**Issue by ugurerkan** [FriendsOfSymfony/FOSRestBundle#1321]
Hello,

I have a simple patch action which is update user data with given form type.
The problem is when send a file with patch request, REST Bundle or Symfony can't parse request body.
Getting empty $request file and parameter bags on controller but $request->getContent is correct. 
Also I have no problem with post request which is contain files, this is happening only with patch requests.
```php
    public function patchMeAction(Request $request)
    {

        $userManager = $this->container->get('fos_user.user_manager');
        $user        = $this->getUser();

        if(null === $user){
            throw $this->createNotFoundException('User does not exists');
        }

        $form        = $this->createForm(new UserType(), $user);

        $form->submit($request,false);
        if ($form->isValid()){
            $userManager->updateUser($user);

            return $this->routeRedirectView('v1_get_user', array('userID' => $user->getId()));
        }

        return array(
            'form' => $form
        );
    }
```

**Patch request is like this.**
![screen shot 2016-01-21 at 05 09 07](https://cloud.githubusercontent.com/assets/473959/12470628/73d42d6c-bffe-11e5-8233-a8505bccb88e.png)

**This is request dump with file.**
![screen shot 2016-01-21 at 05 07 41](https://cloud.githubusercontent.com/assets/473959/12470638/8c629bf2-bffe-11e5-93a1-035f245efb4e.png)

**This is request dump without file.**
![screen shot 2016-01-21 at 05 08 05](https://cloud.githubusercontent.com/assets/473959/12470642/9584c14c-bffe-11e5-88df-52867f9c43ee.png)

Software | Version
------------ | -------------
friendsofsymfony/rest-bundle | 1.7.7
Symfony | 2.8.2
PHP | 5.6.17

**Comment by Ener-Getick** [comment]
This behavior is linked to PHP not to ``FOSRestBundle``.
PHP fills ``$_FILES`` only when using ``POST`` and ``PUT``. And this variable is used internally by symfony...
See the [php doc](https://secure.php.net/manual/fr/features.file-upload.post-method.php).
