### ISSUE TITLE
You have requested a non-existent service "fos_user.doctrine_registry".

### ISSUE THREAD

**Issue by tianchaoc** [FriendsOfSymfony/FOSRestBundle#1333]
When I modify the “security.yml ” it give me this message, who konws why? 

this is my security.yml code:

security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 10
 
    providers:
        fos_user:
            id: fos_user.user_provider.username
 
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: fos_user
                csrf_provider: form.csrf_provider
            logout:       true
 
    access_control:
        - { path: ^/news/(new|(\d+\/edit)), roles: IS_AUTHENTICATED_FULLY }

**Comment by Ener-Getick** [comment]
This doesn't seem to be related to FOSRestBundle
