### ISSUE TITLE
Return view with http code 204, where is content-type ?

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSRestBundle#1344]
Hello.

I update a last version symfony2.3 and version 1.7.7 FosRestBundle.

But in my project I have test that check 
>$this->assertEquals('application/json', $response->headers->get('Content-type'));

But now a response with httpcode 204 the content-type in header is null... 

If I do : 
>$view->getFormat()

It return json.

did FosRestBundle change the logic to response with code 204?

Only I get error in response with httpcode 204... o_0

Any idea or suggestion ? I read all changelog but I found nothing about it...

Thanks in advance.

**Comment by Chrysweel** [comment]
OK, I think I found error. 

It is a issue of symfony sorry.

https://github.com/symfony/symfony/blob/75abd1a451d97f5075128ea10b2598b6df41a065/src/Symfony/Component/HttpFoundation/Response.php#L212

Now reponse with code 204 has not content-type.

I close the issue ! sorry again :)

**Comment by Ener-Getick** [comment]
That's weir to have a ``Content-Type`` with an empty response, this is probably why symfony removes this header.

**Comment by r-martins** [comment]
It seems this behavior breaks Postman.
![Postman_Console_and_Postman](https://user-images.githubusercontent.com/191149/85504287-0b729c00-b62f-11ea-9b5b-21ec1a8c5bce.jpg)
