### ISSUE TITLE
Interaction between "ExceptionController support" and "Forms errors wrapper"

### ISSUE THREAD

**Issue by Abam** [FriendsOfSymfony/FOSRestBundle#1357]
I was reading the official documentation for [ExceptionController support](http://symfony.com/doc/1.7/bundles/FOSRestBundle/4-exception-controller-support.html) and the [Form and views](http://symfony.com/doc/1.7/bundles/FOSRestBundle/2-the-view-layer.html#forms-and-views) sections and it got a little bit confused.

I dig into the code and found out that the `fos_rest.exception_handler` and the `fos_rest.view.exception_wrapper_handler` are tightly linked.

If I only set a custom service for the `exception_handler`, the `fos_rest.view.exception_wrapper_handler` is **not used anymore** neither by the ExceptionController nor the ViewHandler.
If I only set a custom `exception_wrapper_handler`, it is used by both the ExceptionController and the ViewHandler.

I realised that by default, the `fos_rest.exception_handler` is an alias to `fos_rest.view.exception_wrapper_handler` and is used by both the ExceptionController and the ViewHandler. There is no way to have 2 differents services for them. 
Is it the wanted behavior ? 

Just for readers, here are the relevant configuration keys used.
```
# app/config/config.yml
fos_rest:
    service:
        exception_handler:    fos_rest.view.exception_wrapper_handler
    view:
        # only relevant when using the JMS serializer for serialization
        exception_wrapper_handler:  null
```

**Comment by Ener-Getick** [comment]
Well IMO we should not keep this wrapper and instead let the serializer normalizes the data.
@lsmith77 Why was this created in first place ?

**Comment by Abam** [comment]
On my understanding, this wrapper helps in formatting all exceptions and form validations errors  in the same format (code, message, errors).

**Comment by Ener-Getick** [comment]
Yeah but serializing an array would be the same. 
BTW it would be clearly more powerful to serialize exceptions instead of only strings representing them (we would be able to have complex responses based on the exception fields).

**Comment by Abam** [comment]
If you use a custom wrapper, the wrap method is called with an array built by the ExceptionController;
I've found no documentation for the expected array passed to wrap method and the one about ExceptionController is IMO not complete at all. 
I spent most of my time exploring the source code and I have no idea if It is safe to relay on it.
```php
<?php
$parameters = array(
            'status' => 'error',
            'status_code' => $code,
            'status_text' => array_key_exists($code, Response::$statusTexts) ? Response::$statusTexts[$code] : 'error',
            'currentContent' => $currentContent,
            'message' => $this->getExceptionMessage($exception),
            'exception' => $exception,
        );
````

**Comment by Ener-Getick** [comment]
Yeah you're right didn't see that from this point of view.
Well you can rely on this array in 1.7/1.8 but this might change in 2.0 (not sure at all because we want to release it soon...).

For your initial issue you can our services as you want (see [the symfony doc](https://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration))

**Comment by Abam** [comment]
With the 2.0, I could be possible (wrapper is injected as a dependency) but unfortunately, as of 1.7 and 1.8, the same service is fetched by the [ExceptionHandler](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.8/Controller/ExceptionController.php#L63) and the [ViewHandler](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7/View/ViewHandler.php#L527) directly from the container, so I can't tweak it  separately.
I've decided to use the `exception_wrapper_handler` config param to setup one wrapper for both cases.
By the way, the comment above the param `# only relevant when using the JMS serializer for serialization` seems wrong since the wrapper is called before any serialization processing.

**Comment by Ener-Getick** [comment]
At worst if you really want to have two different behaviors you can check if the errors field is empty (exception controller) or not (view handler) in your exception wrapper. 

I think the comment was there for when this bundle only supported the jms serializer to advise that the exception wrapper is useless when using deserialization.

**Comment by Abam** [comment]
Thanks for the tips ! 
This issue can be closed.

**Comment by Ener-Getick** [comment]
Would [this](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1358) be better ?
