### ISSUE TITLE
Mandatory "Default" Serializer group in config

### ISSUE THREAD

**Issue by jbenezech** [FriendsOfSymfony/FOSRestBundle#1361]
I just spent a few hours trying to understand why the serialization was always returning an empty json, so although I am not sure if this is a lack of documentation or a bug, I'd figure I'll open this issue for others to find.

I'm using FOSRestBundle 1.8 and JMSSerializationBundle on master.
If there is no groups defined in the configuration for the serializer, all properties will be excluded from the serialization.
So this minimum configuration is mandatory:

```
fos_rest:
    serializer:
        groups: ["Default"]
```
If this is not set, the serialization context will get an array with 1 element whose key is an empty string, probably due to this cast in the ViewHandler

```
public function setExclusionStrategyGroups($groups)
{
    $this->exclusionStrategyGroups = (array) $groups;
}
```
This in turns introduces 1 exclusion group and the shouldSkipProperty method of JMS\Serializer\Exclusion\GroupsExclusionStrategy will always return true.

I have not looked much deeper yet as to why this is passed an empty string instead of an empty array.
I guess this is due to some changes in 1.8 related to switching the serialization context from JMS to FOSRest.

**Comment by Ener-Getick** [comment]
Could you create a PR containing a test reproducing your issue or a fork of ``symfony/standard-edition`` please?

**Comment by jbenezech** [comment]
Can't be able to clone symfony-standard today so can't give you a fork to reproduce the issue.
Proposed fix: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1365

The issue comes from the XMLFileLoader setting the `fos_rest.serializer.exclusion_strategy.groups` parameter to an empty string in the container.
When the `ViewHandler` service is loaded and the `setExclusionStrategyGroups` called, this sets the `exclusionStrategyGroups` to an array with 1 entry (empty string).
None of the properties of the entities satisfy this group and the serializer ignores them.

**Comment by jbenezech** [comment]
Finally managed to clone symfony-standard.
Problem reproduced here:
https://github.com/jbenezech/symfony-standard/tree/fos_rest_serialization_issue
Commit:
https://github.com/jbenezech/symfony-standard/commit/7f1dd0d70ff494613182559fe1fe5432533a2bec
