### ISSUE TITLE
Error on TwigExceptionController

### ISSUE THREAD

**Issue by shakly** [FriendsOfSymfony/FOSRestBundle#1375]
Since  #1372 / #1374 , i have this issue when i get a NotFoundHttpException or MethodNotAllowedHttpException
```
ContextErrorException in TwigExceptionController.php line 29:
Notice: Undefined variable: format
```

**Comment by Ener-Getick** [comment]
We should really test this class... and I should look a bit more to my PR before merging it...
Thank you, I'll search how to fix it :-)

**Comment by Ener-Getick** [comment]
Can you take a look at https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1376 please?
