### ISSUE TITLE
private functions in controller

### ISSUE THREAD

**Issue by LeniA1** [FriendsOfSymfony/FOSRestBundle#1384]
in the aim to be able to override the controller, the methods ThreadController::getValidCommentParent and ThreadController::getViewHandler should be protected and not private. Otherwise you need ti declare it again.

I hope i posted in the right section, let me know if it's the wrong one :)

**Comment by Ener-Getick** [comment]
You're not in the right bundle. Post your issue in [``FOSCommentBundle``](https://github.com/FriendsOfSymfony/FOSCommentBundle).
