### ISSUE TITLE
@Version() annotation is ignored, when method has no @Route annotation

### ISSUE THREAD

**Issue by jovobe** [FriendsOfSymfony/FOSRestBundle#1386]
When a controller is annotated with a version (like in the docs: http://symfony.com/doc/master/bundles/FOSRestBundle/versioning.html#how-to-match-a-specific-version-in-my-routing) the version condition is only added to the route for methods, which are annotated with @Route.
I think this is the piece of code which should be fixed (FOS\RestBundle\Routing\Loader\Reader\RestActionReader line: ~295):
![restactionreader php 2016-03-10 17-49-07](https://cloud.githubusercontent.com/assets/1265894/13677051/c211c014-e6e8-11e5-9163-46aa66c1479d.png)

**Comment by Ener-Getick** [comment]
Thank you for the report, could you create a patch to fix this and add a test to avoid regressions please?

**Comment by dmaicher** [comment]
@Ener-Getick  I created a PR to address the issue: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1438

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1438#discussion_r61300067
