### ISSUE TITLE
Reserve HATEOAS keywords for auto-route generation

### ISSUE THREAD

**Issue by bblue** [FriendsOfSymfony/FOSRestBundle#1393]
I suggest to reserve/explicitly create routes for the HATEOAS keywords ([new, edit, remove](http://symfony.com/doc/master/bundles/FOSRestBundle/5-automatic-route-generation_single-restful-controller.html#conventional-actions)) to ensure the routes will work.

i.e. if newPageAction() is implemented _after_ getPageAction() in the controller used as the resource for automatic route generation, then the route localhost/pages/new will never hit the intended method, but instead generate a 404 error.

I was tearing my hair out before I realised the routes were defined by the order the methods were implemented in my controller. By moving my newPageAction() before getPageAction() the issue was resolved. As a new Symfony user this took me some time to figure out.

**Comment by Ener-Getick** [comment]
:+1: I think we can safely add this as a bug fix

**Comment by xabbuh** [comment]
I absolutely agree. This looks like one of the WTF moments that we should definitely avoid.

**Comment by lsmith77** [comment]
Yeah this is an annoying issue but I do not understand the proposed solution.

**Comment by bblue** [comment]
That was not really a solution. And I cannot recall exactly what I was thinking at the time, probably just a proposal to somehow let the user know why a 404 is generated by some fallback route. I'm at our summer cabin with no real way of investigating a proposed fix now (no 3G/4G), might look at it in a couple of weeks.

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954
