### ISSUE TITLE
Template guessing no longer works with @View

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/FOSRestBundle#1395]
#1355 introduced major changes to the ViewResponseListener, but using @Rest\View will no longer guess the template name if one is not provided.

It seems to me like we're duplicating quite a bit of logic with the SensioFrameworkExtraBundle's TemplateListener and digging further that using these annotations for their 'magic' seems to be very slow: https://github.com/symfony/symfony/pull/17933

It seems to me like we either need to refactor the TemplateListener so we can reuse the same logic that the ViewResponseListener needs or if that isnt likely to happen at least have feature parity with the TemplateListener.

**Comment by Ener-Getick** [comment]
Status: reviewed

We have to do something here ... but submitting a PR to SensioExtraFrameworkBundle should be better than copy-pasting more logic in FOSRestBundle...

**Comment by Ener-Getick** [comment]
I opened https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/409

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/409. Will be completely fixed as soon as they release a new patch version.
