### ISSUE TITLE
Use FOSRestBundle as Symfony Services instead of extend from Controller

### ISSUE THREAD

**Issue by DavidGarciaCat** [FriendsOfSymfony/FOSRestBundle#1397]
Hey there,

I have been checking your documentation but (for now) I cannot see an easy way to use the FOSRestBundle on my Controllers using Symfony Services, so I would like to know if you have added this option or maybe if you have planed to add it on next releases.

I would like to use FOSRestBundle using my API Controllers as services, like:
```
class MyController
{
    private $myDependency;

    public function __construct(MyDependency $myDependency)
    {
        $this->myDependency = $myDependency;
    }

    // Actions here
}
```
...instead of...
```
class MyController extends Controller
{
    private function getMyDependency()
    {
        return $this->get('my.dependency');
    }

    // Actions here
}
```

Is that possible?

Thanks, and regards,

**Comment by stof** [comment]
Use the service id instead of the class name when importing the rest routing resource for this controller, and it will work.

**Comment by alsar** [comment]
Yes, it is possible. You define your controllers as it is stated in the Symfony docs: https://symfony.com/doc/current/cookbook/controller/service.html

The only additional thing you have to do, is that you have to define the service id of the controller in the FOS Route annotation.

Example:
```
use FOS\RestBundle\Controller\Annotations as Rest;

/**
 * @Service("api_profile_controller")
 *
 * @Rest\Route(service = "api_profile_controller")
 */
class ProfileController
```

**Comment by stof** [comment]
yeah, both ways are actually supported

**Comment by DavidGarciaCat** [comment]
Hello guys,

Thanks for your comments.
I am going to try this immediately.

Given these solutions, I think we can close the issue.

Thanks for your help!
