### ISSUE TITLE
Decode JSON body in php array

### ISSUE THREAD

**Issue by Jerome1337** [FriendsOfSymfony/FOSRestBundle#1401]
I'm working on a `PATCH` method and I need to decode the JSON body sent during the request in a PHP array.

I tried to use `json_decode()` in my controller : 

```
$data = json_decode($updatedServer, true);
```

But this return nothing, I don't know why. I tried in a non-Api controller and this is working well.

The body is not empty and contains a JSON object like this one

```
{
  "id": null,
  "name": "vv",
  "alias": null,
  "notes": null,
}
```

How can I convert my JSON body into a PHP array ?

**Comment by Ener-Getick** [comment]
Did you try the [body listener](https://symfony.com/doc/current/bundles/FOSRestBundle/body_listener.html) ?

We would more informations about your controller to understand your issue.

**Comment by Jerome1337** [comment]
> Did you try the body listener ?
No but this will decode every request response I get, no ?

```

**Comment by Ener-Getick** [comment]
``$updatedServer`` is type hinted as ``Server`` so it probably isn't a json string...

**Comment by Jerome1337** [comment]
Yes, I understood this after I answered on this issue.
