### ISSUE TITLE
"Allowed Http Methods Listener" not working on Symfony 3

### ISSUE THREAD

**Issue by renan-taranto** [FriendsOfSymfony/FOSRestBundle#1412]
Allow header does not appear on responses using Symfony version 3.03. I have another project running on Symfony version 2.8.1 where the listener works fine. 
The config.yml line where I enable it in both projects:
```yml
allowed_methods_listener: true
``` 
The headers that cURL outputs not containing the Allow header;
```HTTP
Host: localhost:8000
Connection: close
X-Powered-By: PHP/5.6.19-1+deb.sury.org~trusty+1
Cache-Control: no-cache
Content-Type: application/json
X-Debug-Token: b5b884
X-Debug-Token-Link: /app_dev.php/_profiler/b5b884
Date: Sun, 03 Apr 2016 18:10:52 GMT

**Comment by Ener-Getick** [comment]
Thanks for the report, but I do not use much this listener.
Could you provide more details please? like checking if the listener is registered/executed on sf 3.1 and if you can detect where the problem is located?

Or you prefer, can you fork the symfony standard edition and reproduce your issue in it to help us debug ?

**Comment by renan-taranto** [comment]
Some more details:
-The listener is registered.
-This listener obtains the allowed methods trough the AllowedMethodsRouterLoader class wich iterates (line 73) over Route objects and their $requirements array properties to grab the methods. **I noticed that these Route objects does not have the '_method' key in the $requirements property**.
-Requesting with a not allowed method gives me a 405 status code with the Allow header perfectly set.

**Comment by renan-taranto** [comment]
I believe I was able to fix the issue. I will fork and make a pull request as soon as I have time.

**Comment by Ener-Getick** [comment]
Nice, I didn't have the time yet to take a deep look at your issue.
If you prefer, you can only describe where the issue is located.

**Comment by renan-taranto** [comment]
I tried creating the pull request 3 times but all failed passing the checks for the 2.0 version.
I believe that the problem happens while creating the routes on RestActionReader class.
 Symfony 2 Route class used to add the method requirements trough the setMethods method called by the constructor, this does not happens on Symfony 3.
I was able to fix the issue on FOSRestBundle v1.7 with this addition to the RestActionReader class:
```php
    private function includeMethodsIfNeeded(array $methods, &$requirements)
    {
        if (!isset($requirements['_method']) && !empty($methods)) {
            $requirements['_method'] = implode('|', $methods);
        }
    }
```
The above method had to be called from the read() public method twice (once for annotations and once for the other case).

**Comment by Ener-Getick** [comment]
Actually I don't think that's the right fix, which version of FOSRestBundle do you use ?

**Comment by renan-taranto** [comment]
Version 1.7. The fix I mentioned in my last comment worked on FOSRestBundle 1.7 and Symfony 3.

**Comment by Ener-Getick** [comment]
Yeah but it triggers deprecations, I'll open a PR ;-)

**Comment by Ener-Getick** [comment]
I opened #1419

**Comment by renan-taranto** [comment]
Yeah you are right, like I said it didn't passed the checks. Hope it helps someway.
