### ISSUE TITLE
Fix the AllowedMethodsListener in 2.0

### ISSUE THREAD

**Issue by Ener-Getick** [FriendsOfSymfony/FOSRestBundle#1420]
The AllowedMethodsListener doesn't work at all in 2.0 so we have to adapt #1419 to make it work again.

**Comment by xabbuh** [comment]
@Ener-Getick You are right. Thanks for taking care of creating this issue to keep track of it.

**Comment by Ener-Getick** [comment]
@xabbuh you're welcome ☺ 
i'll try to fix this this week, otherwise it will have to wait a bit (i won't be there next week) 

I don't know if this is really complicated to do, maybe fixing conflicts will be enough.

**Comment by xabbuh** [comment]
Let's see what the tests tell us in #1422.

**Comment by xabbuh** [comment]
fixed by #1422

**Comment by Ener-Getick** [comment]
Great, thank you @xabbuh
