### ISSUE TITLE
fosrestbundle 2.0

### ISSUE THREAD

**Issue by NadaBen** [FriendsOfSymfony/FOSRestBundle#1429]
hello, i want to install fosrestbundle version 2.0, when i add this version in te composer, it does not work

**Comment by xabbuh** [comment]
@NadaBen What does that mean? Which exact steps did you do and what happened then?

**Comment by NadaBen** [comment]
i try to add fos restbundle in the composer with "friendsofsymfony/rest-bundle": "2.0", or with "friendsofsymfony/rest-bundle": "*", and it work for * but it install 1.7. version , when i add it mannually it show me this error Class 'FOS\RestBundle\FOSRestBundle not found in AppKernel.php

**Comment by xabbuh** [comment]
Please note that we do not have a stable release of FOSRestBundle 2.0 yet. You need require a beta version:

```bash
$ composer require friendsofsymfony/rest-bundle:~2.0@beta
```

**Comment by NadaBen** [comment]
i try it with ~2.0@beta  but 
Problem 1
    - Conclusion: don't install symfony/symfony v2.5.12
    - Conclusion: don't install symfony/symfony v2.5.11
    - Conclusion: don't install symfony/symfony v2.5.10
    - Conclusion: don't install symfony/symfony v2.5.9
    - Conclusion: don't install symfony/symfony v2.5.8
    - Conclusion: don't install symfony/symfony v2.5.7
    - Conclusion: don't install symfony/symfony v2.5.6
    - Conclusion: don't install symfony/symfony v2.5.5
    - Conclusion: don't install symfony/symfony v2.5.4
    - Conclusion: don't install symfony/symfony v2.5.3
    - Conclusion: don't install symfony/symfony v2.5.2
    - Conclusion: remove symfony/symfony v2.5.1
    - Conclusion: don't install symfony/symfony v2.5.1
    - friendsofsymfony/rest-bundle 2.0.0-BETA1 requires symfony/finder ^2.7|^3.0 -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4].
    - friendsofsymfony/rest-bundle 2.0.0-BETA2 requires symfony/finder ^2.7|^3.0 -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4].
    - don't install symfony/finder v2.7.0|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.1|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.10|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.11|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.2|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.3|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.4|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.5|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.6|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.7|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.8|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.7.9|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.8.0|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.8.1|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.8.2|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.8.3|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v2.8.4|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v3.0.0|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v3.0.1|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v3.0.2|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v3.0.3|don't install symfony/symfony v2.5.0
    - don't install symfony/finder v3.0.4|don't install symfony/symfony v2.5.0
    - Installation request for symfony/symfony 2.5.* -> satisfiable by symfony/symfony[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - Installation request for friendsofsymfony/rest-bundle ~2.0@beta -> satisfiable by friendsofsymfony/rest-bundle[2.0.0-BETA1, 2.0.0-BETA2].

Done.

**Comment by xabbuh** [comment]
Well, you need Symfony 2.7 or higher (precisely only some components/bundles are actually required by FOSRestBundle). The new bundle version is not compatible with Symfony 2.5.

**Comment by NadaBen** [comment]
Okey i'll install symfony 2.7.. thank you
