### ISSUE TITLE
Unrecognized option "exception_handler" under "fos_rest.service" 

### ISSUE THREAD

**Issue by sgasser** [FriendsOfSymfony/FOSRestBundle#1434]
Hi.

After upgrading from 1.7 to 2.0. I get following error:

```Unrecognized option "exception_handler" under "fos_rest.service".```

This options exists in configuration-reference (2.0): http://symfony.com/doc/master/bundles/FOSRestBundle/configuration-reference.html

I can't find anything in UPGRADING.md.

What I have to do?

Offtopic:
I only upgraded to 2.0beta because I need symfony 2.8 support.
Do you accept pull requests on 1.7 with deprecation fixes for symfony 2.8/3.0?

**Comment by xabbuh** [comment]
@sgasser If you do not want to deal with BC breaks right now, you can use 1.8 (which also is in BETA right now) which is compatible with Symfony 2.8.

Nonetheless, we should of course fix the documentation if it is wrong about this.

**Comment by xabbuh** [comment]
For the record, this option was removed in #1358.

**Comment by Ener-Getick** [comment]
Fixed in #1446
