### ISSUE TITLE
Fix multiple version for one controller route condition

### ISSUE THREAD

**Issue by boyez-joggin** [FriendsOfSymfony/FOSRestBundle#1436]
As I found out, it seems that having multiple version in one Version annotation for a Controller breaks the routing condition.

I found the condition is generated like this before evaluating to write cache:
```
request.attributes.get("version") == (<version> or <version> or <version>)
```

this evaluates to true during runtime for any non empty string and breaks the version limitation.

I corrected the code to generate with _in_ operator like this:
```
request.attributes.get("version") in [<version>, <version>, <version>]
```

**Comment by dmaicher** [comment]
How exactly did the annotations your controller look like?

**Comment by boyez-joggin** [comment]
My annotations were like this:
![symfony_rest_versions](https://cloud.githubusercontent.com/assets/18553271/14674754/cf6e9542-0705-11e6-8cd8-458c000a44c4.png)

And my final condition in the auto-generated url matcher is that:
![symfony_url_matcher](https://cloud.githubusercontent.com/assets/18553271/14674815/1ea6fb4a-0706-11e6-87ef-5fe27bc5b612.png)

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1438
