### ISSUE TITLE
Import two rest resource routing with custom header versioning only works for last added entry

### ISSUE THREAD

**Issue by cve** [FriendsOfSymfony/FOSRestBundle#1469]
Hi,

first of all thanks for working on this helpful bundle.

I want to API versioning based on custom accept header, so my conf:

    fos_rest:
        versioning:
            enabled: true
            resolvers:
                custom_header: true
        view:
            view_response_listener:
                force: true
        routing_loader:
            include_format: false
            default_format: json

rounting:

    app_v1:
        resource: "@AppBundle/Controller/V1/ProductController.php"
        type:     rest
    
    app_v2:
        resource: "@AppBundle/Controller/V2/ProductController.php"
        type:     rest

and controller from V1:

    <?php
    
    namespace AppBundle\Controller\V1;
    
    use FOS\RestBundle\Controller\Annotations\Version;
    use FOS\RestBundle\Routing\ClassResourceInterface;
    
    /**
     * @Version("1.0")
     */
    class ProductController implements ClassResourceInterface
    {
        public function cgetAction()
        {
            return [
                ['name' => 'test 1', 'price' => 51.63],
                ['name' => 'test 1', 'price' => 51.63],
                ['name' => 'test 1', 'price' => 51.63],
                ['name' => 'test 1', 'price' => 51.63],
            ];
        }
    }

and V2:

    <?php
    
    namespace AppBundle\Controller\V2;
    
    use FOS\RestBundle\Controller\Annotations\Version;
    use FOS\RestBundle\Routing\ClassResourceInterface;
    
    /**
     * @Version("2.0")
     */
    class ProductController implements ClassResourceInterface
    {
        public function cgetAction()
        {
            return [
                ['name' => 'test 2', 'price' => 51.63],
                ['name' => 'test 2', 'price' => 52.63],
                ['name' => 'test 2', 'price' => 52.63],
                ['name' => 'test 2', 'price' => 51.63],
            ];
        }
    }

The problem is when I call a request with X-Accept-Version = 2.0 it works (cause it is last entry in the routing), but X-Accept-Version = 1.0 gives 404.

When I change the order of entries in routing the situation is reversed, the 1.0 works but 2.0 does not.

I think that this is problem with the same URI for both resources, but I may be wrong...

**Comment by xabbuh** [comment]
You can use the `@NamePrefix` annotation to prevent the generation of identical route names that would then overlap:

```php
namespace AppBundle\Controller\V1;

use FOS\RestBundle\Controller\Annotations\NamePrefix;
// ...

/**
 * @NamePrefix('product_v1_')
 */
class ProductController implements ClassResourceInterface
{
    // ...
}
```

**Comment by Ener-Getick** [comment]
Then I guess this should be closed @xabbuh @cve ?

**Comment by cve** [comment]
I will check If that works for 4 hours

**Comment by Ener-Getick** [comment]
ok thanks !

**Comment by cve** [comment]
It works, thanks.
