### ISSUE TITLE
Decrease the priority of the exception normalizer

### ISSUE THREAD

**Issue by xabbuh** [FriendsOfSymfony/FOSRestBundle#1488]
In #1358 we added a new `ExceptionNormalizer` which will be used to normalize exceptions with the Symfony Serializer component. However, one now has to register their own normalizers with a higher priority to make sure that they are executed before our normalizer which is a bit inconvenient. Thus, I suggest that we decrease the priority (let's say -10) of our listeners to make this a bit easier to customise (no need to specify a priority for custom normalizers).

**Comment by Ener-Getick** [comment]
:+1:

**Comment by xabbuh** [comment]
see #1489
