### ISSUE TITLE
Update UPGRADING-2.0 in relation to exception_wrapper_handler having been removed

### ISSUE THREAD

**Issue by angrygreenfrogs** [FriendsOfSymfony/FOSRestBundle#1495]
UPGRADING-2.0 currently states:

```
exception_wrapper_handler is now the name of a service and not the name of a class
```

However, in fact "exception_wrapper_handler" has been removed altogether and replaced with Serializer/Normalizer/ExceptionHandler and ExceptionNormalizer

I haven't totally figured out how to work with those yet, so be nice to add some docs about them as well, but I can definitely see that's what's happened.

**Comment by Ener-Getick** [comment]
:+1: Can you tell me if #1497 is clearer please?

**Comment by angrygreenfrogs** [comment]
Oh hey nice! thanks! that's a lot better.
