### ISSUE TITLE
allowBlank and nullable no longer work together as they did in 1.0

### ISSUE THREAD

**Issue by angrygreenfrogs** [FriendsOfSymfony/FOSRestBundle#1496]
Previously you could specify allowBlank=false and nullable=true, which would account for allowing the user to not specify an API parameter, but if they DO specify the parameter, that parameter cannot be blank.

Example:

```
* @RequestParam(name="token", requirements=".{1,200}", allowBlank=false, strict=true, nullable=true, description="User's token")
```

This worked correctly in 1.0 where `/api/call?token=` would throw an error, but `/api/call?` would be fine.

Now in 2.0, however, the above is throwing an exception when you do not specify the parameter at all.

"Parameter \"token\" of value \"\" violated a constraint \"This value should not be blank.\""

I think this is incorrect, because nullable was set to true, so the value should be allowed to be null. The parameter is incorrectly being flagged as blank, but it is in fact null since it was not included at all in the request.

**Comment by Ener-Getick** [comment]
Seems related to https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1425

**Comment by angrygreenfrogs** [comment]
Definitely in the same area, but this is an additional issue.

Under the covers the problem is that rest bundle is using the Symfony [NotBlank validator](http://symfony.com/doc/current/reference/constraints/NotBlank.html)

NotBlank also returns false if the value is null, so that means it's not really compatible with nullable any more. This must've been handled differently in 1.0 since it used to work.

I think there should be a check that if nullable=true and value=null, that should take precedence and allowblank should be ignored.

**Comment by Ener-Getick** [comment]
Well maybe in that case we can have our own ``NotBlank`` constraint and validator. Could you submit a PR ?

**Comment by nico-incubiq** [comment]
I am facing a similar issue.
My requirement is being check when I pass no parameter, although I set nullable=true.
This used to work before and I cannot find any way around this issue...

Here is my param:
`@REST\QueryParam(name="page", nullable=true, strict=true, requirements=@Assert\Range(min="1"), description="The page number")`

**Comment by AlmogBaku** [comment]
any update?

**Comment by xabbuh** [comment]
@AlmogBaku Would you like to submit a pull request?
