### ISSUE TITLE
Add a note to the UPGRADING instructions about using the JMS serializer exception handler

### ISSUE THREAD

**Issue by angrygreenfrogs** [FriendsOfSymfony/FOSRestBundle#1500]
There's a note already in there about "If you use the Symfony serializer", but it doesn't explain how to do it if you use the JMS serializer.

You guys can probably clean this up a bit, but here's a short example of how to add a JMS serializer exception handler.
1. Create a new ExceptionHandler class as a copy of https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.0/Serializer/Normalizer/ExceptionHandler.php
2. I called it `HttpExceptionHandler` in my example
3. Modify the namespace to your own, and the class header like:

```
namespace  ApiBundle\Serializer\Handler;
```

```
class HttpExceptionHandler extends \FOS\RestBundle\Serializer\Normalizer\AbstractExceptionNormalizer implements SubscribingHandlerInterface
```
1. Change the 'type' in getSubscribingMethods to the Exception class you wish to catch, for example:

```
'type' => \Symfony\Component\HttpKernel\Exception\HttpException::class,
```
1. Add it to your services and tag it as a JMS serializer subscribing handler
   services.yml:

```
    # JMS Serialization for HTTP Exceptions
    http_exception_handler:
        class:     ApiBundle\Serializer\Handler\HttpExceptionHandler
        tags:
        - { name: jms_serializer.subscribing_handler }
        arguments: ["@fos_rest.exception.messages_map", false]
```
1. Modify it as you wish, and whenever the chosen Exception is serialized it will be processed according to your handler

**Comment by Ener-Getick** [comment]
Maybe the best thing to do is to add a link to the jms doc ?

**Comment by Ener-Getick** [comment]
BTW we should probably add something about the fact that FOSRestBundle change in part the jms serializer behaviour (it allows simple handler inheritance).

**Comment by lbayerl** [comment]
I my case I had to overwrite the original ExceptionNormalizer like that in my services.yml:

`parameters:
     fos_rest.serializer.exception_normalizer.jms:
        class: Acquaim\ArcticBundle\EventHandler\JmsExceptionHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
        arguments: ["@fos_rest.exception.messages_map", false]`

**Comment by sela** [comment]
Is overwriting fos_rest.serializer.exception_normalizer.jms the only solution?

**Comment by Tobion** [comment]
Closing as it's too late to improve upgrade for 2.0. Btw you can also set `fos_rest:.exception.exception_controller` config and return whatever response you see fit. You don't even need to use the jms serializer for this.
