### ISSUE TITLE
maxDepth exclusion strategy is not work property

### ISSUE THREAD

**Issue by ghanbari** [FriendsOfSymfony/FOSRestBundle#1504]
i have 2 issue:
1. I set max depth by `setMaxDepth(3)` method, but it is not working, `@MaxDepth(1)` annotation overwrite this method, this method should ignore annotation, because developer expect 3 level set by method.

2. serializer check max depth after it run query, if i have a entity as:
```
Class Driver extends user
{
    /**
     * @var string
     *
     * @ORM\Column(name="mobile", type="string", length=11, unique=true)
     *
     * @Assert\NotBlank(groups={"Register", "Profile"})
     * @Assert\Regex(pattern="/09\d{9}/", groups={"Register", "Profile"})
     *
     * @JS\Groups({"DriverMobile", "Profile", "Admin"})
     * @JS\Since("1.0.0")
     */
    protected $mobile;

    /**
     * @var Car
     *
     * @ORM\OneToMany(targetEntity="FunPro\DriverBundle\Entity\Car", mappedBy="driver")
     *
     * @JS\Groups({"Cars", "Admin"})
     * @JS\MaxDepth(1)
     * @JS\Since("1.0.0")
     */
    private $cars;
.....
```
in method i get driver by:
```
$driver = $this->getDoctrine()->getRepository('Driver')->find($id);

$context = (new Context())
            ->addGroup('Admin')
            ->setMaxDepth(1);
        return $this->view($driver)->setSerializationContext($context);
```
when i hceck profiler, it run another query for driver's cars, and in the end, it apply maxDepth rule and show result:
```
      "mobile": "09674240600",
      "cars": [
        {}
      ],
```

**Comment by Ener-Getick** [comment]
This issue seems related to the JMS serializer not to this bundle.

**Comment by ghanbari** [comment]
`View::setSerializationContext()` get one instance of `FOS\\RestBundle\\Context\\ContextInterface`,
why this bundle use another context class?

**Comment by Ener-Getick** [comment]
We have our own Context class because we also support the symfony serializer so we needed to abstract the serializers we support.
And I didn't understand your 2nd question... do you have an example ?

**Comment by ghanbari** [comment]
@Ener-Getick Update post

**Comment by Ener-Getick** [comment]
The ``maxDepth`` attribute enables [the jms max depth checks](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.0/Serializer/JMSSerializerAdapter.php#L95), its value doesn't change anything (it does only for the symfony serializer).
I guess you can only use the ``@MaxDepth`` annotation.

**Comment by ghanbari** [comment]
@Ener-Getick thanks for help
what is `direction` in method signature?
what do [this code](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.0/Serializer/JMSSerializerAdapter.php#L78) ?, do it overwrite annotation?

**Comment by bassrock** [comment]
@GuilhemN So does the MaxDepth not work if you use the JMS Serializer?

**Comment by GuilhemN** [comment]
@bassrock it enables the max depth check, its value is not considered, that's how work the jms serializer.

**Comment by bassrock** [comment]
@GuilhemN So you have to use both MaxDepth checks? Or how can you get the value to be considered?

**Comment by ghanbari** [comment]
@bassrock if you want use jms serializer, you should define max level value by annotaion @MaxDepth(Y) and then enable max depth check for given response view by View::setMaxDepth(X) (X is ignored and Y is applied)
