### ISSUE TITLE
Disable 'method_prefix' globally

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSRestBundle#1507]
Is it possible to disable `method_prefix` globally?
I don't want to set it to `false` on each action.

http://symfony.com/doc/current/bundles/FOSRestBundle/7-manual-route-definition.html#method-name-prefix

**Comment by Ener-Getick** [comment]
This is not possible for now but it could be a great improvement :+1:

**Comment by xabbuh** [comment]
closing here as implemented in #1643
