### ISSUE TITLE
@View() and other annotations should work together

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSRestBundle#1509]
I cannot use `@View` and route annotations like `@Get` together.

Example: I want to get JSON output on `/api/category/{name}.json` and XML output on `/api/category/{name}.xml`. But I only get a normal response.

My code:

``` php
use FOS\RestBundle\Controller\Annotations as Rest;

class CategoryController extends FOSRestController
{
    /**
     * @Rest\Get("/api/category/{name}.{_format}", name="api_category", options={"method_prefix": false})
     * @Rest\View()
     */
    public function getCategoryAction($name)
    {
        return new Response('test');
    }
```

Btw: It would be much easier if I could just return `test` instead of a Response object.

It doesn't matter if I add `@Rest\View()` there.
If I write `return 'test';` it will result into an exception.

**Comment by JHGitty** [comment]
This code works fine:
```php
    /**
     * @Rest\Get("/api/category/{name}.{_format}", name="api_category", options={"method_prefix": false}, defaults={"_format": "json"})
     * @Rest\View()
     */
    public function getCategoryAction($name)
    {
        return $this->handleView(new View('test'));
    }
```

But it would be much better if I could use `@Rest\View()`.
It would also be nice if I don't need to specify the default for `_format` on each action.

**Comment by Ener-Getick** [comment]
@JHGitty did you enable the ``view_response_listener`` ?

With it, you can simply use:
```php
    /**
     * @Rest\Get("/api/category/{name}.{_format}", name="api_category", options={"method_prefix": false}, defaults={"_format": "json"})
     * @Rest\View()
     */
    public function getCategoryAction($name)
    {
        return 'test';
    }
```

**Comment by JHGitty** [comment]
Okay, that works fine. Is there any idea how to not always write the `_format` default and automatically add `.{_format}` to the route path?

**Comment by xabbuh** [comment]
@JHGitty Why do you define your route manually at all?

**Comment by Tobion** [comment]
Closing as the original problem has been solved.
