### ISSUE TITLE
Unable to dump configuration via console config:dump

### ISSUE THREAD

**Issue by hshn** [FriendsOfSymfony/FOSRestBundle#1511]
```bash
$ sf config:dump fos_rest

[LogicException]
No extensions with configuration available for "fos_rest"
```

**Comment by lsmith77** [comment]
are you sure the bundle is properly registered in your kernel .. or more importantly that you are running the CLI on the kernel you are assuming it runs against?

**Comment by lsmith77** [comment]
at any rate .. nothing in this Bundle could cause this issue, ie. it would be an issue in the FrameWorkBundle

**Comment by lsmith77** [comment]
aha .. interesting .. so if there is no configuration class .. then it gives this exception ..
