### ISSUE TITLE
Return form constraints to the client

### ISSUE THREAD

**Issue by hpatoio** [FriendsOfSymfony/FOSRestBundle#1514]
I've an endpoint the return a form definition. 

```
GET /events/{id}/contact-form

{
  "children": {
    "name": {
      "type": "text",
      "required": true,
      "label": "Name"
    },
    "email": {
      "type": "email",
      "required": true,
      "label": "Email Address"
    }
}
```
The form validations is dynamic so I would like to add the constraints definition for each field in the response so the client knows which validation add to each field (I have backend validation and I wont remove it. I want this only for a better UX)

I would like to have a response like

```
GET /events/{id}/contact-form

{
  "children": {
    "name": {
      "type": "text",
      "constraints": "mandatory",
      "required": true,
      "label": "Name"
    },
    "email": {
      "type": "email",
      "constraints": "mandatory, email",
      "required": true,
      "label": "Email Address"
    }
}
```

Is this possible ?

**Comment by Ener-Getick** [comment]
Of course, you should take a look at https://github.com/bichotll/FormValidationBundle which provides you a simple way to know which validations apply to a form.
You can transform its output as you want with a normalizer for example and you'll obtain what you want :)
