### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by lferro9000** [FriendsOfSymfony/FOSRestBundle#1515]
http://symfony.com/doc/master/bundles/FOSRestBundle/index.html

States that it is just a simple step:

composer require friendsofsymfony/rest-bundle

Then proceeds with "Just add a line in"

However, none of the stated files (ex. app/AppKernel.php) where created by the previous composer instalation, which can only mean that there are steps missing.

**Comment by xabbuh** [comment]
This sounds wird. The AppKernel class is part of the Symfony Standard Edition. How did you initially set up your application?

**Comment by lsmith77** [comment]
@lferro9000 I think you just installed this Bundle .. the documentation assumes without saying it, that you are adding this Bundle to a symfony full stack application.

@xabbuh maybe we should mention this as a pre-requisite

**Comment by Tobion** [comment]
Fixed by https://github.com/FriendsOfSymfony/FOSRestBundle/commit/e1f91266ca37e423dfae9ec4e641b247fdb2915d
