### ISSUE TITLE
InvalidConfigurationException with exception_wrapper_handler:  null

### ISSUE THREAD

**Issue by codereviewvideos** [FriendsOfSymfony/FOSRestBundle#1516]
Hi,

Firstly, thank you to everyone involved for creating, and supporting this bundle. It is awesome. 

I'm trying `"friendsofsymfony/rest-bundle": "^2.0@dev",`

Part of my config:

```
fos_rest:
    view:
        exception_wrapper_handler:  null
```

Which seems inline with the [configuration reference](http://symfony.com/doc/master/bundles/FOSRestBundle/configuration-reference.html).

But with this I get:

```
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "exception_wrapper_handler" under "fos_rest.view"
```

Removing the line from my config resolves the issue. 

I'm unsure where I'm going wrong with this - potentially just out of sync documentation?

Thanks

Chris

**Comment by Ener-Getick** [comment]
Indeed this option was removed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1358.
I propose a fix for the docs in #1517, thanks !
