### ISSUE TITLE
Custom Route Order

### ISSUE THREAD

**Issue by callistino** [FriendsOfSymfony/FOSRestBundle#1521]
I'm need of a custom route ordering/matching for my project and I can't find a way to do so. First I should say that we use singular resources so the pluralize option is set to false. My project uses multi-tenant accounts and a pure json api. An example of the generated routes will describe better my needs and goal.

```
cget_company                GET      ANY      ANY    /company
get_company                 GET      ANY      ANY    /company/{idCompany}
post_company                POST     ANY      ANY    /company
cget_company_org            GET      ANY      ANY    /company/org
get_company_org             GET      ANY      ANY    /company/{idCompany}/org/{idOrg}
post_company_org            POST     ANY      ANY    /company/org
```

As you can see, I have a need to get all orgs via `/company/org` but that route is preceded in order by the route `get_company:/company/{idCompany}`. Is there a way to override this order? I don't see anything in the documentation. If there is, please point me in the right direction. 

thanks,

**Comment by Ener-Getick** [comment]
This issue was reported [here](https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1393) as well.
For now the only solution you have is to declare the method including keywords in their route before the others.

**Comment by callistino** [comment]
I was able to overcome this issue by generating more routes using a class that overloads the `\FOS\RestBundle\Routing\Loader\RestYamlCollectionLoader:load()` and sorting the routes in an order that fits my needs.
