### ISSUE TITLE
Sensio's framework-extra-bundle: outdated dependency with 1.8

### ISSUE THREAD

**Issue by lbayerl** [FriendsOfSymfony/FOSRestBundle#1532]
Tried to upgrade FOS Rest from 1.7.7 to 1.8 (to prepare the upgrade to 2.0 as suggested).
One potential issue that I found is that while upgrading with composer update sensio/framework-extra-bundle got downgraded from 3.0.16 to 3.0.12.
Is that some dependency issue with FOS Rest or is it on purpose?

This is the line within composer.json from 1.8:
"sensio/framework-extra-bundle": "~2.0|~3.0,<3.0.13",

**Comment by Ener-Getick** [comment]
This is not a bug, the 1.x releases of fosrestbundle aren't compatible with sensioframeworkextrabundle 3.0.13 and higher.
To upgrade the sensio bundle, you must upgrade fosrestbundle to 2.0.

**Comment by lbayerl** [comment]
Thanks @Ener-Getick for making this clear. I am just wondering a bit, because I already had FOS Rest 1.7.7 running with framework-extra 3.0.16. So was this a bug then which was fixed with 1.8? Because I got a downgrade for framework-extra when upgrading from 1.7.7 to 1.8?

**Comment by stof** [comment]
@lbayerl the older version of FOSRestBundle was not compatible either, but it was not telling Composer about it
