### ISSUE TITLE
ParamFetcher can't fetch file arrays

### ISSUE THREAD

**Issue by muffe** [FriendsOfSymfony/FOSRestBundle#1535]
I've got a REST function, where I have an image upload as a POST parameter, that looks something like this

``` php
 * @FileParam(name="image-data", strict=false)
 * @View()
 */
 public function postSubmitAction(Request $request, ParamFetcher $paramFetcher)
```

I'm uploading an array of images at the "image-data" key with the [] notation, therefore "image-data[]".
If i try to read the POST data with `$request->files->get('image-data')` I get an array of UploadedFile objects.

If I do the same with `$paramFetcher->get('image-data')` it returns null.

**Comment by Ener-Getick** [comment]
We should probably move ``$map`` from ``AbstractScalarParam`` to ``AbstractParam``.
This would need a new test to ensure this works as expected. Can you work on that @muffe ?

**Comment by muffe** [comment]
I just have taken a look at what the actual problem is.

The `getConstraints` method of the FileParam Annotation looks like this
```
if ($this->image) {
    $constraints[] = new Constraints\Image($options);
} else {
    $constraints[] = new Constraints\File($options);
}
```
In both cases the validation is obviously failing because we get an array as return value.

I just talked with @xabbuh about two possible ways of fixing this.

1. - my way.

We add a new configuration flag to the FileParam Annotation called `multiple`. If this is true we use the Collection constraint.

2. - the @xabbuh way.

In the configuration of the name field of the FileParam we append `[]` to the actual name (so image-data[] instead of image-data[]) to indicate that we want to receive multiple values. While retrieving the value from the actual FileBag we would have the remove the `[]`again.

In both cases we would have to filter the array in some way because we could have potential NULL values.

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1474
