### ISSUE TITLE
Renaming array to map incompatibilities

### ISSUE THREAD

**Issue by okdewit** [FriendsOfSymfony/FOSRestBundle#1544]
I just upgraded an old project from FOSRestBundle 1.7 to 2.0.

When replacing array=true with map=true in a parameter which is an array:

    * @REST\RequestParam(map=true, name="images", description="Images", nullable=true)

I get the following Symfony error:

    The options "constraints" must be set for constraint Symfony\Component\Validator\Constraints\All

The images parameter is an array, with each image item containing various keys like filename, content, width, height, etc. In FOSRestBundle 1.7, when one of our customers didn't include images (nullable=true), it would be an empty array.

Also, the UPGRADING-2.0.MD tells me that array was renamed to "map", but the annotation reference (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.0/Resources/doc/annotations-reference.rst) still uses "array".

**Comment by gatmanmihai** [comment]
until it is not fixed, try to use instead of `nullable=true` this `default={}`

Before
`* @REST\RequestParam(map=true, name="images", description="Images", nullable=true)`

After
`* @REST\RequestParam(map=true, name="images", description="Images", default={})`

**Comment by Ener-Getick** [comment]
This was fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1405.
Thanks for the report !
