### ISSUE TITLE
Query param array validation: array to string conversion error

### ISSUE THREAD

**Issue by senkal** [FriendsOfSymfony/FOSRestBundle#1546]
Hello,
I followed the conversation about array to map changes and some logic to validate types for array keys.
What I want to achieve is really similar to what is in the docs:
```
     * @QueryParam(map=true, name="filters", requirements=@MyComplexConstraint, description="List of complex filters")
     * In this example, the ParamFetcher will validate each value of the array with the constraint, returning the
     * default value if you are in safe mode or throw a BadRequestHttpResponse containing the constraint violation
     * messages in the message.
```
http://symfony.com/doc/master/bundles/FOSRestBundle/param_fetcher_listener.html
But without the `map=true` to get parameters in validator once, as an array with keys

My setup is like this:
```
     * @QueryParam(
     *     name="page",
     *     strict=true,
     *     nullable=true,
     *     requirements=@MyCustomValidatorConstraint
     *     )
```
Following comment:
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1192#issuecomment-156176789
I get an array with keys in custom Validator.
Works fine until I add any violation:
  `$this->context->addViolation('Error message');`
or following Symfony docs way:
```
$this->context->buildViolation('error message')
                ->setParameter('%string%', $value)
                ->addViolation();
``` 
Adding violations in that custom validator ends up with:
```
[2016-07-29 17:18:53] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Array to string conversion" at /{...}/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php line 47 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Array to string conversion at /{...}/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php:47)"} []
```
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Exception/InvalidParameterException.php#L45
`$violation->getInvalidValue()` return array of filters, not a string.

Do I miss anything and should configure something to make this work?
Looks I need to set invalid value just don't see a way to do it.

PS.
fos-rest bundle 2.0.0

For now I use not great hacks to make it working.
I use map=true and, based on property path in context inside custom validator, try to find which key I am checking now to know which validation rule to apply.

**Comment by Ener-Getick** [comment]
I propose to use the VarDumper of symfony to print the invalid value. Could you submit a pr ?

**Comment by senkal** [comment]
@Ener-Getick sure, will do.
Do you want to use VarDumper all the time(even for string) or just when the invalid value is not scalar?

**Comment by Ener-Getick** [comment]
I'd say only when not scalar, for bc :)

**Comment by senkal** [comment]
I am not sure from which branch should I create the PR, 2.0 or master?
Do you have any contribute guide?

**Comment by Ener-Getick** [comment]
It looks like we don't :/ but we follow symfony practices.
I'd say let's do that on master as it is a consequent change.

**Comment by senkal** [comment]
Just to be sure, I will need to add this dependency.
I don't see Symfony var-dumper inside composer.
Then just call `dump()` or use some more advanced formatting?
Maybe just `var_export` will be fine, looks like a lot of hassle to just dump a variable.

**Comment by Ener-Getick** [comment]
Yes could be fine as well, i'm not even sure we need to include the invalid value in the exception message.

**Comment by senkal** [comment]
In the end, the best way to format exception message is to catch the right Exception class and do the formatting on your own, using Symfony Violation list for example.
Here is just- do not break the app when using the use case I covered, simple var_export is fine probably.

Will do it.
