### ISSUE TITLE
404 Not Found in Prod environnement

### ISSUE THREAD

**Issue by NadaBen** [FriendsOfSymfony/FOSRestBundle#1552]
Hello,
I can access http:/localhost/app_dev.php (dev environment)

However, when I try to access the prod environment:
http:/localhost/app.php

it works with all routes, except routes of FOSRestBundle

I get the following error message
**404 Not Found**

I tried with
**php app/console cache:warmup --env=prod --no-debug**

but the same error with routes of my rest api ..

my routing parameters for the api controller is as following:

```
vcycle_api:
    type:     rest
    resource: VCycle\PhotosBundle\Controller\VCycleApiController
    prefix:   /v1
    options: { i18n: false }
```

an example of the api request:

```
     /**
     * @ApiDoc(
     * description="Deletes tags by they titles.",
     * resource=true,
     * resourceDescription="Deletes tags by they titles."
     * )
     *
     * @Rest\Delete("/tags")
     * @Rest\RequestParam(name="tags", requirements=".+", map=true, allowBlank=false, description="Tags titles for deletion.")
     * @Rest\QueryParam(name="access_token", description="OAuth Access_Token.")
     * @Rest\View()
     */
    public function deleteTagsAction(array $tags)
    {
        $em = $this->getDoctrine()->getManager();

        $tags = $em->getRepository('VCycleTagsBundle:Tag')->findBy(array('title' => $tags));
        foreach ($tags as $tag) {
            $em->remove($tag);
        }

        $em->flush();

        return array('status' => 'success, tags deletes');
    }
```

**Comment by Ener-Getick** [comment]
Can you try running `bin/console debug:router`?
In case you can't fix that yourself, we're gonna need more information such as your config, the URL you called, your routing, anything that might be useful.

**Comment by NadaBen** [comment]
It exists in routes .. i verified with bin/console debug:router

**Comment by snebes** [comment]
Did you verify that the routes are in prod, too?
`php app/console debug:rout --env prod`

**Comment by payene** [comment]
I have the same problem. In my case the route is available also in production .  
Any suggestions ?

**Comment by xabbuh** [comment]
Without more information (the best would be a reproducable application) we won't be able to help you.

**Comment by payene** [comment]
All right ! i just clear the cache and it works !
