### ISSUE TITLE
It is not possible to define route manually without "Action" suffix in controller method name

### ISSUE THREAD

**Issue by warlock39** [FriendsOfSymfony/FOSRestBundle#1569]
Actually, it is normal behaviour for `RestActionReader`, but [**documentation**](http://symfony.com/doc/current/bundles/FOSRestBundle/7-manual-route-definition.html#method-name-prefix) in this case confuses developers to use manual definition of routes. Example demonstrates following snippet: `public function getUsers() { /** */ }`, but without `Action` suffix it will not work according to this condition [Routing/Loader/Reader/RestActionReader.php#L430](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L430)

How to update documentation for this component?

**Comment by lsmith77** [comment]
documentation is here https://github.com/FriendsOfSymfony/FOSRestBundle/tree/master/Resources/doc
