### ISSUE TITLE
Handler Registry / recursive parent loop

### ISSUE THREAD

**Issue by temp** [FriendsOfSymfony/FOSRestBundle#1572]
What's the reason for the overridden getHandler() method inside the JMSHandlerRegistry?
It completely breaks my custom handler for custom type resolving...
Would it be possible to make this optional? Maybe the handler could opt-out via an interface?
As far as I can see there is no possibility to not have a handler for sub-classes.
When I restore the old functionality (no parent-traversal) everything works fine.

**Comment by Ener-Getick** [comment]
It is here to manage any instance of Exception. We can of course replace it if you have a better solution ?

**Comment by temp** [comment]
Not really. I found a solution for my problem.
But it should be stated somewhere, that this changes default serializer-bevaviour.
