### ISSUE TITLE
System parameters cannot be used as requirements on a QueryParam annotation

### ISSUE THREAD

**Issue by aaronahearne** [FriendsOfSymfony/FOSRestBundle#1575]
The following code does not work when a 'my_regex' parameter is listed in the parameters.yml file. Stepping through the code, this seems to be because the code sees this as class Fos\RestBundle\Validator\Constraints\Regex, which does not implement the ResolvableConstraintInterface. This happens even when my_regex is set to a simple string like 'test'

`* @QueryParam(name="departureTime", requirements="%my_regex%", strict=true, nullable=false)`

**Comment by Ener-Getick** [comment]
It looks like we forgot to implement this interface.
Could you submit a pr doing that + testing it ?

**Comment by aaronahearne** [comment]
Will do

**Comment by xabbuh** [comment]
@aaronahearne Can you please check if #1591 fixes this issue for you?
