### ISSUE TITLE
ExceptionWrapper Status Codes being ignored

### ISSUE THREAD

**Issue by ChristianVermeulen** [FriendsOfSymfony/FOSRestBundle#1580]
Hi,

We are trying to wrap exceptions manually because we want to add more data to the exception besides the `status_code`, `message` and `errors`. So we have created our own `ExceptionWrapperHandler`.

At first it would spit out an array with our data, but this caused it to always return a `500` code in de headers. So then we tried returning an `ExceptionWrapper` with

```
$exceptionData = [
            'status_code' => 400,
            'message' => 'myMessage,
            'other' => 'values'
        ];

return new ExceptionWrapper($exceptionData);
```

However, though the exception is serialized into json and holds code=400, the headers still pass a 500 internal server error. So it seems that FosRest is not taking into account the actual status codes.

The second, less urgent, problem is that we can't seem to add the extra fields to serialisation. We've set the config as described in the docs but it just won't serialise those extra fields.:
![screenshot 2016-09-22 11 57 54](https://cloud.githubusercontent.com/assets/1062751/18744474/740f2800-80be-11e6-8474-b6e351ad66d2.png)

We do use JMS serialiser, so we've pretty much copied the above example.

**Comment by Ener-Getick** [comment]
@ChristianVermeulen to have a more flexible implementation, you should use 2.0, it is using directly the serializer normalizers.

**Comment by ChristianVermeulen** [comment]
@Ener-Getick I just upgraded to 2.0 and created a handler for JmsSerializer but it is still not picking up the status code.. In my serialisation method I create an array and pass it on to the visitor:

```
// Format and return desired message
$response = [
    'status_code' => $customException->getStatusCode(),
    'message' => $customException->getMessage(),
    'type' => $customException->getMessageType(),
    'baseExceptionClass' => $customException->getBaseExceptionClass()
];

$visitor->visitArray($response, $type, $context);
```

The output I get in the body is a nice json, but the actual http status code is **still** 500 instead of the one I've set (400):

<img width="1152" alt="screenshot 2016-09-30 15 46 21" src="https://cloud.githubusercontent.com/assets/1062751/18993764/14ddeebc-8725-11e6-9cdc-327ab1bf5a68.png">

How do I get FosRestBundle to pickup the `status_code` from my exceptions just as it does with `HttpException`'s?

**Comment by Ener-Getick** [comment]
This is managed [in the config](http://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html). You have to define `fos_rest.exception.codes`.

**Comment by ChristianVermeulen** [comment]
But this means I need to config every exception we make / throw hardcoded... That is not a viable option. We need it to be dynamic. This list of exceptions can grow fairly quickly in a moderate sized API! It will turn into a very unmaintainable list...

**Comment by Ener-Getick** [comment]
@ChristianVermeulen as your exceptions extend `HttpException` they should already be managed. Can you check if [this part of the code](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/ExceptionController.php#L109) is executed?
