### ISSUE TITLE
x-http-method-override and bodylistener

### ISSUE THREAD

**Issue by cyrilchapon** [FriendsOfSymfony/FOSRestBundle#1581]
[This part](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/c1b87d933dfc9b59fc603f8e44f8064e4530a2b1/EventListener/BodyListener.php#L154-L161) of bodylistener code doesn't not accept `x-http-method-override`, while the routing part of the rest-bundle doest accepts it (IE: I'm falling inside my "getBlabla" function, but json is not decoded, when I send a POST with x-http-method-override to GET)

I think this is a little inconsistent.

**Comment by Ener-Getick** [comment]
[This part is managed by symfony itself.](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1278-L1284)
The `X-HTTP-METHOD-OVERRIDE` header is only allowed when using `POST`, you can't use it with `GET`.

BTW if possible don't use this trick, it may create security issues.

**Comment by cyrilchapon** [comment]
Oh realy ? Didn't know that.
Any reference ? Thanks for information :)

**Comment by Ener-Getick** [comment]
That's described in the phpdoc of the method linked above.
