### ISSUE TITLE
Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is…option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0.

### ISSUE THREAD

**Issue by alanhartless** [FriendsOfSymfony/FOSRestBundle#1586]
This is filling up my logs and related to https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/config/forms.xml#L10 which has a note about < 2.8. 

```
Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is…option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0.
```

But is there something we can do to prevent this error? I'd rather not globally disable deprecation logging.

**Comment by Ener-Getick** [comment]
I don't think we can do anything except advising you to upgrade to 3.0.

**Comment by xabbuh** [comment]
We could add the text inside the DI extension instead of here. This way we could select the tag attributes based on the installed version of the Form component.

**Comment by Ener-Getick** [comment]
@xabbuh indeed, it shouldn't be hard i'll try to remember to do it tomorrow unless someone already submited a pr.

**Comment by xabbuh** [comment]
see #1598

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1598.
