### ISSUE TITLE
Fatal error after upgrade to 2.1.0 version  (Symfony 2.8)

### ISSUE THREAD

**Issue by adam-bernau** [FriendsOfSymfony/FOSRestBundle#1588]
`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must be an instance of FOS\RestBundle\View\ViewHandlerInterface, none given,`

**Comment by Ener-Getick** [comment]
I guess you reference this controller in your own code and you didn't change this reference by the service name or you didn't change its building arguments.
Without more informations, it looks like this is related to your code.
