### ISSUE TITLE
Broken code after upgrading willdurand/negotiation dependency

### ISSUE THREAD

**Issue by edefimov** [FriendsOfSymfony/FOSRestBundle#1593]
After updating willdurand/negotiation dependency to version 2.2.0 via `composer update` FOSRestBundle fails with syntax error

`
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                          
  Warning: Declaration of FOS\RestBundle\Negotiation\FormatNegotiator::getBest($header, array $priorities = Array) should be compatible with Negotiation\AbstractNegotiator::getBest($header, array $priorities, $strict = false)
`

**Comment by willdurand** [comment]
Argh. I knew it.. Sorry for this, I am going to revert the change and publish a fix right away.

**Comment by xabbuh** [comment]
Thank you for reporting this issue @edefimov. However, I am closing here as this will be fixed by willdurand/Negotiation#87.

**Comment by willdurand** [comment]
This is now fixed in [Negotiation 2.2.1](https://github.com/willdurand/Negotiation/releases/tag/v2.2.1). @edefimov could you please confirm?

**Comment by edefimov** [comment]
Yes, thanks 2.2.1 works well. I suggest to add this into composer.json:
```json
    "conflict": {
        "willdurand/negotiation": "2.2.0"
    },
```

**Comment by xabbuh** [comment]
Imo that's not really necessary. Noone should use a version constraint that is so restrictive in that it only allows 2.2.0, but denies 2.2.1. The thing is that each conflict rule we add will add more workload to Composer's solver without much added benefit imo.

@lsmith77 @Ener-Getick What do you think?

**Comment by willdurand** [comment]
I don't think it is worth adding a conflict either. We don't do that for other bug fixes.

**Comment by Ener-Getick** [comment]
I agree i don't think we need to add a conflict either :)
