### ISSUE TITLE
`jms_serializer.form_error_handler.class` parameter from `serializer.xml` is not used

### ISSUE THREAD

**Issue by dstotijn** [FriendsOfSymfony/FOSRestBundle#1600]
In `Resources/config/serializer.xml` of this bundle, the parameter `jms_serializer.form_error_handler.class` is overridden to `FOS\RestBundle\Serializer\Normalizer\FormErrorHandler`. However, when I test with returning a form with errors from a controller, instead the serialized output from the default `JMS\Serializer\Handler\FormErrorHandler` class is seen in the HTTP response body. It seems the override of the parameter in `serializer.xml` has no effect.

I can only get the desired result by putting this in my app's `parameters.yml`:

    parameters:
        jms_serializer.form_error_handler.class: FOS\RestBundle\Serializer\Normalizer\FormErrorHandler

After I define the above parameter, I get the desired result, e.g. I see the form errors are serialized by `FOS\RestBundle\Serializer\Normalizer\FormErrorHandler` with `code`, `message` and `errors` keys, as seen in the [docs](https://symfony.com/doc/master/bundles/FOSRestBundle/2-the-view-layer.html#forms-and-views).

Am I missing something or is this a bug? Any help is appreciated. Thanks! :)

Note: I'm using version `2.1.0` of `friendsofsymfony/rest-bundle`, and version `1.1.0` of `jms/serializer-bundle`.

**Comment by xabbuh** [comment]
In what or do you enable the FOSRestBundle and JMSSerializerBundle in the kernel class?

**Comment by dstotijn** [comment]
@xabbuh: I've enabled FOSRestBundle and JMSSerializerBundle in `app/AppKernel.php` like described in step "B" [here](https://symfony.com/doc/master/bundles/FOSRestBundle/1-setting_up_the_bundle.html).

**Comment by dstotijn** [comment]
@xabbuh: OK, just found out what I did wrong: I put FOSRestBundle before JMSSerializer in the array I return in `\AppKernel::registerBundles`. If I reverse them, everything works like expected, without me having to override the parameter myself. Was banging my head on this one ;)
Thanks!

**Comment by ddeboer** [comment]
Ran into this as well. Adding this to the docs in #1651.
