### ISSUE TITLE
Change priority of DisableCSRFExtension to make it compatible with Symfony 3.2

### ISSUE THREAD

**Issue by daFish** [FriendsOfSymfony/FOSRestBundle#1602]
Hi.

I was testing an app with Symfony 3.2 Beta and encountered the following issue like @romainneutron pointed out in [symfony/symfony#20332](https://github.com/symfony/symfony/issues/20332). I'd suggest to change the priority of the extension in order to avoid having this issue once more people are updating their apps to Symfony 3.2.

**Comment by Ener-Getick** [comment]
I'm not against that but as I don't use much symfony forms I can't tell if that's the right solution. Do you know what caused this?

**Comment by daFish** [comment]
@GuilhemN I'm not quite sure but I suspect it might be related to [symfony/symfony#19790](https://github.com/symfony/symfony/pull/19790).
The used Trait sorts the fetched extensions causing the issue I describe.

**Comment by GuilhemN** [comment]
I investigated a bit and I didn't find what could cause this issue in the PR you linked :/
Would you mind reverting it locally on your repository and see if this issue still happen ?

**Comment by daFish** [comment]
@GuilhemN I just tried it and reverting the PR solves the problem. So, I'd go and open a PR to add the priority for the listener. Or should we go another route for solving the problem?

**Comment by GuilhemN** [comment]
It may be a symfony issue but adding a priority on our side to fix it looks good to me.

**Comment by GuilhemN** [comment]
Fixed in https://github.com/symfony/symfony/pull/20995.
