### ISSUE TITLE
Body Converter with Custom Validator

### ISSUE THREAD

**Issue by njaw** [FriendsOfSymfony/FOSRestBundle#1603]
Just wondering if there is a way to define a custom validator when using the body_converter. I am developing an application not using ORM and would like to define the validator when a request is made. I would like to do something like this:

```
/**
* @ParamConverter("post", converter="fos_rest.body_converter" validator="my_custom_post_validator")
*/

public function putPostAction(Post $post, ConstraintViolationListInterface $validationErrors)

```

Is this possible to do? I could not find anything specific in the documentation.

**Comment by Ener-Getick** [comment]
You can use your own validator for FOSRestBundle services using [its configuration](https://symfony.com/doc/master/bundles/FOSRestBundle/configuration-reference.html) (e.g. `fos_rest.service.validator`) but I'm not sure that's what you want.

If you only want to use validation without an ORM, you can use [symfony's annotations](https://symfony.com/doc/current/validation.html) or configuration files.
