### ISSUE TITLE
Versioning with path parameter doesn't set exclusion strategy version

### ISSUE THREAD

**Issue by TobiasXy** [FriendsOfSymfony/FOSRestBundle#1604]
Currently I'm setting up versioning for my Rest API which is already using this bundle (and the Symfony Serializer).

I need the requested version in my serializer, because the Controller only returns an entity, but depending on the requested version it should be normalized with a different representation.

If I provide the version through a query string parameter or a header it works fine and I can access the version within the normalizer using `$context['version']`. If I set the version as a path parameter (like `GET /v1/some/entity/123`) it isn't available in the $context variable (i.e. it is the default version), but it is set in the `$request->attributes` parameter bag as expected.

Now after reading a bit through the code the reason seems to be:
For versioning using a query string parameter or a header, the VersionListener

1.  uses a VersionResolver to get the requested version from the request
2.  sets the "version" request attribute
3.  calls the `setExclusionStrategyVersion` method of the ViewHandler

Now for a version parameter in the path, there is no VersionResolver. This is not a problem if you only need the version in the controller, since symfony itself sets the "version" request attribute, but in the Serializer you only get the default version, because of that.

If this is considered to be working as intended for some reason just close this issue and I would write a custom EventListener to do this for me. Otherwise I could create a pull request to fix that.

**Comment by xabbuh** [comment]
This indeed looks like an issue to me. I suggest to split the `VersionListener` to fix this bug. The existing `VersionListener` should only be responsible to set the `version` request attribute when necessary. We can then introduce a new event listener that is executed after the `VersionListener` and sets the view handler's exclusion strategy version based on the request's version attribute (if set).

**Comment by GuilhemN** [comment]
@xabbuh what about adding a `RequestAttributeVersionResolver` instead?

**Comment by xabbuh** [comment]
@GuilhemN But we actually do not need to resolve the attribute anymore. We get that for free thanks to the Symfony routing system. So I don't think we should add this resolver at all.

**Comment by GuilhemN** [comment]
Then maybe we could do in the same listener (at the end):
```php
if ($request->attributes->has('version') && $this->viewHandler instanceof ConfigurableViewHandlerInterface) {
    $this->viewHandler->setExclusionStrategyVersion($request->attributes->get('version'));
}
```
?

**Comment by xabbuh** [comment]
That would work too.

**Comment by GuilhemN** [comment]
It's just I think having a new listener is overkill but if you think it's worth it, we can create it.
