### ISSUE TITLE
Supporting several FOSRestBundle versions

### ISSUE THREAD

**Issue by greg0ire** [FriendsOfSymfony/FOSRestBundle#1607]
Recently, a strong accent has been put on BC when developing Sonata bundle. To help users migrate easily from the current generation to the next, it has been decided to support 2 versions of the fos rest bundle. The problem is sonata is using annotations like `QueryParam`, and annotations are by nature not dynamic (and should therefore be avoided in this context IMO). What are the alternatives? How can I dynamically add a query parameter to an action using `array` or `map` when appropriate? See [this discussion](https://github.com/sonata-project/SonataUserBundle/commit/4b6e29540eab072e40535386050cef5a5c68e960#commitcomment-19809506) for more context. cc @lemorragia @xabbuh

**Comment by GuilhemN** [comment]
Maybe that's gonna look hacky, but you could have your own annotation:
```
/**
  * @Annotation
  */
class Annotation extends QueryParam
{
    public $array = false;

    public function getConstraints(...)
    {
         if (property_exists($this, 'map')) {
             $this->map = $this->array;
         }

         return parent::getConstraints(...);
    }
}
```
Then you'll be able to use `array` for 1.x and 2.x.

Or maybe better, you could have your own annotation harcoding both `array` and `map` to true.

**Comment by greg0ire** [comment]
> Maybe that's gonna look hacky

Yeah, a bit :laughing: … but that's an idea.

 I think there must be some kind of thing that reads annotations, then calls some method on a class to register the parameters. Not sure how it works, but maybe you do? I was hoping it was not tightly coupled with annotations.

I was wondering if [this method](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Request/ParamFetcher.php#L77) is the one I should call to add parameters programmatically. If yes I think the way to go would be to implement `ParamReaderInterface` myself… is that right?

If yes, maybe there is a design problem here (or a naming problem). IMHO, the `FOSRestBundle\Controller\Annotations` namespace would be better of if the `Annotations` was replaced with something not tied to a particular driver. But that's a wider problem I guess.

**Comment by GuilhemN** [comment]
> I was wondering if this method is the one I should call to add parameters programmatically. If yes I think the way to go would be to implement ParamReaderInterface myself… is that right? 

>If yes, maybe there is a design problem here (or a naming problem). IMHO, the FOSRestBundle\Controller\Annotations namespace would be better of if the Annotations was replaced with something not tied to a particular driver. But that's a wider problem I guess. 

Our annotations implement `ParamInterface` but a param doesn't need to be an annotation, it's just convenient. You can add parameters using `addParameter` if you don't want to use an annotation of course (btw you could extend `QueryParam` and fill its properties as you need in the constructor and then inject the parameter dynamically).

>I think there must be some kind of thing that reads annotations, then calls some method on a class to register the parameters. Not sure how it works, but maybe you do? I was hoping it was not tightly coupled with annotations. 

From what i know doctrine injects values directly in the annotation (that's why parameters are `public`) that's why it's really hard to provide a smooth path for annotations.

That's where my second suggestion could look better, you would only have to replace `QueryParam default values:
```php
/**
  * @Annotation
 */
class MyQueryParam extends QueryParam
{
    public $array = true;
    public $map = true;
}
```
However i'm not sure php wouldn't complain about a value conflict with the parent.

**Comment by greg0ire** [comment]
> You can add parameters using addParameter if you don't want to use an annotation of course (btw you could extend QueryParam and fill its properties as you need in the constructor and then inject the parameter dynamically).

I'm indeed quite reluctant to use an annotation. I think these are great when you write something in RAD mode, but if you need flexibility like a library does, you shouldn't use annotations IMO : 

- They're by nature not dynamic.
- They annotate something, which means they are very tightly coupled to it.

I know maintaining things is hard, so I'm not suggesting FOSRest should support XML or YAML for this, but I think it should support php for this. Maybe it already does, if yes I'll probably contribute a documentation article to show how to do this.

> From what i know doctrine injects values directly in the annotation (that's why parameters are public) and that's why it's really hard to provide a smooth path for annotations.

I think this happens [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Request/ParamReader.php#L58), so maybe I just need to write an implementation of `ParamReaderInterface` that will just return a hardcoded array of annotations. It will feel weird because I won't be using annotation at all, that's why I suggested there's probably a problem with the `Annotations` namespace. IMO, it should be `Metadata`, just like in doctrine. If I can do that, I'll just need to figure out how to use my implementation of instead of the other one. Otherwise I'll probably do what you suggest.

**Comment by GuilhemN** [comment]
> IMO, it should be Metadata, just like in doctrine.

This is doable, however i'm not sure that's worth it.

> I know maintaining things is hard, so I'm not suggesting FOSRest should support XML or YAML for this, but I think it should support php for this.

Using php is already possible, just not very user friendly.

```php
$param = new QueryParam();
$param->array = true;
$paramFetcher->addParam($param);

**Comment by greg0ire** [comment]
> This is doable, however i'm not sure that's worth it.

At the moment it probably isn't but, it might be a good thing to keep it mind if the library evolves towards more flexibility one day.

> Using php is already possible, just not very user friendly.

I'll try that and keep you posted. In the meantime, I'm going to close this, there is no need to keep it open IMO.
