### ISSUE TITLE
[Routing] unsupported keys "name_prefix", "parent"

### ISSUE THREAD

**Issue by havvg** [FriendsOfSymfony/FOSRestBundle#1615]
The documentation at http://symfony.com/doc/master/bundles/FOSRestBundle/6-automatic-route-generation_multiple-restful-controllers.html shows examples of providing `name_prefix` & `parent` options on routes. However when defining them, I receive the following exception on Symfony `v3.1.5`

> [InvalidArgumentException]
  The routing file "[...]/app/config/environments/dev/routing.yml" contains unsupported keys for "api_faq_topic": "name_prefix", "parent". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition".

It's not the combination, I can use any of it and it won't work.
Are the docs up-to-date or did I just miss something to configure?

**Comment by xabbuh** [comment]
Did you put the routes containing options specific to FOSRestBundle in a separate file and then loaded that file with the `type: rest` option?

**Comment by havvg** [comment]
I have them in separate files and importing a `type: directory` with `*.yml` in it having `type: rest` defined.

I just tried your suggestion and it seems to work. So the issue is the directory definition using multiple files? Is there a way I do not need to add the definitions all over, when adding new routes?

**Comment by xabbuh** [comment]
Unfortunately, I don't think there is another solution currently.

@GuilhemN @lsmith77 I could imagine that we make it possible to let the `DirectoryRouteLoader` load a bunch of configuration files (be it PHP, XML, or YAML) from a directory too (or write a dedicated loader for that). What do you think?

**Comment by GuilhemN** [comment]
@xabbuh I'd go for a separate loader like [what does symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/DirectoryLoader.php) with the `rest-directory` type. But that would need some work, so do we really want to support this case? It looks very unusual to me.

**Comment by xabbuh** [comment]
Not sure how common this is. I usually stick with annotations. However, adding a new loader should not really hurt if someone is willing to provide a pull request.

**Comment by GuilhemN** [comment]
Sure, let's see if someone is interested then.

**Comment by kubaceg** [comment]
Hi, I also had a problem with `name_prefix`, which is supplied in documentation, and because of that I think it's good idea to fix it.

On the other side IMHO routes prefixing by controller name should be default behaviour. And I there is PR providing such functionality https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1759.

**Comment by Tobion** [comment]
Closing as the underlying issue to load non-annotated routes from a directory is a new feature that has not been requested further. Btw, about the custom option name_prefix, this is now part of symfony itself: https://symfony.com/blog/new-in-symfony-4-1-prefix-imported-route-names
