### ISSUE TITLE
[Documentation][fr] French documentation

### ISSUE THREAD

**Issue by Abam** [FriendsOfSymfony/FOSRestBundle#1616]
Hi,

Since Symfony 3 official documentation doesn't support frecnh anymore, I've found out a well written documentation explaining FOSRestBundle in french [Créez une API REST avec Symfony 3](https://zestedesavoir.com/contenus/1280/creez-une-api-rest-avec-symfony-3/). 
It's a good starting point for beginners.

It would be nice to have a list of references (links, ebook, ...) in the readme that you consider helpful for beginners.

**Comment by GuilhemN** [comment]
I agree about referencing useful articles, however i don't think we need to do it in several languages, english is very common and it will be likely that one article in french for example won't explain the same thing than an english article.

**Comment by Tobion** [comment]
Closing as the linked article does not seem to be available anymore, or at least not publicly. Also localized docs will not be part of the rest-bundle as it's impossible to maintain.
