### ISSUE TITLE
Use FOSRestBundle in existing table

### ISSUE THREAD

**Issue by danitome24** [FriendsOfSymfony/FOSRestBundle#1619]
Hi,

I have an existing table called users_web with fields user (username), email, password... And I want to use FOSRestBundle with existing mapping. How to handle it?

Thanks!

**Comment by jorge07** [comment]
Sounds like wrong repo, try in [FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle). Rest does not related with user...

**Comment by xabbuh** [comment]
Closing as this indeed looks it was posted on the wrong repository.
