### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by bpolaszek** [FriendsOfSymfony/FOSRestBundle#1635]
Hi there,

I'd like to install a bundle which relies on FOSRestBundle ^1.8, though 2.0 is my actual installed version.
In order to know if a downgrade is possible, I'd like to check what has changed since 1.8 but I can't look at every commit :)

I know this require some time, and time is precious, but would you mind keeping the changelog up-to-date on major & minor releases?

Thanks,
Ben

**Comment by xabbuh** [comment]
Indeed, we did not update the changelog file very often and we should change that. However, maybe you find all the information you need in the [upgrade file](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.0/UPGRADING-2.0.md).

**Comment by Aliance** [comment]
+1 for updating the changelog file.

**Comment by Tobion** [comment]
Keeping changelogs is indeed important. But for 2.0 it's kinda too late now.
