### ISSUE TITLE
AccessDeniedListener not called

### ISSUE THREAD

**Issue by INSEAD-asim** [FriendsOfSymfony/FOSRestBundle#1638]
Hi Team,

I am trying to show response for AccessDeniedListener. I followed steps in https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING-2.0.md and added config settings as below.

    fos_rest:
        access_denied_listener:
            json: true
        exception: true

However, when I check in profiler, the listener is not called. I am using Symfony 2.8 and FOSRestBundle 2.1. Appreciate your help on this.

![accessdeniedlistener not called](https://cloud.githubusercontent.com/assets/7233258/21386482/f48ec176-c7ad-11e6-82ab-db056fc8e0bb.png)

**Comment by xabbuh** [comment]
The "Called Listeners" tab could be interesting too. It could be that another listener is catching the event and prevents other listeners from being executed.

**Comment by INSEAD-asim** [comment]
Here is the list of all listeners (called, not called). Thank you!

**Called Listeners**
![called_listeners_1](https://cloud.githubusercontent.com/assets/7233258/21412697/3141ea42-c82d-11e6-9943-e50bdde654ad.png)
![called_listeners_2](https://cloud.githubusercontent.com/assets/7233258/21412700/39864090-c82d-11e6-9829-99bfa146bd6d.png)

**Not Called Listeners**
![not_called_listeners_1](https://cloud.githubusercontent.com/assets/7233258/21412706/41ce7614-c82d-11e6-9147-003eab30f5db.png)
![not_called_listeners_2](https://cloud.githubusercontent.com/assets/7233258/21412726/5754b55c-c82d-11e6-94f3-3f12b982ed3c.png)
![not_called_listeners_3](https://cloud.githubusercontent.com/assets/7233258/21412730/5f16f200-c82d-11e6-8d03-23efd1f22e2c.png)

**Comment by xabbuh** [comment]
It looks like your controller doesn't throw an exception, but just returns a response. So there's no need for the listener to be executed.

**Comment by INSEAD-asim** [comment]
Hi @xabbuh , How can I return json response for 401? as per documentation link shared earlier, it should return after adding `exception: true`.

**Comment by xabbuh** [comment]
Well, this listener is all about dealing the exceptions that occur when access is denied. But when that never happens there is no need for the listener to be executed. The only thing that changed with 2.0 is that the listener itself won't create a response anymore, but you will have to turn the `exception` option on to let the `ExceptionController` deal with that matter. However, if there is no exception triggered, there is no need to run all this logic.

**Comment by INSEAD-asim** [comment]
I implemented listener for response body. Thanks anyway.
