### ISSUE TITLE
Restrict Exception Controller

### ISSUE THREAD

**Issue by crash21** [FriendsOfSymfony/FOSRestBundle#1642]
Hello,

I am using a custom  exception_controller because I would like to override 404 error message to avoid exposing Entity path (ie AppBunde\\Entity\\Foo object not found).

This is working fine but affects also HTTP exceptions (my app have 2 versions, HTTP and API), so I would prefer to restrict this controller to be  used only if I hit API URLs. 
Something like rules we have in format_listener.

How to do that?

**Comment by lsmith77** [comment]
it looks like we have a markup issue in the docs (see #1646) but this can be achived with the zone listener. search for "zone" on http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html

**Comment by lsmith77** [comment]
markup has been fixed http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html#zone-listener
