### ISSUE TITLE
RestBundle with JMSSerialization setSerializationContext

### ISSUE THREAD

**Issue by shubaivan** [FriendsOfSymfony/FOSRestBundle#1644]
in `"friendsofsymfony/rest-bundle": "~1.4",` we have setSerializationContext for class SerializationContext from `        "jms/serializer-bundle": "^1.1.0",` in this context we set gropu and enable depth

            return View::create()
            ->setStatusCode(200)
            ->setData($certificatesResponse)
            ->setSerializationContext(
                SerializationContext::create()
                    ->enableMaxDepthChecks()
                    ->setGroups(array('certificates_by_parameters'))
            );

early in `"friendsofsymfony/rest-bundle": "~1.4",` we have this function for View class from RestBundle

        /**
     * Sets the serialization context.
     *
     * @param SerializationContext $serializationContext
     *
     * @return View
     */
    public function setSerializationContext(SerializationContext $serializationContext)
    {
        $this->serializationContext = $serializationContext;

        return $this;
    }

In `"friendsofsymfony/rest-bundle": "^2.0",` I don't find this function, how to set serialized context in 2.0 version ?

**Comment by lsmith77** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING-2.0.md

```
use FOS\RestBundle\Context\Context;

$view = new View();

$context = new Context();
$view->setContext($context);

$context = $view->getContext();
```

**Comment by carere** [comment]
Hello guys :)

Can you update the doc on the Symfony Site for this issue ? Thx :)
