### ISSUE TITLE
[Question] How to correctly set response version information?

### ISSUE THREAD

**Issue by havvg** [FriendsOfSymfony/FOSRestBundle#1649]
Hi there,

I'm trying to get the version information into the response `Content-Type` header.
Assuming a client sends `Accept: application/json;v=2, application/json;v=1;q=0.8`

What's the correct/supported way to provide the version information within the response? Let's say I want to have it respond with `Content-Type: application/json;v=1`. Currently it only reads `application/json`.

**Comment by GuilhemN** [comment]
Unfortunately you can't as symfony response stores the request format but not its precise mime type so only `application/json` is given.
I suggest you to register your own request listener adding your version suffix to the content-type.

**Comment by vpassapera** [comment]
I opened a PR upstream, on symfony, as the docs in symfony say that this is indeed supported. Check this: https://github.com/symfony/symfony/pull/21975

**Comment by vpassapera** [comment]
https://github.com/symfony/symfony/pull/21975
