### ISSUE TITLE
Exclusion strategies  for context not in current version

### ISSUE THREAD

**Issue by Spea** [FriendsOfSymfony/FOSRestBundle#1653]
Hi there,

I realized, that the PR https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1583 was only merged into master and thus is not included in the current version (2.1.1). Are there any plans to port this feature to the 2.1 version or is it possible to create a new (2.2.0?) version with this included?

Thanks in advance

Martin

**Comment by GuilhemN** [comment]
Features are only packaged in minor versions. It is fine for me to release `2.2.0`, what about you @xabbuh @lsmith77?

**Comment by xabbuh** [comment]
I am not sure if we have enough features for a new minor version. At least, we should first agree on if and for how long we then maintain already existing 2.x minor versions. Added to that I am uncertain if we should continue the discussion started in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1583#issuecomment-253018931.

**Comment by GuilhemN** [comment]
> I am not sure if we have enough features for a new minor version. 

There aren't many feature requests nor features PRs so imo we should release what we already have.

> At least, we should first agree on if and for how long we then maintain already existing 2.x minor versions

Imo we should only fix bugs in the latest minor as we ensure bc.

**Comment by Spea** [comment]
Any updates on this? :)

**Comment by lbayerl** [comment]
Can we help something? We're still stuck to FOS Rest 1.7 because of this issue.

**Comment by GuilhemN** [comment]
I'll take care of it at the end of the week, i don't have time right now to check if everything's ready.

**Comment by lbayerl** [comment]
Sorry for bothering you - can we do anything?

**Comment by mvrhov** [comment]
I don't get it. Use master then.

**Comment by lbayerl** [comment]
I don't get it as well, isn't 'master' by default an unstable non-tagged version which is for development and test purposes only? If the functionality is ready (as I understand the history of this issue) why not tagging a new version which contains it?

**Comment by GuilhemN** [comment]
[2.2 is released](https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/2.2.0). Sorry for the delay...
