### ISSUE TITLE
@Route pluralize=false also applies to parent instead of child only

### ISSUE THREAD

**Issue by havvg** [FriendsOfSymfony/FOSRestBundle#1657]
When applying `pluralize=false` on a child resource, it's applied to the parent part, too. For example: Parent: `/users/{id}` Child: `/users/{id}/profiles`

When I now disable `pluralize` on the the `/profiles` controller, it yields such routes: `/user/{id}/profile`. 

The expected result is `/users/{id}/profile`, as the `pluralize` of `/users` is still `true`.

My current work-around:

```php
<?php
/**
  * @Route(path="/users/{userId}/profile")
  */
public function postAction(int $userId) { }
```

**Comment by Tobion** [comment]
Closing as  automatic route generation is deprecated: #1954
