### ISSUE TITLE
Access Token through HTTP Header instead of Query String

### ISSUE THREAD

**Issue by DavidGarciaCat** [FriendsOfSymfony/FOSRestBundle#1663]
Hello,

I would like to know if the bundle allows to get the access token via HTTP header instead of pass it via Query String.

Although the system works well with the Query String, I am managing several API endpoints, and discussing with other colleagues we believe is easier if we keep the FOS Rest Bundle (due the API is already implemented) and - if possible - change the way we use to authenticate the user.

I'll appreciate if anyone can send me a link to the docs page or an example, due I was not able to find it (easily?) after search it several times.

Thanks,

**Comment by xabbuh** [comment]
Can you explain what you mean with "access token"? If we are talking about authentication and authorisation, then that's nothing related to FOSRestBundle as this bundle does not deal with the Security layer at all. This is the responsibility of Symfony's Security component and you can configure/customise it to fit whatever use case you have.

**Comment by DavidGarciaCat** [comment]
Hi @xabbuh 

Right now I need to get an access token via OAuth, then I need to send this access token in order to identify the user. So, in the end, I need to call this endpoint:

https://api.example.com/v1/path/to/my/resource?access_token={my-access-token-here}

What I was expecting is to add a HTTP Header like `X-AUTH-TOKEN`, so instead of send a Query String argument with my token, I would like to identify my user via this header.

I don't know if this bundle allows this, but I think the Symfony Guard Authentication feature - new in Symfony 2.8 - is giving us an easy way to manage a request like this. However I don't know the bundle is managing already this case, or how to use it.

New in Symfony 2.8: Guard authentication component
https://symfony.com/blog/new-in-symfony-2-8-guard-authentication-component

How to Create a Custom Authentication System with Guard
https://symfony.com/doc/current/security/guard_authentication.html

Any idea?

Thanks,

**Comment by mvrhov** [comment]
Please use FOSOAUTHbundle for this functionality.

**Comment by DavidGarciaCat** [comment]
OK @mvrhov I'll have a look - Thanks,
