### ISSUE TITLE
How can I set-up a Rate Limit?

### ISSUE THREAD

**Issue by DavidGarciaCat** [FriendsOfSymfony/FOSRestBundle#1664]
Hello,

I was wondering how to set-up a Rate Limit so - for example - if a user runs more than 500 calls in 15 minutes then return a 429 Status Code response.

Thanks,

**Comment by xabbuh** [comment]
That's nothing really specific to FOSRestBundle IMO. If you want to do this in Symfony, you can register an event listener that handles the `kernel.request` event, performs some check and returns the response before it actually reaches your controllers. But of course you can as well handle this in a dedicated server/in the web server (Nginx or Apache should be able to do that) or whatever you prefer.

**Comment by DavidGarciaCat** [comment]
Hi @xabbuh 

That was my plan B, so I assume is the best choice.

Thanks,
