### ISSUE TITLE
Consider adding GitHub Topics to this repository

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSRestBundle#1667]
Dear bundle maintainer(s), if you want to make this bundle easier to discover and want to help us creating a stronger Symfony ecosystem, please consider adding some GitHub topics to this repository.

[The official Symfony recommendation](https://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories) is to add `php`, `symfony`, `bundle` and `symfony-bundle` topics ... and then, your own specific topics.

Thanks for your help!

**Comment by stof** [comment]
done

**Comment by xabbuh** [comment]
Don't know if it was there before, but now it is. :)

<img width="992" alt="bildschirmfoto 2017-02-13 um 19 05 11" src="https://cloud.githubusercontent.com/assets/1957048/22896198/6f6d711c-f21f-11e6-943b-f092538086f9.png">
