### ISSUE TITLE
Paramfetcher Exception message not shown in response after upgrade

### ISSUE THREAD

**Issue by kobelobster** [FriendsOfSymfony/FOSRestBundle#1678]
I wanted to upgrade my project to Symfony 3.2 and also upgraded FOS from 1.2 to 2.1. Problem is, when an exception in my `ParamFetcher` is thrown, I don't get the message in the response anymore. I debugged through the code and saw in `Symfony/Component/HttpKernel/HttpKernel` that the line 232 has the following code `$response = $event->getResponse();`. Now, when using the old version of the bundle, in the response, I would get the old error message 

`Request parameter message value {value} violated a constraint (Request parameter '.
                'value{value}, does not match requirements \'.{0,1023}\')`

Now, with the new code, when I go debug through the code and am at the same line, the response object contains `{"code":400,"message":"Bad Request"}` as a response content. However, when I look at the `$e` variable, it still has the FOS Exception message: `Parameter "message" of value "{{value}}" violated a constraint "Parameter 'message' value, does not match requirements '.{0,1023}'"`

So why does this message gets overwritten? Did I do something wrong when migrating to 2.1? I added

```
sensio_framework_extra:
   view:
       annotations: true
```

to my config but it didn't help. This is my config

```
fos_rest:
    access_denied_listener:
        json: true
    param_fetcher_listener: true
    format_listener:
        rules:
            -
                path: '^/api'
                fallback_format: json
            -
                path: '^/'
                stop: true
    view:
        formats:
            json: true
            pdf: true
        view_response_listener: true

    routing_loader:
        default_format: json
        include_format: false
    exception:
        codes:
            // Some exceptions and their status codes
        messages:
            // Some exceptions that are set to true
    service:
      inflector: mapudo_corebundle.util.inflector.noopinflector
```

What do I need to do more to see the messages from FOS again instead of a bad request response?

**Comment by tzfrs** [comment]
Just a thought: Could that be because I'm using the JMS Serializer and not the Symfony serializer? Because in the upgrade guide, it says:

> After (if you use the Symfony serializer):

So what about the JMS users?

**Comment by Tobion** [comment]
I guess you need to add `FOS\RestBundle\Exception\InvalidParameterException` to the `fos_rest.exception.messages` config for those error messages to be shown.

**Comment by kobelobster** [comment]
Hey @Tobion 

I closed this issue. It's not relevant anymore (since I don't develop for PHP anymore) and I can't test your solution since I don't have any code anymore
