### ISSUE TITLE
ExceptionNormalizer debug parameter

### ISSUE THREAD

**Issue by annamakowskaespeo** [FriendsOfSymfony/FOSRestBundle#1687]
Hi, 
I found, that in ExceptionNormalizer service declaration, (probably) you forgot to pass debug data (second parameter).

```
<service id="fos_rest.serializer.exception_normalizer.symfony" class="FOS\RestBundle\Serializer\Normalizer\ExceptionNormalizer" public="false">
     <argument type="service" id="fos_rest.exception.messages_map" /> <!-- exception messages -->
     <argument /><!-- show exception message -->
    <tag name="serializer.normalizer" priority="-10" />
</service>
```

I guess that _kernel.debug_ should be passed there.

**Comment by GuilhemN** [comment]
It's injected [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/FOSRestExtension.php#L344).
