### ISSUE TITLE
Retrieving status code for exceptions doesn't work from string

### ISSUE THREAD

**Issue by ostrolucky** [FriendsOfSymfony/FOSRestBundle#1699]
On http://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html it's advertised that you can use this:
```yml
fos_rest:
    exception:
        codes:
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
```

But that doesn't seem to be true in 2.* version. I don't see any code which would fetch the value for this string from \Symfony\Component\HttpFoundation\Response, as is implied in https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING-2.0.md. You now need to use numeric values.

**Comment by stof** [comment]
The code is here: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/d62a6c0f4bc699f899865d7e7bc7a4186aef9a86/DependencyInjection/Configuration.php#L418

**Comment by ostrolucky** [comment]
So it is indeed supposed to be supported. But it's missing in ExceptionController

**Comment by ostrolucky** [comment]
So that section looks quite different in latest release (2.1.1)

**Comment by stof** [comment]
The ExceptionController should not need it. It never reads the YAML file itself.

**Comment by stof** [comment]
Can you tell us what the issue you have is ?

**Comment by ostrolucky** [comment]
Ok it was fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1585, there just wasn't new release since then (half a year, really?)
