### ISSUE TITLE
Has JMS Serializer support been cancelled/stopped for this bundle?

### ISSUE THREAD

**Issue by lbayerl** [FriendsOfSymfony/FOSRestBundle#1700]
We are fully aware that since Symfony introduced the Serizalizer component there are basically two major Serializers out there of which one is usually used when using the FOS Rest Bundle.
Assuming that all older projects (including ours) which started before the new component came up were using JMS Serializer it would have been great if JMS Serializer is supported as long as there is no other statement.

We are using ExceptionWrapperHandler, VirtualProperties, custom Exclusion Strategies (for both named fields and serialization depth) etc. That's as well the reason why we're not able to easily switch our Serialization component.

FOS Rest bundle is still poorly documented regarding e.g. Exception Handling with JMS Serializer, Exclusion Strategies are merged but not published (1653)[https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1653], so we're still using a FOS Rest version which is from 2015.

Don't get me wrong, it's much appreciated what bundles like this are giving to the community but
1. I was offering my support in order to get out 1653 but there was no response
2. in general I'd propose to merge FOS Rest bundle into Symfony framework (as unlike FOS User e.g. it's not a "add-on" but in between the full stack)
3. if JMS Serializer is only supported for the most basic stuff (things for which it wouldn't be really necessary to use in the first place) why isn't that communicated upfront that you don't want users to use it anymore and deprecate it.

Is there anything we can support you with?

**Comment by xabbuh** [comment]
I am sorry this took us so long @lbayerl. But finally we managed to release [2.2.0](https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/2.2.0) containing the changes from #1653. Thus I am going to close here.
