### ISSUE TITLE
setFormat on view ignored in 2.2.0

### ISSUE THREAD

**Issue by swordbeta** [FriendsOfSymfony/FOSRestBundle#1702]
Since 2.2.0 the `setFormat` method on a view is ignored.

The following configuration:

```yml
 - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: false }
```

With the following in the controller:

```php
$this->handleView($this->view()
            ->setTemplate('myView.html.twig')->setFormat('html'));
```

Worked in 2.1.1. Since 2.2.0 the above does not work. Is this intended behavior? I have been unable to find documentation or change log on this.

**Comment by xabbuh** [comment]
What is the behaviour that you observe now? You still get the same response body but the `Content-Type` header is different?

**Comment by swordbeta** [comment]
@xabbuh Same response but the Content-Type is `application/json` instead of `text/html`

**Comment by xabbuh** [comment]
Can you check if this is caused by #1668 or #1683?

**Comment by swordbeta** [comment]
@xabbuh Reverting https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1683 fixes this issue
