### ISSUE TITLE
PUT forms are not binding data with $form->handleRequest, but POST do

### ISSUE THREAD

**Issue by ebeem** [FriendsOfSymfony/FOSRestBundle#1713]
I have this code which is supposed to bind form data into the variable `$postData`
```
$form = $this->createForm(new AnonymousActivateAccountType(), $postData, [
            'method' => 'PUT'
        ]);
```

now when I run it, sadly it does not bind the data.

when I change the function's method into `POST` and change form method into `POST`, it binds the data to the variable.

Did anyone get a similar issue? thanks

**Comment by ebeem** [comment]
so .. it turned out that the request objects that I get in `PUT` methods contain data in `query` and not in `request`. So, I think this is not this bundle's problem ...

after doing this work around, it worked
```
$request = $this->get('request');
$request->request = $request->query;

```

now I do have a question, however, is it really supposed to work this way? parameters of `PUT` and `PATCH` and `DELETE` methods will be treated as query parameters? and only `POST` parameters will be treated as request parameters?

I don't feel that this is right, is this is a bug or a misunderstanding from me?

**Comment by xabbuh** [comment]
This looks like an issue in the client code. It should send the data as part of the request body (of course, there's nothing wrong with sending data as part of the query string in a PUT request, it just does not make much sense here).

**Comment by ebeem** [comment]
so .. in normal cases, the put data are sent in request? I tried two clients: Firefox Rest Client, and Jetbrains's Rest Client. I will try and android later, but I feel it's not the issue of the client.

**Comment by ebeem** [comment]
@xabbuh thanks, it's just as you said, it was a client issue after all
sorry for the false report.
