### ISSUE TITLE
Deprecation warning on Symfony 3.3

### ISSUE THREAD

**Issue by dlegatt** [FriendsOfSymfony/FOSRestBundle#1724]
On a fresh install with Symfony 3.3.2, i get the following deprecation notice in my logs:

    Autowiring services based on the types they implement is deprecated since 
    Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the
    "fos_rest.view_handler.default" service to "FOS\RestBundle\View\ViewHandlerInterface" instead.

The only change I made besides installing FOSRestBundle and JMSSerializerBundle was to have the DefaultController extend FOSRestController like so:

    class DefaultController extends FOSRestController
    {
        /**
         * @Route("/", name="homepage")
         */
        public function indexAction(Request $request)
        {
            // replace this example code with whatever you need
            return $this->render('default/index.html.twig', [
                'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
            ]);
        }
    }

I wasn't able to find anything in the issues or PRs for this, is there a workaround available?

**Comment by Konafets** [comment]
Without using the the package, I would say that this is no problem. The deprecation notice just let you now that something will not work with Symfony 4.0 and how you should fix it.

**Comment by xabbuh** [comment]
Do you have any service where you used to inject the `fos_rest.view_handler.default` service before and now rely on autowiring doing the job for you?

**Comment by crashev** [comment]
will this be somehow fixed in order to stop symfony shouting about this deprecation ?

**Comment by zbyyna** [comment]
Hi,
I have the same problem in Symfony 3.4.0:

Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_rest.view_handler.default" service to "FOS\RestBundle\View\ViewHandlerInterface" instead.

Can you help me with this deprecation warning?

**Comment by xabbuh** [comment]
Can you try out the changes from #1763?
