### ISSUE TITLE
[Question] Route generation with complex Controller Class name

### ISSUE THREAD

**Issue by lucraraujo** [FriendsOfSymfony/FOSRestBundle#1726]
Hello everyone,
I'm sorry if this is not the place to ask a question, but I could not find any place (Slack, IRC, email, whatever) to ask a question.

I have a controller with a complex name, something like `class FooBarController extends FOSRestController implements ClassResourceInterface`, and, as you can see, I'm using the automatic route generation. The problem I have is that the route it generates is kinda weird, something like `http://lucraraujo/api/v1/foos/bars` (plurals everywhere!).
Is there a way to still use auto route and get something like `http://lucraraujo/api/v1/foo/bars` or `http://lucraraujo/api/v1/foobars` or I will have to use the strategy I'm using today, which is manual route definition?

Thanks!

**Comment by GuilhemN** [comment]
I guess you shouldn't capitalize both words then and call your controller `FoobarController`.

**Comment by lucraraujo** [comment]
Thanks!
