### ISSUE TITLE
400 Bad Request show details in prod

### ISSUE THREAD

**Issue by pesseyjulien** [FriendsOfSymfony/FOSRestBundle#1727]
Hi,

I would like to show the constraint validation error message, even in prod. Is there a way to do this ?

Thanks,
Julien

**Comment by rehoehle** [comment]
I have the same problem. In dev mode i see the message:

message: "Parameter "hwVersion" of value "NULL" violated a constraint "This value should not be blank.""

in Production mode i see only:

message: "Bad Request"

**Comment by GuilhemN** [comment]
There is two ways to do that:
- one option is to use ``messages``:
```yml
fos_rest:
    exception:
        messages: [Exception: true]
```
- or use `debug`:
```yml
fos_rest:
    exception:
        debug: true
