### ISSUE TITLE
injecting services in cgetAction

### ISSUE THREAD

**Issue by mjpvandenberg** [FriendsOfSymfony/FOSRestBundle#1731]
Is there a recommended way to use "action" service injection in a resource's "index" action, such as getRegionsAction? I've noticed that injecting a service (e.g. Doctrine's EntityManager) into the getRegionAction does not impact the auto-generated route, but in the getRegionsAction it results in an additional URL part.

```php
public function getRegionsAction(EntityManager $em)
{
    //
}

public function getRegionAction(Region $region, EntityManager $em)
{
    //
}
```

My routing.yml:

```
api:
    type:     rest
    resource: routing_api.yml
    prefix:   /api
```

and routing_api.yml:

```
regions:
    type:        rest
    resource:    AppBundle\Controller\Api\RegionController
    name_prefix: api_
```
This results in the following routes. 

```
api_get_regions            GET      ANY      ANY    /api/regions/{em}
api_get_region             GET      ANY      ANY    /api/regions/{region}
``` 

I would like the first route's path to be `/api/regions` .

FWIW, I've found it helps to add `@FOS\Get("regions")` to the getRegionsAction docblock. Now the api_get_regions route simply has an `api/regions` path, and its also creates a redundant route with the exact same path. However, this works only if I don't use a path prefix. I do use a prefix ("/api"), but it is not applied to the extra redundant route which still has the path `/regions`, which I don't want. If I change the annotation to `@FOS\Get("api/regions")` the extra redundant path is correct but now obviously the api_get_regions route's path has two /api prefixes.

**Comment by mvrhov** [comment]
Don't inject the services into the actions as the bundle doesn't support this.
IMO it's better to inject the dependencies in constructor.

**Comment by mjpvandenberg** [comment]
Constructor injection is a good alternative, but I prefer action injection wherever possible. That's mostly a matter of taste, but also it prevents resolving and injecting unused services.

**Comment by mvrhov** [comment]
You could also use class per action and __invoke, but then there won't be automatic route generation however it will work with constructor injection.

**Comment by mjpvandenberg** [comment]
Turns out that the solution is, in fact, to simply use manual route definition. The reason this was causing duplicate and incorrect routes was because of this: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/813#issuecomment-50966837
