### ISSUE TITLE
Unrecognized option "prefix_methods" under "fos_rest.routing_loader"

### ISSUE THREAD

**Issue by PeterZhukov** [FriendsOfSymfony/FOSRestBundle#1747]
Hi, I'm using 
```
"name": "friendsofsymfony/rest-bundle",
"version": "2.2.0",
```
Documentation http://symfony.com/doc/master/bundles/FOSRestBundle/7-manual-route-definition.html says: 
```
Or you can disable it globally by setting:
...
routing_loader:
    prefix_methods: false
```
But when I set this setting at path `fos_rest.routing_loader.prefix_methods` i get an exception:
```
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "prefix_methods" under "fos_rest.routing_loader"
```
I've searched all project source code files for "prefix_methods" string and nothing found. But `routing_loader `setting exists in configuration, but it accepts only `default_format` and `include_format` children (as I saw in source code).

**Comment by xabbuh** [comment]
It's present here: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Configuration.php#L106 Can you show the output of `composer show` for your project?

**Comment by xabbuh** [comment]
Oh well, it looks like we in fact did not tag a new release since then.

**Comment by PeterZhukov** [comment]
`comsposer show`


||||
:-----:|:-----:|:-----:
cocur/slugify|v2.5|Converts a string into a slug.
composer/ca-bundle|1.0.7|Lets you find a path to the system CA bundle, and in...
doctrine/annotations|v1.4.0|Docblock Annotations Parser
doctrine/cache|v1.6.2|Caching library offering an object-oriented API for ...
doctrine/collections|v1.4.0|Collections Abstraction library
doctrine/common|v2.7.3|Common Library for Doctrine projects
doctrine/data-fixtures|v1.2.2|Data Fixtures for all Doctrine Object Managers
doctrine/dbal|v2.5.13|Database Abstraction Layer
doctrine/doctrine-bundle|1.6.8|Symfony DoctrineBundle
doctrine/doctrine-cache-bundle|1.3.0|Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle|2.3.0|Symfony DoctrineFixturesBundle
doctrine/inflector|v1.1.0|Common String Manipulations with regard to casing an...
doctrine/instantiator|1.0.5|A small, lightweight utility to instantiate objects ...
doctrine/lexer|v1.0.1|Base library for a lexer that can be used in Top-Dow...
doctrine/orm|v2.5.6|Object-Relational-Mapper for PHP
doctrine/phpcr-bundle|1.3.9|Symfony DoctrinePHPCRBundle
doctrine/phpcr-odm|1.4.2|Object-Document-Mapper for PHPCR
fergusean/nusoap|0.9.5|NuSOAP re-packaged for Packagist/Composer
friendsofsymfony/rest-bundle|2.2.0|This Bundle provides various tools to rapidly develo...
imagine/imagine|v0.6.3|Image processing for PHP 5.3
incenteev/composer-parameter-handler|v2.1.2|Composer script handling your ignored parameter file
jackalope/jackalope|1.3.3|Jackalope PHPCR library
jackalope/jackalope-doctrine-dbal|1.3.0|Jackalope Transport library for Doctrine DBAL
jdorn/sql-formatter|v1.2.17|a PHP SQL highlighting library
jms/metadata|1.6.0|Class/method/property metadata management in PHP
jms/parser-lib|1.0.0|A library for easily creating recursive-descent pars...
jms/serializer|1.8.1|Library for (de-)serializing data of any complexity;...
jms/serializer-bundle|1.5.0|Allows you to easily serialize, and deserialize data...
knplabs/knp-menu|2.2.0|An object oriented menu library
knplabs/knp-menu-bundle|2.1.3|This bundle provides an integration of the KnpMenu l...
liip/imagine-bundle|1.8.0|This bundle provides an image manipulation abstracti...
monolog/monolog|1.23.0|Sends your logs to files, sockets, inboxes, database...
paragonie/random\_compat|v2.0.10|PHP 5.x polyfill for random\_bytes() and random\_int()...
phpcollection/phpcollection|0.5.0|General-Purpose Collection Library for PHP
phpcr/phpcr|2.1.4|PHP Content Repository interfaces
phpcr/phpcr-utils|1.3.0|PHP Content Repository implementation independant ut...
phpoption/phpoption|1.5.0|Option Type for PHP
psr/cache|1.0.1|Common interface for caching libraries
psr/http-message|1.0.1|Common interface for HTTP messages
psr/log|1.0.2|Common interface for logging libraries
sensio/distribution-bundle|v5.0.20|Base bundle for Symfony Distributions
sensio/framework-extra-bundle|v3.0.26|This bundle provides a way to configure your control...
sensio/generator-bundle|v3.1.6|This bundle generates code for you
sensiolabs/ansi-to-html|v1.1.3|A library to convert a text with ANSI codes to HTML
sensiolabs/security-checker|v4.1.3|A security checker for your composer.lock
sonata-project/admin-bundle|3.x-dev 559797e|The missing Symfony Admin Generator
sonata-project/block-bundle|3.3.2|Symfony SonataBlockBundle
sonata-project/cache|1.0.7|Cache library
sonata-project/core-bundle|3.4.0|Symfony SonataCoreBundle
sonata-project/datagrid-bundle|2.2.1|Symfony SonataDatagridBundle

```
composer.json
"require": {
...
"friendsofsymfony/rest-bundle": "^2.2"
...
}
...
"minimum-stability": "dev"
...
```

I looked at master code you linked - here it is, thanks, that solves problem.

**Comment by iBasit** [comment]
How did it solve the problem?

**Comment by iBasit** [comment]
I have same problem with 2.2 and following is my config

```
fos_rest:
    param_fetcher_listener: true
    routing_loader:
        prefix_methods: false
        default_format: json                            # All responses should be JSON formated
        include_format: false

```

**Comment by PeterZhukov** [comment]
@iBasit 
change your `composer.json` record from `"friendsofsymfony/rest-bundle": "^2.2.0"` - (version may differ) to `"friendsofsymfony/rest-bundle": "2.2.x-dev"`. Then run `composer update`. I think `^2.2.x-dev` is better (https://getcomposer.org/doc/articles/versions.md), but i didn't try it.
