### ISSUE TITLE
Query param enforcing with strict does not work

### ISSUE THREAD

**Issue by crashev** [FriendsOfSymfony/FOSRestBundle#1753]
I'm using version 2.x of fos rest bundle, from documentation at https://symfony.com/doc/master/bundles/FOSRestBundle/param_fetcher_listener.html

* @QueryParam(name="count", requirements="\d+", strict=true, nullable=true, description="Item count limit")
   ........
     * If you set the strict parameter without a nullable option, this will result in an error if the parameter is missing from the query.

I have set it up like this

`@QueryParam(name="code", requirements="\[a-zA-Z]+", strict=true, description="OAuth2 Code")`

but still if I do not provide ?code in query parameter code is still executed, there is no error.
In this case I assume fos rest should enforce providing this parameter and should stop whenever it is missing.

Bug or am I doing something wrong here ?

**Comment by awudarowicz** [comment]
Same here. It doesn't work when it's more than one @QueryParam annotations. With single @QueryParam it looks like working correctly.

**Comment by awudarowicz** [comment]
It runs @QueryParam only if you get this param in your controller action via ParamFetcher $paramFetcher.
So simply do this:
`$count = $paramFetcher->get('count')`
And strict mode will work and throw an error because you want param which doesn't exists

**Comment by saddemm** [comment]
You need to do this : 
`$count = $paramFetcher->get('count', true)`
True to activate strict mode ;)

**Comment by Tobion** [comment]
Closing as explained.
