### ISSUE TITLE
Localization of REST API

### ISSUE THREAD

**Issue by pculka** [FriendsOfSymfony/FOSRestBundle#1755]
Hi,

is there any way getting {_locale} into all the routes with a fallback to default_locale?
I want to use Translatable doctrine behavior to auto-translate entities before outputting them via JSON on a per-route basis, something like:

/api/route1 -default
/api/de/route1 - german translation response
/api/fi/route1 - finnish translation response

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954

You can do this very easily with SF core by adding a `prefix: /{_locale}` to all routes you import.

**Comment by Tobion** [comment]
Btw, you can also use Accept-Language header for this which is more best-practice.
