### ISSUE TITLE
Symfony Serializer use in 2.2.0 (avoid JMS Serializer)

### ISSUE THREAD

**Issue by araines** [FriendsOfSymfony/FOSRestBundle#1767]
In our project we have both the JMSSerializer and the Symfony serializer configured.  We were running successfully with the FOSRestBundle happily using the Symfony serializer in v2.1.1 and had achieved this by ensuring the JMSSerializerBundle option `jms_serializer.enable_short_alias` was set to `false`.

Unfortunately upgrading to v2.2.0 seems to have changed the behaviour of the FOSRestBundle so now its using the JMSSerializer instead when we do not want it to.

I attempted to set the service manually in `fos_rest.service.serializer` setting it to `serializer` but I get the following exception:

```
  [InvalidArgumentException]
  "fos_rest.serializer" must implement FOS\RestBundle\Serializer\Serializer (instance of "Symfony\Component\Serializer\Serializer" given).
```

How should I go about configuring this bundle to use the Symfony serializer over the JMS Serializer? 

Thanks

**Comment by zairigimad** [comment]
you can try to use the SymfonySerializerAdaptater 
fos_rest:
    service:
        serializer: fos_rest.serializer.symfony

**Comment by Tobion** [comment]
Closing as solution has been explained.
