### ISSUE TITLE
Deprecation warning on Symfony 3.3 when using ParamFetcher

### ISSUE THREAD

**Issue by analogic** [FriendsOfSymfony/FOSRestBundle#1777]
Code:
```php
class DomainController extends FOSRestController {
    public function getDomainsAction(ParamFetcherInterface $paramFetcher) {
    }
}
```
leads to this warning:
`Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_rest.request.param_fetcher" service to "FOS\RestBundle\Request\ParamFetcherInterface" instead.`

**Comment by mmoll** [comment]
@analogic please test #1777

**Comment by xabbuh** [comment]
I guess you meant #1779 :)

**Comment by mmoll** [comment]
@xabbuh 
> I guess you meant #1779 :)
aw, yes, editied.
