### ISSUE TITLE
Symfony 4 - unable to validate @RequestParam map to be not blank.

### ISSUE THREAD

**Issue by kgasienica** [FriendsOfSymfony/FOSRestBundle#1785]
I just found out that I'm unable to validate if `variable` is given in request body.

Sample `@RequestParam` which is not checking if `variable` is set:
```
     * @RequestParam(
     *     map=true,
     *     name="variable",
     *     default=null,
     *     nullable=false,
     *     allowBlank=false
     * )
```

It just goes through, not checking if it exist or not.

**Comment by xabbuh** [comment]
Does #1769 fix it?

**Comment by GuilhemN** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1769 merged
