### ISSUE TITLE
[Symfony 3.4] Custom error pages not working when exception controller is enabled

### ISSUE THREAD

**Issue by Danita** [FriendsOfSymfony/FOSRestBundle#1802]
Under Symfony 3.4, when the exception controller is enabled on FOSRest as in [the documentation](http://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html) the [customized Twig error pages](http://symfony.com/doc/4.0/controller/error_pages.html) don't work anymore and you get the standard template.

Apparently it has to do with the new way to reference templates (using `@`), see: 

* https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/TwigExceptionController.php#L40 versus
* https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php#L98

**Comment by gdbonino** [comment]
ping @xabbuh

**Comment by gdbonino** [comment]
#1870

**Comment by Tobion** [comment]
Fixed by #1870

**Comment by MilesYM** [comment]
This is still an ongoing issue on version 2.7.3

I've posted about it [here](https://stackoverflow.com/questions/60913352/symfony-4-with-fos-rest-bundle-messing-up-with-custom-error-pages)

Any help is appreciated.
Thank you.

**Comment by xabbuh** [comment]
@MilesYM Can you check if an approach like #2146 will help?

**Comment by MilesYM** [comment]
Thank you @xabbuh but I'm not sure I understand what I should do from this thread. I am looking into [the zones as described here](https://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#zone-listener). Is this the right approach?

**Comment by MilesYM** [comment]
I think that did the trick.
