### ISSUE TITLE
RestRouteCollection recognize getAction method like custom method

### ISSUE THREAD

**Issue by sanyaboomer** [FriendsOfSymfony/FOSRestBundle#1808]
I have updated the bundle to the version 2.3.
I have problem with the regular expression that was fixed in this commit https://github.com/FriendsOfSymfony/FOSRestBundle/commit/7da0aa5b6545d4789148920e2866182d175d315b the method is **RestRouteCollection::all**.

There is the issue
I have two methods in controller:

`
class Points
{

    /**
     * @Route("/validate/user/{id}/email/{email}/session/{sessionId}",
     *     name="points_validate_and_save",
     *     requirements={"id": "\d+", "email": ".+", "sessionId": "[\w-]+"}
     *     )
     */
    public function getAndAddSessionAction()
    {
    }

    /**
     * @Route("/validate/user/{id}/email/{email}",
     *     name="points_validate",
     *     requirements={"id": "\d+", "email": ".+"}
     *     )
     */
    public function getAction()
    {
    }

}
`

There are generated names for this action:
 - get_and_add_sessionpoints_validate_and_save
 - getpoints_validate

According to the fixed regexp the name "getpoints_validate" is recognized as route with a custom http method  and is placed first in url matcher. 
So the action with the url "/validate/user/{id}/email/{email}/session/{sessionId}" never be executed because the action "getAction" is called first and route rule in this action is more common.

I have found that everything is fine if method **RestActionReader::generateRouteName** return underscore instead of empty string. 
In this case **"getpoints_validate"** become **"get_points_validate"** and this is not custom http method so the order of methods in UrlMatcher is the same as in controller

**Comment by Tobion** [comment]
Closing as  automatic route generation is deprecated: #1954
