### ISSUE TITLE
Attempted to call an undefined method named "getParent" of class "FOS\RestBundle\FOSRestBundle"

### ISSUE THREAD

**Issue by KamilBanaszkiewicz** [FriendsOfSymfony/FOSRestBundle#1813]
Hello, i would like to report this bug after migrating to symfony 4 version. 
I think this is related to using View Annotations, because when i remove this annotation problem is gone.
here is my stack trace
```
in vendor\sensio\framework-extra-bundle\Templating\TemplateGuesser.php (line 95)
        $bundle = $this->getBundleForClass($className);        if ($bundle) {            while ($bundleName = $bundle->getName()) {                if (null === $parentBundleName = $bundle->getParent()) {                    $bundleName = $bundle->getName();                    break;                }
```

Also i cannot define parent to subresource, its little confusing because after research i found out this is possible only if I import my rest routes to the main routing and thats is not possible currently because of bundless structure of app. I have been tried all ways to include resource api.yaml but without result.

Please to check this out and give a feedback if will be possible to fix this issues. Regards

**Comment by xabbuh** [comment]
I am sorry, but that code is part of the SensioFrameworkExtraBundle. However, looking at the code it seems that they made that part of the bundle compatible with Symfony 4 in more recent releases. So just updating that bundle could possibly solve your issue.
