### ISSUE TITLE
[SF4] JMSHandlerRegistry::__construct() must implement HandlerRegistryInterface

### ISSUE THREAD

**Issue by sanchobouillant** [FriendsOfSymfony/FOSRestBundle#1819]
Hi,

I use the dev-master version of fosrestbundle and a fresh install of SF4.

I have the error:

> Type error: Argument 1 passed to FOS\RestBundle\Serializer\JMSHandlerRegistry::__construct() must implement interface JMS\Serializer\Handler\HandlerRegistryInterface, instance of Symfony\Component\DependencyInjection\ServiceLocator given

How can i fix it ?

**Comment by xabbuh** [comment]
Which version of `jms/serializer` do you use?

**Comment by sanchobouillant** [comment]
I try with dev-master and 2.3.

**Comment by xabbuh** [comment]
I am talking about the version of JMS Serializer not the version of FOSRestBundle.

**Comment by sanchobouillant** [comment]
> "jms/serializer-bundle": "dev-master",

Should I try a different version ?

**Comment by xabbuh** [comment]
And I do not mean the serializer bundle but the library. Please show the output of `composer show`.

**Comment by sanchobouillant** [comment]
Ow, ok. Sorry.

> jms/metadata                        1.6.0
> jms/parser-lib                      1.0.0  
> jms/serializer                      1.10.0 
> jms/serializer-bundle               dev-master 8172469
> friendsofsymfony/rest-bundle        dev-master dcd5add
> symfony/framework-bundle            v4.0.2

**Comment by xabbuh** [comment]
Oh I see, you are working on top of #1805. Thanks for catching this. The Travis CI build is currently failing with the same error. I am going to see how we can fix this.

**Comment by xabbuh** [comment]
@sanchobouillant Can you please try the latest changes from #1805? The issue you reported here shouldn't happen anymore.

**Comment by sanchobouillant** [comment]
With the commit #0f85a17149028f38708aca926e7eb8bbd639ca1d I have the error

`Warning: ReflectionObject::__construct() expects parameter 1 to be object, null given`

**Comment by xabbuh** [comment]
Does this also happen when you switch to `dev-master`? If so, are you able to create a small project that allows to reproduce your issue?

**Comment by sanchobouillant** [comment]
I create a small project that reproduce the 2 errors I have.

https://github.com/sanchobouillant/FosRestBundleIssues

**Comment by mgluesenkamp** [comment]
I have the same problem in my new Symfony 4 project. I get the error
`Warning: ReflectionObject::__construct() expects parameter 1 to be object, null given`
after a POST request.

**Comment by xabbuh** [comment]
I am closing here as the reported issue has been solved. The other issue will already be covered with  #1812.
