### ISSUE TITLE
Symfony 4 FOSUserBundle

### ISSUE THREAD

**Issue by methodeprog** [FriendsOfSymfony/FOSRestBundle#1823]
Dear Sir ive this issue ...

The "fos_user.registration.form.factory" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

/login is ok
/registration not ok
and i could not see my fosuser commands....ive tried all night....need help.

**Comment by stof** [comment]
FOSUserBundle is not yet compatible with Symfony 4 (there is an open PR working on it).

and anyway, this has nothing to do with FOSRestBundle.
