### ISSUE TITLE
[SF4] Consistency with guidelines and docs

### ISSUE THREAD

**Issue by pculka** [FriendsOfSymfony/FOSRestBundle#1837]
Hi,

I've been rewriting an "old style bundle-oriented" app into the new SF4 logic and found out a few problems regarding the implementation. As I didn't get deeper into FOSRest, I'll try to share my findings.

1. According to the new guidelines, all controllers should be residing in /src/Controller folder. If one sticks to the simplest "auto" routing scheme, where the definition in `/config/routes/app.yaml` is: 
```
controllers:
    resource: ../../src/Controller/
    type: annotation
```
then it seems the FormatListeners of Symfony and FOSRest crash upon each other and from the REST controllers you cannot output a simple array which corresponds to a json output, as the Symfony expects to find a corresponding template, which is defined as an empty string.

2. After moving the controllers out of `/src/Controller` into for example `/src/Rest`, or `/src/Api` with following api.yaml:
```
api:
    type: rest
    prefix: /api
    resource: ../../src/Api
```
It started working, though I found another "problem". The implementation somehow works for GET requests, but for example POST requests threw an error that a FQN should match regex containing the word `"Controller"`. Which is odd and it seems more of a guesser issue in Symfony core. Nevertheless after I created the structure of `/src/Api/Controller/*` it started working for all requests.

I think it would be nice to maybe look deeper into it (I don't have so much time atm to look into these :( ), so I just share my findings to maybe help others...

**Comment by xabbuh** [comment]
> then it seems the FormatListeners of Symfony and FOSRest crash upon each other and from the REST controllers you cannot output a simple array which corresponds to a json output, as the Symfony expects to find a corresponding template, which is defined as an empty string.

Do you mean something like what is described in #1812?

**Comment by Tobion** [comment]
Closing as  automatic route generation is deprecated: #1954
