### ISSUE TITLE
[Travis] Resolve Symfony 2 tests

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSRestBundle#1855]
> 1) FOS\RestBundle\Tests\Functional\SerializerErrorTest::testSerializeExceptionJson with data set #1 ('JMSSerializer')
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@dataProvider" in method FOS\RestBundle\Tests\Functional\SerializerErrorTest::testSerializeExceptionJson() was never imported. Did you maybe forget to add a "use" statement for this annotation?

**Comment by xabbuh** [comment]
fixed by #1873
