### ISSUE TITLE
[Travis] Resolve PHP 5.5 tests

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSRestBundle#1856]
> 1) FOS\RestBundle\Tests\Functional\SerializerErrorTest::testSerializeExceptionJson with data set #1 ('JMSSerializer')
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@template" in class PhpCollection\AbstractMap was never imported. Did you maybe forget to add a "use" statement for this annotation?

> 2) FOS\RestBundle\Tests\Functional\SerializerErrorTest::testSerializeExceptionXml with data set #1 ('JMSSerializer', '<?xml version="1.0" encoding=...sult>\n')
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@template" in class PhpCollection\AbstractMap was never imported. Did you maybe forget to add a "use" statement for this annotation?

**Comment by xabbuh** [comment]
fixed by #1873
