### ISSUE TITLE
DateInterval annotation  hour(s) ago format

### ISSUE THREAD

**Issue by adityarai** [FriendsOfSymfony/FOSRestBundle#1857]
datetime created today displays as "0 days ago" using @JMS\Type("DateInterval"). Is there a way to set format like an hour ago or minute ago instead.

**Comment by simsComputing** [comment]
Hello Adityarai, 
I'm not a contributor for this project, but I think your issue really concerns the [JMS Serializer bundle](https://github.com/schmittjoh/serializer/issues).

**Comment by EliuTimana** [comment]
You can use KnpTimeBundle's DateFormatter service.

**Comment by xabbuh** [comment]
I agree with @simsComputing that this looks related to JMSSerializerBundle (or maybe the underlying serializer library). Thus I am closing here.
