### ISSUE TITLE
Route format with Symfony4

### ISSUE THREAD

**Issue by Oviglo** [FriendsOfSymfony/FOSRestBundle#1860]
Hi,
I have this annotation in my controller:
`* @Get("/data", defaults={"_format": "json"}, name="base_admin_user_data")`
But url like "/data.xml", "/data.json" doesn't works:

> No route found for "GET /admin/user/data.json"

It work with symfony 3.
Do you have any solution ? 
thanks.

**Comment by xabbuh** [comment]
How do you load the routes? Where does the configuration of the `admin/user` prefix happen?

**Comment by Oviglo** [comment]
Hello, after more searchs I forgot to add type "rest" in my routes.
It work know.
Thanks you.

**Comment by xabbuh** [comment]
thanks for letting us know
