### ISSUE TITLE
Context setGroups behavior

### ISSUE THREAD

**Issue by TemirkhanN** [FriendsOfSymfony/FOSRestBundle#1867]
I'm not sure so why this made for but is it okay that context can contain only unique groups through 
[Context::addGroup()](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Context/Context.php#L140) and [Context::addGroups()](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Context/Context.php#L159) wherein it also provides [Context::setGroups()](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Context/Context.php#L185) that allows duplicates?

**Comment by xabbuh** [comment]
I think this was just missed when implementing `setGroups()`.

**Comment by TemirkhanN** [comment]
So there is no need in this "feature" break?

**Comment by xabbuh** [comment]
Sorry, I don't understand what you mean.

**Comment by stof** [comment]
Both JMSSerializer and Symfony Serializer are not caring at all about duplicate groups AFAIK, as groups are used to determine whether a property should be included in the serialization or no (if you specify groups, only properties belong to *at least one* group will be included)

**Comment by TemirkhanN** [comment]
@xabbuh i mean would it be sudden if I "setGroups" behavior change

to something below?

```php
function setGroups(array $groups = null)
{
    if ($groups === null) {
        $this->groups = null;
            
        return $this;
    }
        
    $this->addGroups($groups);

    return $this;
}

```

@stof thanks! Well, I supposed something like that and that took me to question "What is the real purpose of unique groups through Context::addGroup?". Nothing serious. Just wondering.

**Comment by xabbuh** [comment]
@TemirkhanN Your solution would not replace existing groups. But in general, I would not consider a change that ensures unique groups when calling `setGroups()` a BC break.
