### ISSUE TITLE
serizalizerGroups with YAML configuration uses "properties" instead of "attributes"

### ISSUE THREAD

**Issue by stilllife00** [FriendsOfSymfony/FOSRestBundle#1875]
I am using:
` @Rest\View(statusCode=Response::HTTP_OK, serializerGroups={"view"})`

And defining the annotations in a YAML file:

// src/Bundle/Resources/config/serializer/Entity.User.yml

    Bundle\Models\Entity\User:
         properties:
              firstName:
                    groups: ['view']

This works fine, but the official docs and Serizalizer of Symfony 3 and 4 are using `attributes` instead of `properties`. (http://symfony.com/doc/3.4//components/serializer.html). So in order to use FOSRest for the View and the Symfony Serializer for other reasons I need to duplicate the groups config. 

Is this the intended behavior or a bug ?

**Comment by xabbuh** [comment]
Are you sure that you are not using JMSSerializer in the view handler?

**Comment by stilllife00** [comment]
@xabbuh I think not.

````
use FOS\RestBundle\Controller\Annotations as Rest;

...
/** 
 * @Rest\View(statusCode=Response::HTTP_OK, serializerGroups={"user"})
*/
public function someUserAction() {
 // create an user
 return $user
}
````

**Comment by xabbuh** [comment]
This part is not relevant. It will look the same not matter if you use the Symfony Serializer or JMS Serializer. Do you have the JMSSerializerBundle installed and enabled? Can you also show your FOSRestBundle related config?

**Comment by stilllife00** [comment]
@xabbuh  You are right thanks for the clarification. JMSSerializer kicks in when returning an entity and it uses `properties` from the YAML file.
