### ISSUE TITLE
Error message about SensioFrameworkExtraBundle view annotations

### ISSUE THREAD

**Issue by oliverklee** [FriendsOfSymfony/FOSRestBundle#1878]
This happens with friendsofsymfony/rest-bundle version 2.3.1 in our project https://github.com/phpList/rest-api.

Updating the sensio/framework-extra-bundle package from version 5.1.0 to version 5.1.1 (or any later 5.1.x version) causes these error messages:
```
RuntimeException : You must enable the SensioFrameworkExtraBundle view annotations to use the ViewResponseListener. Did you forget to install and enable the TwigBundle?
```

This can be seen in these builds (all red ones):
https://travis-ci.org/phpList/rest-api/builds/350436773

I've been able to narrow this down to two changes in the sensio/framework-extra-bundle package where the authors explicitly mention the FOSRestBundle:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/530#issuecomment-347965490

> Reusing the old name has an advantage: it will avoid breaking bundles needing to deal with these services, if they kept support for the previous version of the bundle (I'm looking at FOSRestBundle here).

These are the two corresponding changes:
- original change: https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/530
- follow-up fixes: https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/534

**Comment by xabbuh** [comment]
You are right. But we already have an open issue for this. So I am closing here in favour of #1812.
