### ISSUE TITLE
Service "translator" is required when using symfony serializer but not in dependecies

### ISSUE THREAD

**Issue by magnetik** [FriendsOfSymfony/FOSRestBundle#1883]
Hey,

Using FOSRestBundle 2.3.1 with Symfony 4 and the Serializer component I faced the problem that the `fos_rest.serializer.form_error_normalizer` is loaded and require the `translator` component but this dependency is not defined anywhere.

Should this service be loaded conditionally, translator added as a dependency (or a suggest maybe ?) ? 

I can provide a pull request.

**Comment by xabbuh** [comment]
Since we can use the Form component without translations I suggest that we make this argument optional and skip translations if the translator is not present.

**Comment by stof** [comment]
FormErrorNormalizer should simply use `$form->getError()`, which already contains the translated error, instead of duplicating everything on its own. Support for Symfony 2.0 (where this was not the case) does not make sense.

**Comment by magnetik** [comment]
I'm all in not supporting Symfony 2 but it won't be possible before a FOSRestBundle 2.4 or something like that? 

Meanwhile, I've done #1884 to fix it on the short term.

**Comment by magnetik** [comment]
So yeah let's remove it completely, its done in #1892 :)

**Comment by stof** [comment]
@magnetik I'm not talking about dropping support for Symfony 2. The untranslated message in the form error is a Symfony 2.0 thing only. It is translated since 2.1

**Comment by magnetik** [comment]
Yup I "just" removed the translator dependency completely (or I just misunderstood you right now).

**Comment by tomasfejfar** [comment]
When is this expected to land in a release, please?
