### ISSUE TITLE
Referencing controllers with a single colon is deprecated since Symfony 4.1 when executing PHPUnit

### ISSUE THREAD

**Issue by jguyenot** [FriendsOfSymfony/FOSRestBundle#1897]
Hi,

since we are updated to Symfony 4.1 we have this error when launching 
`./vendor/bin/simple-phpunit`

Error message
```
  1x: Referencing controllers with a single colon is deprecated since Symfony 4.1. Use App\Core\User\Controller\UserGroupController::deleteAction instead.
    1x in ContainerTypeTest::testCRUD from App\Tests\Core\Container\Controller
```

I've check into the 
`vendor/friendsofsymfony/rest-bundle/Routing/Loader/RestRouteLoader.php`
and i apply a correction.

`Line 119 :: $prefix = $controller.':'; >> $prefix = $controller.'::';`
`Line 133 :: } elseif (false !== strpos($controller, ':')) { >> } elseif (false !== strpos($controller, '::')) {`

Could you check this correction to apply it into the next release?

**Comment by pdugas** [comment]
I think we also need a fix for the same issue in `Resources/config/exception_listener.xml` where it's referencing `showAction`.  Add the colon there too.

**Comment by pdugas** [comment]
I can confirm the changes to RestRouteLoader.php that @jguyenot proposed resolved the issue for me.

**Comment by xabbuh** [comment]
Did you check if that still works with Symfony 3.4?

**Comment by jguyenot** [comment]
Hi @xabbuh , it works fine with Symfony 4.1 but they deprecated the annotation with only one ":".

**Comment by GuilhemN** [comment]
Your fix won't work, using 3.x an exception will be thrown: https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php#L180.

We need to change the syntax conditionally.
