### ISSUE TITLE
JMS serializer not attached in container. 

### ISSUE THREAD

**Issue by joshhornby** [FriendsOfSymfony/FOSRestBundle#1901]
The documentation states (https://symfony.com/doc/master/bundles/FOSRestBundle/1-setting_up_the_bundle.html#c-enable-a-serializer):

>This bundle needs a serializer to work correctly. In most cases, you'll need to enable a serializer or install one. This bundle tries the following (in the given order) to determine the serializer to use:

> The one you configured using fos_rest.service.serializer (if you did).
> The JMS serializer, if the JMSSerializerBundle is available (and registered).
> The Symfony Serializer if it's enabled (or any service called serializer).

I've installed `"jms/serializer-bundle": "^2.4"` and using `"friendsofsymfony/rest-bundle": "^2.3"`.

My `bundles.php` has both `FOS\RestBundle\FOSRestBundle::class => ['all' => true],` and `JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],`
but `$this->container->has('serializer')` is returning false? Is there some extra non documented step?

**Comment by magnetik** [comment]
Which version of the FOSRestBundle are you using ? The JMSSerializer is not defining the `serializer` alias, but `jms_serializer.serialize` alias.

**Comment by Tobion** [comment]
Closing as explained by @magnetik .
