### ISSUE TITLE
Reduce deplucation FosRest annotations

### ISSUE THREAD

**Issue by aebenhassine** [FriendsOfSymfony/FOSRestBundle#1908]
I'm using <a href="https://symfony.com/doc/master/bundles/FOSRestBundle/index.html">Fos RestBundle</a> that helps me implement some annotations for my Rest API resources,
The fact that I don't really like the huge block of annotations that should be defined above my function...where I'm using `query param fetcher`to get some data such `query` and `category` ...
<br>
Any idea how I can create <b>one Symfony annotation</b> that includes the hole block of `@FOSRest\QueryParam` annotations.<br>
And finnaly the new solution gonna help me to reduce the code, separate code, and decoupling.

<br>
This my function:

        /**
         * @param ParamFetcherInterface $paramFetcher
         *
         * @return int[]
         *
         * @FOSRest\QueryParam(name="query")
         * @FOSRest\QueryParam(name="articleReference", requirements="\d+")
         * @FOSRest\QueryParam(name="category", requirements="\d+")
         * @FOSRest\QueryParam(name="memberCategory", requirements="\d+")
         * @FOSRest\QueryParam(name="supplier", requirements="\d+", nullable=true)
         * @FOSRest\QueryParam(name="published", requirements="(0|1)", nullable=true)
         * @FOSRest\QueryParam(name="withoutCoefficient", requirements="(0|1)", nullable=true)
         * @FOSRest\QueryParam(name="zipCode", requirements="\d+", nullable=true)
         * @FOSRest\QueryParam(name="memberCategoryStrict", default=0, requirements="(0|1)")
         * @FOSRest\QueryParam(name="orphan", requirements="(0|1)", nullable=true)
         * @FOSRest\QueryParam(name="articleType", requirements="article|catalog", nullable=true)
         * @FOSRest\QueryParam(name="withImage", requirements="0|1", nullable=true)
         * @FOSRest\QueryParam(name="withTechnicalSheet", requirements="0|1", nullable=true)
         *
         */
        public function getArticlesStatsAction(ParamFetcherInterface $paramFetcher)
        {
         //
         }

I want to implement an annotation called `@GetArticlesStats()` for eg. where the final result should look like this:

    /**
     * @param ParamFetcherInterface $paramFetcher
     *
     * @return int[]
     *
     * @GetArticlesStats()
     *
     */
    public function getArticlesStatsAction(ParamFetcherInterface $paramFetcher)
    {
    //
    }
Any idea would be so appreciated. Thank you.

**Comment by stof** [comment]
this can actually be done, by overriding the `fos_rest.request.param_fetcher.reader` service with your own implementation of the ParamReaderInterface (be careful to still support the logic of the default implementation in parallel of yours, otherwise it might break third-party bundles expecting the default behavior)
