### ISSUE TITLE
Autowiring in DTO

### ISSUE THREAD

**Issue by MaksSlesarenko** [FriendsOfSymfony/FOSRestBundle#1919]
Body Param converter feature allows us to convert request params into DTO object and perform validation on them
https://symfony.com/doc/master/bundles/FOSRestBundle/request_body_converter_listener.html

There is problem that by default jms serialiser constructs objects on its own, without using autowiring. So only limited number of validators can be used. Unfortunately autowiring of deserialized object is not compatible with JMSserializer principles.

So I wonder if this feature can be implemented within fos-rest-bundle? 

https://github.com/schmittjoh/serializer/pull/979

**Comment by stof** [comment]
I'm wondering why you would want to inject a service into a DTO. That looks like a weird architecture to me.

**Comment by MaksSlesarenko** [comment]
@stof to perform validation against database for example

**Comment by Vovchikus** [comment]
> I'm wondering why you would want to inject a service into a DTO. That looks like a weird architecture to me.

Otherwise issue exists, class using paramconverter can not autowire service in it

**Comment by xabbuh** [comment]
I do not see that this will ever happen inside FOSRestBundle. So I am going to close here.

For validation, you can use the `validator` service and pass it your DTO. Validation constraints can be registered as services and thus do nearly everything.
