### ISSUE TITLE
Deprecation error Symfony 4 with FOSRestBundle

### ISSUE THREAD

**Issue by eaunitrust** [FriendsOfSymfony/FOSRestBundle#1922]
FOSRestBundle 2.3 is throwing a deprecation error:

> The "Sensio\Bundle\FrameworkExtraBundle\Configuration\Route" annotation is deprecated since version 5.2. Use "Symfony\Component\Routing\Annotation\Route" instead.

`"require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "friendsofsymfony/rest-bundle": "^2.3",
        "jms/serializer-bundle": "^2.4",
        "nelmio/api-doc-bundle": "^3.2",
        "sensio/framework-extra-bundle": "^5.2",
        "symfony/asset": "^4.1",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/orm-pack": "^1.0",
        "symfony/twig-bundle": "^4.1",
        "symfony/yaml": "^4.1"
    },
    "require-dev": {
        "symfony/browser-kit": "^4.1",
        "symfony/dotenv": "^4.1",
        "symfony/phpunit-bridge": "^4.1"
    },`

**Comment by GuilhemN** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1822
