### ISSUE TITLE
Return every param validation error.

### ISSUE THREAD

**Issue by lannerxiii** [FriendsOfSymfony/FOSRestBundle#1925]
Hello and sorry for having to ask this here. I'm having a problem with the paramFetcher and the param validation.I have this two annotations on my method and I need the paramFetcher to return the user a response specifying BOTH of the invalid params, not just one. If both params do not pass the validation I need to return a response explaining what happened and not just the first one. If I send both of them blank I only get an answer for the first one. 

`@RequestParam(name="nombre", allowBlank=false, strict=true, nullable=false, description="Nombre del archivo.")`

`@RequestParam(name="archivo_mime_type", strict=true, nullable=false, allowBlank=false, description="Contiene el mime type del archivo.")`

Does the Bundle provide a way of doing it?
Thank you

**Comment by cluster28** [comment]
@lannerxiii Did you find a workaround for that?
