### ISSUE TITLE
FOSRestBundle Exception triggers JMSSerializer on All routes

### ISSUE THREAD

**Issue by numediaweb** [FriendsOfSymfony/FOSRestBundle#1930]
I [disabled format listening ](https://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html#disabling-the-format-listener-via-rules) for non `^/api` routes and used custom exception in my config:
```
sensio_framework_extra:
    request: { converters: true }
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true } # Available for version >= 1.5
    view:
        view_response_listener: true
        formats:
            json: true
            html: true
        templating_formats:
            html: false
            json: false
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    serializer:
        serialize_null: true
    exception:
        enabled: true
        exception_controller: 'My\ApiBundle\Controller\ExceptionController::showAction'
```
This works fine when calling a non existing resource via api but the problem is JMS tries to serialize other exceptions not related to the route/path I specified above and results in:
```
UnsupportedFormatException
The format "html" is not supported for serialization.
```
_full error [here](https://prnt.sc/kg45u7)_

If I remove in the config:
```
    exception:
        enabled: true
        exception_controller: 'My\ApiBundle\Controller\ExceptionController::showAction'
```
I get normal exceptions but then I loose the option to customize my API 404 errors.

**Comment by Tobion** [comment]
Closing as the exception_controller has been deprecated and the fallback to html is fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2188
