### ISSUE TITLE
[Donation] How to donate ?

### ISSUE THREAD

**Issue by tonivdv** [FriendsOfSymfony/FOSRestBundle#1936]
Hi guys,

My company would like to start donating on regular basis to some of the open-source software that allows us to build our product much more easily then if we would have done this all by ourselves.

We know how to support symfony, composer or 1 single developer, but how about an organisation like FriendsOfSymfony ? 

Cheers

**Comment by lsmith77** [comment]
This is awesome! Donations in the form of money are quite complex in open source. Generally donations in the form of time are therefore the best way, ie. working on features, bug reports, PR reviews, documentation.

**Comment by tonivdv** [comment]
@lsmith77 Already doing that :) 

Maybe we should take the one that contributed the most for a specific time and by him something from a wishlist ?

**Comment by lsmith77** [comment]
sure. this can be a nice gesture

**Comment by tonivdv** [comment]
Since last year, the user contributed the most is @xabbuh . So @xabbuh do you have any wishlist somewhere? Like on Amazon? Or any book you want?

Results where found by doing following:

```
$ git log --since="1 year ago" | grep Author | sort | uniq -c | sort -n -r
  71 Author: Christian Flothmann <christian.flothmann@sensiolabs.de>
   7 Author: Guilhem N <egetick@gmail.com>
   5 Author: Asmir Mustafic <goetas@gmail.com>
   3 Author: Peter Culka <culka@trexima.sk>
   2 Author: Tobias Schultze <webmaster@tubo-world.de>
   2 Author: Karel Souffriau <karel@hardware.info>
   2 Author: Guilhem Niot <guilhem.niot@gmail.com>
   2 Author: Guilhem N <guilhem.niot@gmail.com>
   2 Author: Gabriel Caruso <carusogabriel34@gmail.com>
   1 Author: kunicmarko20 <kunicmarko20@gmail.com>
   1 Author: gdbonino <gdbonino@gmail.com>
   1 Author: ball00n- <herman.belous@gmail.com>
   1 Author: Toni Van de Voorde <toni.vdv@gmail.com>
   1 Author: Tomasz Hanc <tomasz.hanc@gmail.com>
   1 Author: Shane Archer <sarcher@ampdraw.com>
   1 Author: RokkieBrown <rokkie@users.noreply.github.com>
   1 Author: Peter Culka <p.culka@gmail.com>
   1 Author: Michael Moll <kvedulv@kvedulv.de>
   1 Author: Laurent Aubertin <2binfree@users.noreply.github.com>
   1 Author: Indra Gunawan <guind.online@gmail.com>
   1 Author: Fabian Gut <fabian.gut@ethy.ch>
   1 Author: Baptiste Lafontaine <baptiste@nadeo.com>
```

**Comment by xabbuh** [comment]
If I were to decide here, I would like to ask you to donate some money to Composer. I think @naderman or @Seldaek can help you with that.

**Comment by tonivdv** [comment]
@xabbuh Composer is indeed very important but we also want to gratify contributors to libraries we are using that speed up our dev. Now if you prefer to give to composer fine by us ;)

**Comment by Seldaek** [comment]
If anyone wants to "donate" to composer the best is to start using (Private Packagist)[https://packagist.com] - we don't accept donations per se. But IMO @xabbuh you should just accept it if someone wants to give something back for your work :)
