### ISSUE TITLE
View::getTemplateData gets called twice

### ISSUE THREAD

**Issue by mlazze** [FriendsOfSymfony/FOSRestBundle#1941]
Currently we can use setTemplateData method to add lazy-loading variables to the templating system.

The problem i'm facing is that i have some non idempotent operations in the callable I use with setTemplateData.
This only happens if I use DependencyInjection on the action level.
Simple example:
```php
public function indexAction(Request $request) {
    $integer = $request->get('integer');
    return $this->view()->setTemplateData(function () use (&$integer) {
        ++$integer;
        return ['result' => $integer];
    });
}
```

getTemplateData gets called twice, via https://github.com/FriendsOfSymfony/FOSRestBundle/blob/0df031da174d2a43a1ee3b397db13784380397bd/EventListener/ViewResponseListener.php#L114 and https://github.com/FriendsOfSymfony/FOSRestBundle/blob/0df031da174d2a43a1ee3b397db13784380397bd/View/ViewHandler.php#L359

I expected the callable to be called only once.

I changed my project code inside setTemplateData to account for double calls, but a warning on the documentation could be useful for others who face the same problem.

**Comment by Tobion** [comment]
Closing the the templating part is deprecated: #2088
