### ISSUE TITLE
 Generate a route based on class name not on the function name

### ISSUE THREAD

**Issue by ahmed-bhs** [FriendsOfSymfony/FOSRestBundle#1953]
I have this final class that represent an ENDPOINT for getting a list of articles:

    /**
     * @ApiDoc()
     *
     * @FOSRest\View()
     */
    final class getArticleListController extends AbstractRestController
    {
    
        public function __invoke() : array
        {
            return $this->em->getRepository(Article::class)->findAll();
        }
    }

This is my routing configuration:

    app_article:
        resource: App\Controller\Article\getArticleListController
        type: rest
        prefix: /api
        name_prefix: api_

1) Is it possible to use `routing_loader` with some few configuration to generate automaticly a route base on the class name instead of the function name. To get finnaly a route named: `api_get_article_list`<br>
2) Is it possible to change my routing configuration to something like this:

    app_article:
        resource: App\Controller\Article\*
        type: rest
        prefix: /api
        name_prefix: api_

**Comment by Tobion** [comment]
Closing as  automatic route generation is deprecated: #1954
