### ISSUE TITLE
JMSHandlerRegistry must implements HandlerRegistryInterface correctly

### ISSUE THREAD

**Issue by timotheemoulin** [FriendsOfSymfony/FOSRestBundle#1955]
Hello all,

In the latest version of JMS\Serializer the class JMS\Serializer\Handler\HandlerRegistryInterface defines `registerSubscribingHandler` and `registerHandler` as `void` functions thus ` JMSHandlerRegistry` implementation **must** follow the same definition and not return anything.

```
public function registerSubscribingHandler(SubscribingHandlerInterface $handler): void;
public function registerHandler(int $direction, string $typeName, string $format, $handler): void;
```
versus
```
 /**
 * {@inheritdoc}
 */
public function registerSubscribingHandler(SubscribingHandlerInterface $handler)
{
    return $this->registry->registerSubscribingHandler($handler);
}

/**
 * {@inheritdoc}
 */
public function registerHandler($direction, $typeName, $format, $handler)
{
    return $this->registry->registerHandler($direction, $typeName, $format, $handler);
}
```

Can anyone fix this?

Thanks for the help.
Timothée

**Comment by vkhramtsov** [comment]
Looks like this issue already fixed/merged by  #1899. Do you have any plans for creating release?

**Comment by xabbuh** [comment]
I think currently #1961 is a blocker for the next release.

**Comment by vkhramtsov** [comment]
@xabbuh Looks like #1961 resolved now. How about release? :wink:
