### ISSUE TITLE
Serialize FormView

### ISSUE THREAD

**Issue by onEXHovia** [FriendsOfSymfony/FOSRestBundle#1957]
Hi!
I'm used https://github.com/FriendsOfSymfony/FOSCommentBundle and handle json response. But when configured with serializer `fos_rest.serializer.symfony` `FormView` object practical empty.

For example call method https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Controller/ThreadController.php#L191

Configuration with symfony:
```
fos_rest:
    service:
        serializer: fos_rest.serializer.symfony
```
![2018-11-14 12 39 06](https://user-images.githubusercontent.com/3332033/48467311-53520000-e80a-11e8-9e82-9935381e85b1.png)

Configuration with JMS:
```
fos_rest:
    service:
        serializer: fos_rest.serializer.jms
```
![2018-11-14 12 40 36](https://user-images.githubusercontent.com/3332033/48467379-81374480-e80a-11e8-9eba-cd9faf48d5ef.png)

How to solve this problem? In the project I use only symfony serializer.

**Comment by LukeMcDonnell** [comment]
@onEXHovia 

Did you ever find a solution to this? Other than switching to JMS serializer?

I'm experiencing the same issue.
