### ISSUE TITLE
Undefined class constant DIRECTION_SERIALIZATION

### ISSUE THREAD

**Issue by pdias** [FriendsOfSymfony/FOSRestBundle#1961]
The change in ExceptionHandler from JMS\Serializer\GraphNavigator to JMS\Serializer\GraphNavigatorInterface will originate this error:

> Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError
>   : Undefined class constant 'DIRECTION_SERIALIZATION' in D:\wamp\www\api\ven
>   dor\friendsofsymfony\rest-bundle\Serializer\Normalizer\ExceptionHandler.php
>   :29

Thanks,
Paulo

**Comment by xabbuh** [comment]
fixed in #1962
