### ISSUE TITLE
JMSSerializerAdapter is accessing private property of JMS\Serializer\Context

### ISSUE THREAD

**Issue by RoYaLBG** [FriendsOfSymfony/FOSRestBundle#1975]
Hello,

I have the following dependencies:

```
        "friendsofsymfony/rest-bundle": "^2.4",
        "jms/serializer": "^2.0",
```

Note: Using `jms/serializer` instead of `jms/serializer-bundle` because after `composer install` finishes it gives error of incompatible serializer classes (in one of the issues here it is mentioned to use `jms/serializer`)

But, it gives me an error that the adapter is accessing a private property, which is, in fact, true. 

The class `JMS\Serializer\Context` in version 2 and above has switched the property `$attributes` from public to private, yet `FOS\RestBundle\Serializer\JMSSerializerAdapter` in version 2.4 tries to access it on line 98:

```
        foreach ($context->getAttributes() as $key => $value) {
            $jmsContext->attributes->set($key, $value);
        }
```

**Comment by GuilhemN** [comment]
This has been fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1899, thanks!
