### ISSUE TITLE
Proposal: StatusCode annotation

### ISSUE THREAD

**Issue by ossinkine** [FriendsOfSymfony/FOSRestBundle#1984]
Now if you want to return a custom status code, you must either return the View object with the status code, or add a View annotation with the status code. Both solutions are not very elegant. The View annotation requires the installation of SensioFrameExtraBundle and Twig, although they are not needed in the project. Creating a View object in the controller looks cumbersome.
I propose to do something like this:
```php
class ApiController
{
    /**
     * @StatusCode(201)
     */
    public method createItem(Item $item): void
    {
        $this->persist($item);
    }
}
```

**Comment by GuilhemN** [comment]
I'm afraid it would add one more thing to maintain with no much gain.
Isn't calling `AbstractFOSRestController::view()` good enough ?

**Comment by ossinkine** [comment]
@GuilhemN It is certainly enough, but I would like the controller code to be cleaner and do one thing (instead of persisting the object and preparing the view).

**Comment by Tobion** [comment]
Closing as I think this is a bad idea. If something fails like `persist` call in your example. The return status code is not 201 as it seems from the annotation. Returning the view with the status code after the fact seems more logical to me.
