### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by metalmini** [FriendsOfSymfony/FOSRestBundle#1989]
SF4 is out for quite some time, it would be allot easier for beginners to start with documentation that results in something that works.

**Comment by metalmini** [comment]
I am willing to help and maintain the docs, or at least get them to a point that we can all agree on.

**Comment by xabbuh** [comment]
If there's anything that needs to be updated, I will happily review a PR. :)

**Comment by metalmini** [comment]
Have not created a PR but first thing that i ran into was deprecation of FOSRestController.

**Comment by Tobion** [comment]
There are indeed some mentions still in the doc about the deprecated `FOSRestController`. @metalmini  do you want to create a PR?

**Comment by W0rma** [comment]
> There are indeed some mentions still in the doc about the deprecated FOSRestController

Seems like this has already been fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2001

Should this issue be closed?

**Comment by Tobion** [comment]
FOSRestController isn't mentioned anymore indeed.
