### ISSUE TITLE
Deprecate symfony/templating

### ISSUE THREAD

**Issue by phoenixgao** [FriendsOfSymfony/FOSRestBundle#2002]
After upgrading to Symfony 4.3 we're getting a lot of symfony/templating component related deprecation notice in FOSRestBundle.

`symfony/templating` is deprecated in Symfony 4.3 and will be removed in Symfony 5.0
https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration.

**Comment by Tobion** [comment]
IMO we should try not to depend on twig or templating which should be possible with https://github.com/symfony/symfony/pull/31065 in sf 4.4 and which then also makes use of https://tools.ietf.org/html/rfc7807
