### ISSUE TITLE
circular reference in Symfony request object

### ISSUE THREAD

**Issue by m2broth** [FriendsOfSymfony/FOSRestBundle#2003]
I reproduced this issue on Symfony test project with installed fosrest bundle. I've faced with a strange behavior when tried clearing cache or just var_dump Request $request object from the controller action - it takes ages to generate response and fails with a memory error. I suppose there is some circular reference issue In the ParamListener. When I remove paramListener from the request->attributes collection - everything is fine. Have you faced with such issue?

**Comment by m2broth** [comment]
The issue is related to the $container property of ParamListener class. It takes a lot of memory when serializing container object with enabled forest bundle

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce the issue?

**Comment by m2broth** [comment]
Just install Symfony web application based project from scratch, install for_rest bundle, enable param_fetcher_listener and try to var_dump $request object from any controller action.

**Comment by m2broth** [comment]
The real issue in the Symfony validator component. I'm investigating it now. Don't know the reason. Fosrest bundle doesn't make any performance problem The issue is reproduced without fosrest bundle too

**Comment by Tobion** [comment]
Closing as the ticket is unclear without reproducer.
