### ISSUE TITLE
Hidden dependencies: "symfony/form" and "symfony/serializer" components

### ISSUE THREAD

**Issue by iraklialaverdashvili** [FriendsOfSymfony/FOSRestBundle#2009]
Hi, I am using the rest-bundle and getting errors in prod
`PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class Symfony\\Component\\Serializer\\Normalizer\\NormalizerInterface not found in /xxx/vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/FormErrorNormalizer.php:22`

In the FormErrorNormalizer.php file I see this:
`use Symfony\Component\Form\FormInterface;`
`use Symfony\Component\Serializer\Normalizer\NormalizerInterface;`

And in the composer.json `"symfony/form"` and `"symfony/serializer"` are under require-dev node.

Could you please look at this?
Thank you

**Comment by xabbuh** [comment]
This is a bug in PHP. You need to update it.

**Comment by iraklialaverdashvili** [comment]
This is not a bug, it's true that the different versions of php are handling it in a different way, but the code is using interfaces from Symfony components that are not declared as dependencies (for production environment).
I think that if anyone is implementing interfaces in his code, these interfaces must exist, no matter what version of php is used.

**Comment by xabbuh** [comment]
It is a PHP bug (see symfony/symfony#32395 for more context). With PHP 7.2.21 and 7.3.8 this will work as expected again.

**Comment by iraklialaverdashvili** [comment]
Yes, I've seen the thread already, and pull requests to move dependencies from dev to prod also. And nikic is explaining correctly the problem in his example, but...
Why not require dependencies before using them? Is there any problem to having this components installed?
The point is that there are live websites using this vendor that stop working after updates, and developers have to spend time, maybe hours to find the problem and solve it.

**Comment by xabbuh** [comment]
If we moved the packages from `require-dev` to `require`, this would mean that everyone got those packages installed even if they where not using any of the related features. That would mean having more dependencies installed you need to check for updates, security issues etc.

**Comment by Tobion** [comment]
Those are optional dependencies which are only required depending on what features you need. It would be better to create a separate package for those things with explicit dependencies. But that's the way it is currently and makes maintainance easier. We should throw an explicit error suggesting to install symfony/form if you enable something is requires forms and have no installed it.

@iraklialaverdashvili what does your fos_rest config look like?
