### ISSUE TITLE
VIewHandler can't accept Twig in Symfony 4.3 and beyond

### ISSUE THREAD

**Issue by sarcher** [FriendsOfSymfony/FOSRestBundle#2020]
After upgrading to Symfony 4.3, it appears impossible to both avoid deprecation notices and use Twig as the default render engine for the `ViewHandler` class. This message is seen:

> An instance of Symfony\Component\Templating\EngineInterface must be injected in
> FOS\RestBundle\View\ViewHandler to render templates.

Since the constructor for `ViewHandler` type hints an `EngineInterface` , the following configuration will fail because Twig is now an instance of `Twig\Environment`:

```
fos_rest:
    service:
        templating: twig
```

One workaround is to extend the `ViewHandler` class and then replace the default implementation, but this seems like an ugly necessity to use things in their (more or less) default setup. 

So, either I am missing something, or there needs to be a fix here. My best guess would be to remove the type hint and add a check to see that the injected object is either `Twig\Environment` or an instance of `EngineInterface` or `null`. 

I feel like I am missing something, though, since this was not mentioned in the other deprecation fixes. Is there another solution here?

**Comment by maxhelias** [comment]
Is your issue not related to this PR #2012 ? Or it's an other issue ?

**Comment by sarcher** [comment]
Apologies, I should have mentioned this is occurring against the current master:
https://github.com/FriendsOfSymfony/FOSRestBundle/commit/e1f91266ca37e423dfae9ec4e641b247fdb2915d

So, this is after that PR has been applied.

**Comment by isakrubin** [comment]
Same issue, using dev-master and ViewHandler still type-hints "EngineInterface $templating = null" :/

**Comment by sarcher** [comment]
This was closed by #2022
