### ISSUE TITLE
Unable to use fos rest without twig for a json api

### ISSUE THREAD

**Issue by nachocifu** [FriendsOfSymfony/FOSRestBundle#2021]
Im developing a json rest api. 
Fos rest keeps throwing the following error: 

> [critical] Uncaught Exception: An instance of Symfony\Component\Templating\EngineInterface must be injected in FOS\RestBundle\View\ViewHandler to render templates.

Specs:
Symofny 4.3
FosRest: dev-master

**Comment by sarcher** [comment]
This is the issue I reported in #2020; I am working to try to figure out a fix, but fear that it requires a larger view of the codebase than I have.

**Comment by sarcher** [comment]
I can't close this, but it was fixed in #2022
