### ISSUE TITLE
Upgrade to Symfony 4.4.x causes - The "controller_name_converter" service is deprecated since Symfony 4.3

### ISSUE THREAD

**Issue by treadmillian** [FriendsOfSymfony/FOSRestBundle#2030]
`1x: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.
        1x in JsonControllerTest::setUp from App\Tests\Controller\Api\V1`

**Comment by maxhelias** [comment]
See #2032

**Comment by W0rma** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2074

**Comment by enumag** [comment]
@xabbuh This error started to appear again with dev-master. Previously I fixed it using

```
fos_rest:
    routing_loader:
        parse_controller_name: false
```

but now this option is invalid so I can't suppress it.

**Comment by xabbuh** [comment]
Can you debug where the service is actually used?

**Comment by enumag** [comment]
It's not easy... Also I'm getting more deprecations now. But I'm not using any of these on purpose so it must be some internal thing in your bundle. What do I need to disable to get rid of them?

```
  1x: The FOS\RestBundle\Routing\RestRouteCollection class is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\ClassResourceInterface is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Controller\Annotations\NamePrefix annotation is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Controller\Annotations\Prefix annotation is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.directory service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\DirectoryRouteLoader class is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.processor service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\RestRouteProcessor class is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.controller service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\RestRouteLoader class is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.reader.controller service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\Reader\RestControllerReader class is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.reader.action service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\Reader\RestActionReader class is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.inflector.doctrine service is deprecated since FOSRestBundle 2.8.
  1x: Not passing an instance of FOS\RestBundle\Routing\Loader\Reader\RestControllerReader as the 3rd argument of FOS\RestBundle\Routing\Loader\RestRouteLoader::__construct() is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.yaml_collection service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\RestYamlCollectionLoader class is deprecated since FOSRestBundle 2.8.
  1x: The fos_rest.routing.loader.xml_collection service is deprecated since FOSRestBundle 2.8.
  1x: The FOS\RestBundle\Routing\Loader\RestXmlCollectionLoader class is deprecated since FOSRestBundle 2.8.
```

**Comment by xabbuh** [comment]
You need to disable the automatic route generation feature:

```yaml
fos_rest:
    routing_loader: false
```

**Comment by enumag** [comment]
But what do I use instead of it?

```
Symfony\Component\Config\Exception\LoaderLoadException
Cannot load resource "@ApiBundle/Controller". Make sure the "ApiBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@ApiBundle/Controller" is not empty.
```

**Comment by enumag** [comment]
I'm guessing that the problem now is using `type: rest` in routing.yml:

```
api:
  resource: '@ApiBundle/Controller'
  type: rest
  prefix: /crm/api/v{version}
  requirements: { version: '\d+\.\d+' }
```

What should I change this to?

**Comment by enumag** [comment]
Btw. can you create a 2.8 branch? Master is already 3.0-dev but 2.8 branch doesn't exist...

**Comment by xabbuh** [comment]
There won't be any REST-specific loader anymore. You will need to configure the routes explicitly (the method specific annotations `@Get`, `@Post` and so on won't be removed and will be handled by Symfony's annotation loader).

If you still would like to use this feature, you will have to wait a bit to be able to use the new FOSRestRoutingBundle @alexander-schranz is currently working on.

> Btw. can you create a 2.8 branch? Master is already 3.0-dev but 2.8 branch doesn't exist...

The `2.x` branch mirrors the 2.8 development. We set up a branch alias so requiring something like `^2.8@dev` will bring you the latest development version of 2.8.

**Comment by enumag** [comment]
> the method specific annotations @Get, @Post and so on won't be removed and will be handled by Symfony's annotation loader

Does that mean I can simply change `type: rest` to `type: annotation`?

> The `2.x` branch mirrors the 2.8 development.

There is no 2.x branch.

**Comment by xabbuh** [comment]
Yes, that should work.

**Comment by enumag** [comment]
Looks like I have to remove `@NamePrefix` and add the prefix to each route manually.

**Comment by alexander-schranz** [comment]
> Does that mean I can simply change type: rest to type: annotation?

@enumag it depends on your controller how did you define it. If you did use the `implements ClassResourceInterface` which automatically generates routes by the public functions like `getAction`, `postAction`, `*Action` this will not work with the `annotation` route loader.

This automatic route generation is moved to [FOSRestRoutingBundle](https://github.com/handcraftedinthealps/FOSRestRoutingBundle/pull/1). 

> Looks like I have to remove @NamePrefix and add the prefix to each route manually.

Symfony supports the name prefix also in your route definition:

```yaml
api:
  resource: '@ApiBundle/Controller'
  type: annotation
  prefix: /crm/api/v{version}
  requirements: { version: '\d+\.\d+' }
  name_prefix: 'api_bundle.'
```
