### ISSUE TITLE
Symfony 4.4 compatibility: use Either ErrorListener or ExceptionListener

### ISSUE THREAD

**Issue by bendavies** [FriendsOfSymfony/FOSRestBundle#2031]
This bundle currently has integration with with the symfony `ExceptionListener` here:

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/7705fa0af878f28d56a182dea4f18c1e0ab9cbbb/EventListener/ExceptionListener.php

In symfony 4.4 this class is [deprecated](https://github.com/symfony/symfony/blob/a8a9e69488fdaf609fecacba66e056ffb8f25da8/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php#L28) in favor of [ErrorListener](https://github.com/symfony/symfony/blob/a8a9e69488fdaf609fecacba66e056ffb8f25da8/src/Symfony/Component/Console/EventListener/ErrorListener.php).

A [Compiler Pass](https://github.com/symfony/symfony/blob/a8a9e69488fdaf609fecacba66e056ffb8f25da8/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExceptionListenerPass.php) is used to use either one or the other.

This bundle needs support for both eventualities/listeners.

**Comment by maxhelias** [comment]
Should be fixed by #2025

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2025

**Comment by bendavies** [comment]
That PR does not resolve the issue. please reopen.

**Comment by xabbuh** [comment]
Can you provide some more information on what happens?

**Comment by bendavies** [comment]
[This](https://github.com/symfony/symfony/blob/475967cbc1dd943911fa21cff7ad075760c009f4/src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php#L104) is converting the Exception to a FlattenedException, because the parameter [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/6c33b4d0caf2e04d875b79f9cbbb07dc16397ae2/Controller/ExceptionController.php#L65) has no type.

Which results in a type error [here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/6c33b4d0caf2e04d875b79f9cbbb07dc16397ae2/Controller/ExceptionController.php#L102):
`TypeError: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::getStatusCode() must be an instance of Exception, instance of Symfony\Component\ErrorHandler\Exception\FlattenException given`

Adding a type to [$exception](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/6c33b4d0caf2e04d875b79f9cbbb07dc16397ae2/Controller/ExceptionController.php#L65) would fix it.

But like i said in OP, 

This bundle is uses the deprecated [ExceptionListener](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/6c33b4d0caf2e04d875b79f9cbbb07dc16397ae2/EventListener/ExceptionListener.php#L39) 

In symfony 4.4 this class is [deprecated](https://github.com/symfony/symfony/blob/a8a9e69488fdaf609fecacba66e056ffb8f25da8/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php#L28) in favor of [ErrorListener](https://github.com/symfony/symfony/blob/a8a9e69488fdaf609fecacba66e056ffb8f25da8/src/Symfony/Component/Console/EventListener/ErrorListener.php).

This bundle needs to detect if the consumer is using either `Symfony/Component/HttpKernel/EventListener/ExceptionListener` or `Symfony/Component/Console/EventListener/ErrorListener`, and use the same. It will always be one or the other

**Comment by bendavies** [comment]
related, since this bundle now supports symfony 5, [this](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/6c33b4d0caf2e04d875b79f9cbbb07dc16397ae2/EventListener/ExceptionListener.php#L39) is totally broken since the class doesn't exist.

**Comment by yceruto** [comment]
Yes, I can confirm that https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2025 does not work in 5.0 and triggers another deprecation on 4.4. The ExceptionListener was deprecated while PR was alive.

I will try to rework it this weekend.

**Comment by yceruto** [comment]
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2036

**Comment by seddighi78** [comment]
how to fix this problem in Symfony 4.4?

**Comment by yceruto** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2036 already fix this problem on 4.4

**Comment by emimarz** [comment]
when going to merge it? because I have the same error

**Comment by emimarz** [comment]
are there a work around for this? meanwhile

**Comment by The-Don-Himself** [comment]
> are there a work around for this? meanwhile

@emimarz this hack seems to solve it for me and a few others on Symfony 4.4

https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2036#issuecomment-569602695
