### ISSUE TITLE
ruflin/elastica removed type

### ISSUE THREAD

**Issue by aequasi** [FriendsOfSymfony/FOSRestBundle#2034]
https://github.com/ruflin/Elastica/commit/997989426dc37a1f4d103f477222869b7b6a87ab

This breaks the Elastica/Index override class causing exceptions

**Comment by xabbuh** [comment]
Was this meant to be opened in the FOSElasticaBundle repository?

**Comment by aequasi** [comment]
Yes... I’m not sure how it got here, and I couldn’t find it after I closed the tab! Thanks.... haha

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
