### ISSUE TITLE
composer require fails with Symfony 5.0

### ISSUE THREAD

**Issue by oheins** [FriendsOfSymfony/FOSRestBundle#2043]
```
$ composer require friendsofsymfony/rest-bundle:dev-master 
[...]
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service "routing.loader" has a dependency on a non-existent service "co  
!!    ntroller_name_converter".                                                    
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
```

This seems to be fixed in #2036; however, this is not merged yet.

**Comment by maxhelias** [comment]
Be patient and use a stable tag rather than dev-master

**Comment by Yozhef** [comment]
up

**Comment by wumke** [comment]
> Be patient and use a stable tag rather than dev-master

Anyone has an idea when 2.7 is expected to be released as stable?

**Comment by derWebdesigner** [comment]
+1

**Comment by gvanbeck** [comment]
+1

**Comment by Josee9988** [comment]
At least you can download it in the dev version, but when will this version be available as stable??
```json
    "minimum-stability": "dev",
```

**Comment by derWebdesigner** [comment]
@Josee9988 You can't anymore if I understood the last merges correctly because the dev version is now only compatible with Symfony 4.4 and Symfony 5 should be fixed in a 3.x branch. I would love to know an ETA for this as well but currently, there is none I guess?

**Comment by Webonaute** [comment]
This is a big blocker for my team. I would love to know a schedule for this. Thank.

**Comment by derWebdesigner** [comment]
@Webonaute Same to me and I would love to help somehow with a fast solution for 3.x but I am simply lacking in knowledge.

**Comment by wumke** [comment]
I agree with the fact that not being Symfony 5 compatible is a big blocker for everyone that starts using Symfony at its current version (and for those who want to update to latest version). 
The 3.x branch should be created as soon as possible, with the compatibility changes of the mentioned PR included.

**Comment by xabbuh** [comment]
I talked a bit with @yceruto about this. Dropping support for Symfony 4 in version 3 of FOSRestBundle is probably not the best idea. It makes updating harder and more importantly increases the maintenance overhead as doing support for 2.x would only be possible once Symfony 4.4 reaches end of life. That being said a better solution would probably be to deprecate all features that cannot be supported with Symfony 4 and 5 in 2.x and then remove them in 3.0 while keeping support for both Symfony 4.4 and 5.0.

**Comment by xabbuh** [comment]
Additionally 2.x could then go into a maintenance-only mode meaning that it would only receive bugfixes, but new features would only be added in 3.x.

**Comment by derWebdesigner** [comment]
@xabbuh Actually that sounds like a really good idea and totally makes sense Christian, especially because 4.4 is an LTS version.

**Comment by Josee9988** [comment]
Can I use FosRestBundle with 4.4 or 5? Or not yet?

**Comment by Saracevas** [comment]
> Can I use FosRestBundle with 4.4 or 5? Or not yet?
@Josee9988 not yet, no.

**Comment by Yozhef** [comment]
@Saracevas @Josee9988  - why not use in 4.4? For Symfony 5 not work integration but in 4.4 all good work

**Comment by Josee9988** [comment]
@Yozhef I tried to use it in 4.4 and couldn't use any functions from the AbstractFosController so I had to do it all by myself. It was the first time I used symfony and FOS so maybe I did something wrong but I don't think so.
Cheers

**Comment by Yozhef** [comment]
@Josee9988 now I have a project in Symfony 4.4 and normal work. I very wait wen bundle start support Symfony 5 =)

**Comment by wumke** [comment]
@The Package Maintainers:
So, what is the final plan regarding to FOSRest package version numbers and Symfony version compatability? 

If not decided yet, can we at least have a new 'Symfony5Compatible' branch so that people using Symfony5 can make changes, test and create pull requests?

If there is a final plan, I'd suggest to place it in the readme... that avoids a lot of 'not Symfony X compatible' issues!

**Comment by Yozhef** [comment]
@stof any news? This package really blocked migrate to Symfony 5 in Installs: 22 062 486 users.

**Comment by xabbuh** [comment]
I have just tagged the 2.7.0 release which is compatible with Symfony 4.4.

The `master` now serves for the development of FOSRestBundle 3.0. Its version constraints already allow Symfony 5 components. I invite you to test your application with that branch, but be prepared that features that are not compatible with Symfony 5 will error in some way.

As explained in https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2043#issuecomment-576413826 we will need to deprecate some features in the `2.x` branch for FOSRestBundle 2.8 that are not compatible with Symfony 5 and remove them in 3.0. I invite everyone to help us reach this goal.

**Comment by QuentinNanomonx** [comment]
For the ones waiting for SF5 support, you can follow the team progress through [3.0 milestone](https://github.com/FriendsOfSymfony/FOSRestBundle/milestone/9)
I've tested it on my project and everything is good so far with SF5!
I don't say that it will be fine for everyone, but you might give it a try ;-)

**Comment by Yozhef** [comment]
@stof @lsmith77 When 3.0 planned release, in my team 4 service are written in Symfony 5 and everything works fine. You might make a release, because my service with dev-master dependency, not a good idea.

**Comment by patrick-mcdougle** [comment]
I trust the maintainers to release when it's ready not when any arbitrary project is successful on master. If you're not going to contribute, just be patient and wait for the 3.0 stable release. (Thanks for your hard work maintainers, don't let the impatient pressure you to release before it's time)

That being said, seeing that the [milestone for 3.0](https://github.com/FriendsOfSymfony/FOSRestBundle/milestone/9) is 100% is there anything I can do to help get this over the finish line?

**Comment by xabbuh** [comment]
Thank you for your kind words @patrick-mcdougle. The plan is to release 2.8 and 3.0 at the same time. For 2.8 I would like to merge https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2109 as the last change. The patch itself looks good, but I think we need to rework the tests as they still pass when the changes to the event listener are reverted.

**Comment by jawira** [comment]
For the **really** impatient people, release **3.0.0-beta3** is available.

**Comment by jawira** [comment]
Well, **v3.0.0** is out!
