### ISSUE TITLE
changed default behavior for "serialize_null" configuration inside 2.x branch

### ISSUE THREAD

**Issue by Haehnchen** [FriendsOfSymfony/FOSRestBundle#2044]
We did update some projects for Symfony 4.4, but by this we also updated this bundle. This changed json responses; now null values are getting filtered. This was not expected for 2.5.0 => 2.6.0.

The default of this bundle was never different but did not working so fare:

```
    serializer:
        serialize_null:       false
```

So the default configuration is now working via the fix:

- https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1996
- https://github.com/FriendsOfSymfony/FOSRestBundle/issues/922
- https://github.com/FriendsOfSymfony/FOSRestBundle/commit/54758949bff9fc520997415341323eebf3f54892

Maybe there should the consideration to change the default value inside 2.x and provide it correct inside 3.x.

**Comment by Tobion** [comment]
Since the change is released quite awhile now, I think there is no point in changing the behavior again. This might just break things again for others. Also this only seems to affect the symfony serializer not the jms one.
