### ISSUE TITLE
Bug after update of SensionFrameworkExtraBundle (5.5) 

### ISSUE THREAD

**Issue by ClementVincent** [FriendsOfSymfony/FOSRestBundle#2045]
Hi guys !

I have some issues with my symfony project since few months. I have posted a message on  SensionFrameworkExtraBundle but since noone answered yet, I'm posting here a link to the original question : 
https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/649

So far the workaround seems to be to downgrade the version of SensionFrameworkExtraBundle but it could be cool if someone has an idea to solve this.

Tanks ! :)

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce the issue?

**Comment by Tobion** [comment]
Closing as there is discussion on the original ticket.
