### ISSUE TITLE
Notice: Undefined offset: 0

### ISSUE THREAD

**Issue by AzRunRCE** [FriendsOfSymfony/FOSRestBundle#2075]
Hello everybody, i have a misstake with FOSRestBundle.
I have recently upgrade to symfony 4.4 from 4.1 and now every endpoint return me an error 500 with this message 

> Notice: Undefined offset: 0
> "file": "G:\\Users\\Utilisateur\\Documents\\TheStadium_Back\\vendor\\friendsofsymfony\\rest-bundle\\EventListener\\ViewResponseListener.php", "line": 99,

I'm not a expert in symfony maybe i have misconfigured something but i don't know what.

- php 7.3.8,
- "friendsofsymfony/rest-bundle": "^2.7",[ (with the default yaml conf)](https://pastebin.com/raw/GXc8GHWa)
- "sensio/framework-extra-bundle": "^5.5",

thank for reading. have a nice day

**Comment by xabbuh** [comment]
see sensiolabs/SensioFrameworkExtraBundle#649

**Comment by Tobion** [comment]
Fixed by #2097
