### ISSUE TITLE
Feature or bug? Can't see relevant error messages when not in debug mode.

### ISSUE THREAD

**Issue by ericc06** [FriendsOfSymfony/FOSRestBundle#2086]
Seen with SF 4.4.3 / FOSRest 2.6.0

Working on a REST API, using QueryParam to validate GET values with requirements.
When not in debug mode (i.e. when APP_DEBUG=0), and if an invalid value is given in the query string as regards the requirements, the JSON response I receive is:

```
{
    "code": 400,
    "message": "Bad Request"
}
```

whereas I'd like to read a more relevant error message, as seen in debug mode (i.e. when APP_DEBUG=1), for example :

```
{
    "code": 400,
    "message": "Parameter \"limit\" of value \"AAA\" violated a constraint \"Parameter 'limit' value, does not match requirements '\\d+'\""
}
```

or, even better using [this feature](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1015), some custom error message such as:

```
{
    "code": 400,
    "message": "Parameter \"limit\" of value \"AAA\" violated a constraint \"'limit' must be an integer greater than 0\""
}
```

But relevant messages are only sent when in debug mode (APP_DEBUG=1).
Is it the expected behavior?

If so, what can we do to send relevant error messages when not in debug mode?

As an example, here is one of my QueryParam's:

     * @Rest\QueryParam(
     *     name="limit",
     *     requirements={
     *         "rule" = "\d+",
     *         "error_message" = "'limit' must be an integer greater than 0"
     *     },
     *     strict=true,
     *     nullable=true,
     *     description="(optional) Max number of products per page."
     * )

And my config file (fos_rest.yaml) :

```
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: true
        formats: { json: true, xml: false, rss: false }
    serializer:
        serialize_null: true
    exception:
        enabled: true
        codes:
            {
              App\Exception\ResourceValidationException: 400,
              App\Exception\ResourceNotFoundException: 404,
              App\Exception\ResourceAccessNotAuthorized: 403,
              App\Exception\LimitOrPageLogicException: 400,
              App\Exception\PageOutOfRangeException: 404
            }
        messages:
            {
              App\Exception\ResourceValidationException: true,
              App\Exception\ResourceNotFoundException: true,
              App\Exception\ResourceAccessNotAuthorized: true,
              App\Exception\LimitOrPageLogicException: true,
              App\Exception\PageOutOfRangeException: true
            }
```

**Comment by Tobion** [comment]
You need to add BadRequestHttpException to your exception.messages config. Otherwise the error messages are not shown in non-debug for security reasons.

**Comment by ericc06** [comment]
Hi Tibion,
Thank you very much, but I can't make it work.

Here's my code:

```
fos_rest:
    ...
    exception:
        enabled: true
        messages:
            { App\Exception\BadRequestHttpException: true }
```


I created App\Exception\BadRequestHttpException.php:

```
<?php

namespace App\Exception;

class BadRequestHttpException extends \Exception
{
}
```

In my controller:

```
    /**
     * @Rest\Get("/end-users", name="end_user_list")
     (...)
     * @Rest\QueryParam(
     *     name="limit",
     *     requirements={
     *         "rule" = "\d+",
     *         "error_message" = "'limit' must be an integer greater than 0"
     *     },
     *     strict=true,
     *     nullable=true,
     *     description="(optional) Max number of products per page."
     * )
     (...)
     * @Rest\View
     */
    public function list(ParamFetcherInterface $paramFetcher)
    {
        (...)
```

And when I send this:

`GET https://<domain>/api/end-users?limit=ABC`

I still receive this response:

```
{
    "code": 400,
    "message": "Bad Request"
}
```

when I'd like to receive this one:

```
{
    "code": 400,
    "message": "Parameter \"limit\" of value \"ABC\" violated a constraint \"'limit' must be an integer greater than 0\""
}
```

I must be missing something...
All I want to do is send in the JSON response the content of the 'error_message' defined in the QueryParam, without having to throw my custom exception in the controller code.

**Comment by Tobion** [comment]
You must list the exception that is thrown in exception.messages. This is very likely not your custom `App\Exception\BadRequestHttpException`
but https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Exception/BadRequestHttpException.php

**Comment by ericc06** [comment]
Hi Tobion,
I tried this, without success:

```
fos_rest:
    exception:
        enabled: true
        messages:
            { Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true }
```

**Comment by Tobion** [comment]
Just debug which exception class is thrown for the error. It could also be some exception from the validator component. When it works for your `App\Exception\LimitOrPageLogicException` that you already configured, I don't see why it should not work for the param fetcher in principle.

**Comment by ericc06** [comment]
OK, I'll try to debug the thrown exception.
As regards my LimitOrPageLogicException, I explicitly throw it in my code:

```
<?php

namespace App\Repository;

use App\Exception\LimitOrPageLogicException;
(...)

abstract class AbstractRepository extends EntityRepository
{
    protected function paginate(QueryBuilder $qb, $limit, $page)
    {
        if (!(filter_var($limit, FILTER_VALIDATE_INT) && 0 < $limit)) {
            $message = '$limit must be an integer greater than 0.';

            throw new LimitOrPageLogicException($message);
        }
        (...)
```

This is not the case for my QueryParam error_message.
I'd like the param fetcher to do the job for me in production mode, if possible, as it does in debug mode.
Else, I'd have to give up the idea of using QueryParam error_message and throw my own exceptions, as I did for LimitOrPageLogicException.

**Comment by Tobion** [comment]
Closing due to missing information.
