### ISSUE TITLE
RestActionReader ignoring user interface in 2.7.0

### ISSUE THREAD

**Issue by wickedOne** [FriendsOfSymfony/FOSRestBundle#2090]
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2024 introduced ignoring the UserInterface class as controller argument
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ab328c73cadc1ee7a102bd4b6a90af5a3b213c10/Routing/Loader/Reader/RestActionReader.php#L532-L540

this breaks all configured children from a ``something_user_route`` parent because ignoring it will cause the following condition to be false
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ab328c73cadc1ee7a102bd4b6a90af5a3b213c10/Routing/Loader/Reader/RestActionReader.php#L275
and without a singular name all children will trigger this exception
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ab328c73cadc1ee7a102bd4b6a90af5a3b213c10/Routing/Loader/Reader/RestActionReader.php#L255

i do think it's fairy common to have a user entity to be part of a restful path?

anyway, any suggestions how to work around this issue without having to refactor a large amount of controllers?

**Comment by Tobion** [comment]
Another edge cases speaking in favor of #1954.

**Comment by wickedOne** [comment]
for now, wouldn't it make more sense to use a property & setter for ``ignoredClasses`` in the ``RestActionReader`` so at least they can be overridden?

**Comment by Tobion** [comment]
Yes that could be a workaround for now. Feel free to create a PR.

**Comment by wickedOne** [comment]
here you go: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2091
