### ISSUE TITLE
Not working Exception Handling in ExceptionController with PHP 7

### ISSUE THREAD

**Issue by MissbachMichael** [FriendsOfSymfony/FOSRestBundle#2095]
Please fix the bug:
php.CRITICAL: Uncaught Error: Argument 3 passed to FOS\RestBundle\Controller\ExceptionController::getTemplateData() must be an instance of Exception, instance of TypeError given, called in /var/www/html/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 74
It´s already reported in https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2092 after it was closed.

**Comment by faresk93** [comment]
I'm getting the same error.
Previously this error was being launched in the getStatusCode() method. Now it's the getTemplateData().

**Line 69**: `vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php`

`    if ($exception instanceof \Exception) {
            $code = $this->getStatusCode($exception);
        } else {
            $code = $this->getStatusCodeFromThrowable($exception);
        }`

The latest release **2.7.1** has made some improvements to check the exception instance in the showAction() method but apparently it has forgot to handle the getTemplateData() method requiring an \Exception Type as a 3rd parameter 
`(public function getTemplateData($currentContent, $code, \Exception $exception, DebugLoggerInterface $logger = null)`

For the moment, and as temporary workaround for this issue, I'm using a custom exception controller similar to the original fos_rest controller while avoiding this conflict !

**Comment by MissbachMichael** [comment]
And please don´t forget to fix the method call on function "createView".

**Comment by GuigZ-** [comment]
Pr #2096 is now ok, i wait feedback from fos team :)

**Comment by xabbuh** [comment]
@MissbachMichael @faresk93 Can you both confirm that the current `2.7` branch after #2096 being merged fixes your issue? If yes, I will tag a new bugfix release later today.

**Comment by faresk93** [comment]
I believe this hasn't solved the problem yet !
I got another exception related to **jms-serializer**

![image](https://user-images.githubusercontent.com/12989345/75664748-44979280-5c73-11ea-85ff-11b50e99ea0f.png)

**Comment by xabbuh** [comment]
@faresk93 Thank you for the feedback. Please ping me if I can help you or when you need some feedback.

**Comment by faresk93** [comment]
I created I pull request fixing this issue @xabbuh 
#2104
