### ISSUE TITLE
Naming convention for entities with two words

### ISSUE THREAD

**Issue by log0** [FriendsOfSymfony/FOSRestBundle#212]
I know the naming convention about the FOSRestBundle, suppose I have the entity call "EmployeeAccountNumber", how could I make it so such that the route path doesn't resolve into "employeeaccountnumber" but rather "employee_account_number" or "employee_account_numbers" or anything custom?

**Comment by blaugueux** [comment]
I have the same issue. Any chance to see this supported ?

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954
