### ISSUE TITLE
Composer 1.10 invalid PSR-4 autoloaded class

### ISSUE THREAD

**Issue by michaljusiega** [FriendsOfSymfony/FOSRestBundle#2129]
After new version of composer to 1.10, and running: 

`composer dump-autoload --optimize --no-dev --classmap-authoritative`

i get:

`Deprecation Notice: Class FOS\RestBundle\Examples\RssHandler located in ./vendor/friendsofsymfony/rest-bundle/Resources/doc/examples/RssHandler.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185`

**Comment by xabbuh** [comment]
Thank you for reporting this. I don't think this will be an issue when Composer 2 is released as this is only code that is part of the documentation. But we could still look into whether we will be able to silence the message.

**Comment by xabbuh** [comment]
see #2130

**Comment by michaljusiega** [comment]
Thank you.
