### ISSUE TITLE
"The template should be a string or extend TemplateReference"

### ISSUE THREAD

**Issue by titomiguelcosta** [FriendsOfSymfony/FOSRestBundle#216]
I'm using symfony 2.1-dev and just after i run an update of the project using composer, now i get the error "The template should be a string or extend TemplateReference". I check that the error occur in file vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php, line 177. The argument $template is an instance of Template, not TemplateReference, and the value of the property template is NULL. I'm using annotations to specific the template and return an array(). In my template i use block and the twig tag render and include. If i return a response on the controller, no problem.

**Comment by bassrock** [comment]
I just started seeing this issue today with the new Sensio Framework bundle v3.0.13.

**Comment by pculka** [comment]
Also, happened since yesterday. Test builds are failing, Sensio Framework bundle v3.0.13 aswell

**Comment by pculka** [comment]
v3.0.12 works fine . https://github.com/sensiolabs/SensioFrameworkExtraBundle/compare/v3.0.12...v3.0.13

**Comment by jupeter** [comment]
I have same problem. 

Problem appear in v3.0.13. 
Works file in v3.0.12.

**Comment by xabbuh** [comment]
see #1354
