### ISSUE TITLE
Mapped Exception Return status code instead of given code

### ISSUE THREAD

**Issue by alexander-schranz** [FriendsOfSymfony/FOSRestBundle#2167]
Testing current master branch (pre 3.0) with sulu.

We have an exception which look like this:

https://github.com/sulu/sulu/blob/00d86acd9dc7c1f91c7561497fe0f7262456ad5c/src/Sulu/Bundle/CategoryBundle/Exception/KeywordIsMultipleReferencedException.php#L31

It has a `$code` attribute which is set to `2002`. And this exception is mapped to the statuscode [409](https://github.com/sulu/sulu/blob/2cccc18a10d948feec020463b48274fb7c76477f/src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php#L56).

Now instead of getting [2002](https://github.com/sulu/sulu/blob/00d86acd9dc7c1f91c7561497fe0f7262456ad5c/src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/KeywordControllerTest.php#L295) in the tests the json returns `409`.

**Comment by xabbuh** [comment]
Could you check if the changes from #2161 applied on `master` would solve the issue here?

**Comment by xabbuh** [comment]
@alexander-schranz #2161 should be fully available on `master` now. Can you check if the mapping works as expected?

**Comment by alexander-schranz** [comment]
@xabbuh seems like we did decorate the old exception listener and the `$code` was set by us to the `$exception->getCode()`.
Seems like I need to decorate the new `FlattenExceptionNormalizer` to set again  the exception code instead of the http status code.

The mapping works now correct.

**Comment by alexander-schranz** [comment]
@xabbuh The Exception Status Code mapping works but when running `--prefer-lowest` which will use symfony 4.4 the FlattenExceptionNormalizer is never called and so `message` and `code` is not set returned.

**Comment by xabbuh** [comment]
Any idea what is happening? Is the `ErrorRender` actually called? Will the `SerializerErrorRenderer` be used?

**Comment by alexander-schranz** [comment]
@xabbuh no it seems there is only the deprecated TwigBundle:ExceptionController called in Symfony 4.4

**Comment by alexander-schranz** [comment]
@xabbuh when disabling it with:

```php
        if ($container->hasExtension('twig') && class_exists(ExceptionController::class)) {
            // Disable the deprecated exception contorller
            $container->prependExtensionConfig('twig', [
                'exception_controller' => null,
            ]);
        }
```

it works as expected, as then the new error controller is called which uses the ErrorHandler component.

**Comment by xabbuh** [comment]
@alexander-schranz This looks expected to me. The ErrorRender component will only be used when the `ErrorController` from the HttpKernel component is executed (which replaces the `ExceptionController` provided by TwigBundle and which thus needs to be disabled explicitly on 4.4).

**Comment by alexander-schranz** [comment]
We disabled the exception_controller on our side now. In #2178 I added a exception to the compilerpass to avoid that other devs run into this problem.
