### ISSUE TITLE
Controller "FOS\RestBundle\Controller\ExceptionController" does neither exist as service nor as class. (500 Internal Server Error)

### ISSUE THREAD

**Issue by gmuehl** [FriendsOfSymfony/FOSRestBundle#2196]
I have some serious Problems with the newest dev-master in Symfony 5, this is my Configuration that worked before the upgrade:

```
# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  param_fetcher_listener:  true
  view:
    view_response_listener:  force
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      # https://github.com/FriendsOfSymfony/FOSRestBundle/issues/650#issuecomment-31449035
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
  exception:
    codes:
      'Doctrine\ORM\EntityNotFoundException': HTTP_NOT_FOUND
      'Symfony\Component\Form\Exception\AlreadySubmittedException': HTTP_CONFLICT
```

routing_loader seems deprecated, so i simply removed it. No Idea if i have to reconfigure it somehow, but the Main Problems are Exceptions:

If I force an Exception i am getting two serious errors:

- Controller "FOS\RestBundle\Controller\ExceptionController" does neither exist as service nor as class. (500 Internal Server Error)
- Exception is returned as HTML

This is reproducable in Symfony 5 with an empty Config. So, my Questions:

- do i have to change some settings because of routing_loader has gone?
- What is wrong with the ExceptionController, i checked the Source, it is really gone?
- And so: How can i get Exceptions as JSON again?

I Am pretty helpless at the Moment, looks like the Documentation is not updated.

**Comment by gmuehl** [comment]
Error is caused by a setting in framework.yaml

```
# Exceptions as JSON
error_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
```

**Comment by xabbuh** [comment]
The `ExceptionController` has been removed for 3.0. The Symfony ErrorRenderer component should now be used to render exceptions. Do you use the Symfony serializer or the JMS serializer?

**Comment by gmuehl** [comment]
Symfony Serializer

**Comment by xabbuh** [comment]
Then not setting the `error_controller` option should fix it for you.
