### ISSUE TITLE
doctrine/inflector

### ISSUE THREAD

**Issue by W0rma** [FriendsOfSymfony/FOSRestBundle#2197]
I noticed that this bundle requires `doctrine/inflector:^1.0`.

However, I'm not sure if it is still in use after https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2152

Should the classes located under https://github.com/FriendsOfSymfony/FOSRestBundle/tree/master/Inflector be deprecated in 2.8 and removed in 3.0?

**Comment by xabbuh** [comment]
That's a good catch. We should indeed be able to do that.
