### ISSUE TITLE
Empty fields in FormType serialization

### ISSUE THREAD

**Issue by rehoehle** [FriendsOfSymfony/FOSRestBundle#2211]
I have a problem in serializing a form type. I have testet a low now but i can't find the error. 

I have installed the following packages:

```
Symfony: 4.4
FOSRest: 2.7.4
JMSSerializerBundle: 3.5.0
TrikoderOAuthBundle: 3.1.1
```

When i try to serialize a form type:

```
$form = $this->createForm(ProfileEditType::class, $this->getUser());
return $this->handleView($this->view(['form' => $form]));
```

or 

`return $this->handleView($this->view($form));`

i get the following return:

```
{
    "children": {
        "firstname": {},
        "lastname": {},
        "street": {}
    }
}
```

I've read a lot and i tried a lot but i don't get some values for the fields. Does anyone know if this is a bug or if i make something wrong? I need a form type with values to parse it in VUE.

**Comment by rehoehle** [comment]
I have removed the JMS serializer and installed the symfony serializer pack in version 1.0. And i get the following output:

```
{
    "firstname": [],
    "lastname": [],
    "street": []
}
```

It's the same like the JMS example and it's empty.

**Comment by xabbuh** [comment]
I may be mistaken here as it's been a long time since I used FOSRestBundle with forms, but IIRC we only serialize errors when you embed a form in a view.

**Comment by rehoehle** [comment]
@xabbuh thanks for your answer. Errors are working. But for working with VUE for example it would be great to get the fields and the values that are mapped to the fields and the type of the field to render the form in VUE. 

Is there another good and easy solution? Or do i have to build the return array for the form by myself? The frontend and backend is completely separated because the frontend is hosted in S3.

**Comment by xabbuh** [comment]
I guess you can write your own serializer handler which works on `FormInterface` instances the way you need it.

**Comment by rehoehle** [comment]
Ok i have found the problem. It's not working with "$this->getUser()". So i have to make a database query first. Then i get the values.
