### ISSUE TITLE
override formErrorHandler or ExceptionHandler

### ISSUE THREAD

**Issue by imajim** [FriendsOfSymfony/FOSRestBundle#2217]
Hello,

Anyone could you describe the override of the formErrorHandler ou the ExceptionHandler ?
I've tried many solution but i can't override anything
Symfony version 3.4
FosRest: 2.7
JMS serializer: 2.4
I would change Json 's structure (flat version not tree version)

thx.

**Comment by xabbuh** [comment]
This sounds like it's mainly related to how to configure/customize JMS Serializer. Better ask for help on StackOverflow or on the Symfony Slack I guess.
