### ISSUE TITLE
Fatal error missing NormalizerInterface in project with JMS Serializer instead of Symfony Serializer

### ISSUE THREAD

**Issue by freezy-sk** [FriendsOfSymfony/FOSRestBundle#2218]
Running `php bin/console cache:clear` in project using JMS Serializer instead of  Symfony Serializer throws 
```
Fatal error: Interface 'Symfony\Component\Serializer\Normalizer\NormalizerInterface' not found in /var/www/html/vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/FormErrorNormalizer.php on line 22
```
```
friendsofsymfony/rest-bundle        2.7.4
jms/serializer-bundle               3.5.0
symfony/framework-bundle            v4.4.8
```

**Comment by xabbuh** [comment]
Do you still experience this error? If so, can you please create a small example application that allows to reproduce it?

**Comment by freezy-sk** [comment]
@xabbuh I tried it right now with fresh install of SF 4.4 with Rest bundle 2.7, 2.8, 3.0, JMS bundle 3.5 and SF 5.0 with Rest bundle 2.7, 2.8, 3.0, JMS bundle 3.5 and it works correctly everywhere. I don't remember in which one of my projects I was experiencing this, so I can't find related config files.
Closing this issue as it's not possible to reproduce it.
