### ISSUE TITLE
2.8 breaking serializer.serialize_null config

### ISSUE THREAD

**Issue by Thewolfs** [FriendsOfSymfony/FOSRestBundle#2219]
Hi,

Moving to 2.x-dev/2.8-beta breaks the config for serializer.serialize_null with SF4. Whatever value you assign to it, it's getting ignored

Downgrading to 2.7.4 works fine though

From what I could see, the options passed in FOSRestExtension line 485 are not getting propagated properly:
`$options['serializeNullStrategy'] = $config['serializer']['serialize_null'];
$viewHandler->addArgument($options);`

**Comment by xabbuh** [comment]
Could you create a small example application that allows to reproduce?

**Comment by Thewolfs** [comment]
Here is a repo with a small example : 
https://github.com/Thewolfs/fosRestSerializerNullExample

Go to the URL /api/data to notice that `foo: null` does not appear
If you downgrade to Fos Rest : ^2.7 it will appear just fine

Hope this helps

**Comment by xabbuh** [comment]
Thank you. I am able to reproduce the issue. Looking into how to fix this.

**Comment by xabbuh** [comment]
Can you confirm that this works with the changes I propose in #2220?

**Comment by xabbuh** [comment]
2.8.0-beta3 containing this fix has been tagged
