### ISSUE TITLE
BC break 2.8: configuration setting ["serializer"]["groups"] seems to be ignored

### ISSUE THREAD

**Issue by W0rma** [FriendsOfSymfony/FOSRestBundle#2222]
I have upgraded my project from 2.7 to 2.8.0-beta2

The default serializer group "Default" is defined in the bundle configuration:

    fos_rest:
        serializer:
            groups: ['Default']
            serialize_null: true

I'm using JMS serializer.

In 2.7 everthing works like expected. However, in 2.8 the default group seems to be completely ignored.

In https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.8.0-beta2/Serializer/JMSSerializerAdapter.php#L100 `$context->getGroups()` returns `null` in 2.8 whereas it returns `["Default"]` in 2.7.

Adding the annotation `View(serializerGroups={"Default"})` to the affected controller action fixes the issue.

**Comment by xabbuh** [comment]
Can you confirm that #2220 has fixed this in the meantime?

**Comment by W0rma** [comment]
Yes, works like a charm - thank you!

**Comment by xabbuh** [comment]
2.8.0-beta3 containing this fix is tagged now
