### ISSUE TITLE
API Versioning without JMS Serializer

### ISSUE THREAD

**Issue by gmuehl** [FriendsOfSymfony/FOSRestBundle#2231]
I guess this is not really an FOSRestBundle Issue, maybe an "missing Documentation" Issue! ;)

It's pretty clear how to use Versioning with JMS Serializer, but what happens when using the Symfony Serializer Component?

I don't think that there is something like @Since and @Until in Symfony Serializer?

So, how can i use FOSRestBundle API Versioning without JMS Serializer?

**Comment by GuilhemN** [comment]
You can't leverage FOSRestBundle Versioning using the Symfony's Serializer annotations.
However, you can leverage it using custom normalizers, using the `version` passed in the context (see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/Serializer/SymfonySerializerAdapter.php).
