### ISSUE TITLE
v2.8.0 is broken on Symfony 3.4

### ISSUE THREAD

**Issue by marmaladesoftware** [FriendsOfSymfony/FOSRestBundle#2234]
`Serializer/Normalizer/FlattenExceptionNormalizer.php` has a use statement for an interface that is not present in Symfony 3.4.41: `Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface`. This causes an error:

`[2020-06-04 15:12:46] app.CRITICAL: Internal Server Error: Attempted to load interface "CacheableSupportsMethodInterface" from namespace "Symfony\Component\Serializer\Normalizer". Did you forget a "use" statement for another namespace? {"http_error":"Internal Server Error","file":"/var/www/...redacted.../vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/FlattenExceptionNormalizer.php","line":25,"stack_trace":"#0 {main}"} []`

**Comment by xabbuh** [comment]
Thank you for reporting @marmaladesoftware. I have created #2236 to fix this.
