### ISSUE TITLE
Add custome header for all endpoint

### ISSUE THREAD

**Issue by krabouilleur** [FriendsOfSymfony/FOSRestBundle#2242]
Hi,

I'm using Symfony 5.

for example, in .env file there is an env variable :
`FOO=bar`

All endpoint called must have the header response :  
`Custom-header: bar`

Is there a way, in yaml configs to add the same header for all routes ?

**Comment by Steveb-p** [comment]
Use built-in Symfony events: https://symfony.com/doc/current/event_dispatcher/before_after_filters.html#after-filters-with-the-kernel-response-event

Note that it has nothing to do with FOSRestBundle. There is no reason for this library to add something like this as it is practically out of scope.
