### ISSUE TITLE
Cannot use interface when using ParamConverter

### ISSUE THREAD

**Issue by lopesrichard** [FriendsOfSymfony/FOSRestBundle#2246]
When working with dependency injection with symfony, we can use interfaces in controller, and the framework automatically uses the corresponding implementation.

For example: I have the following structure in my project
  - Model
     - Impl
         - UserModel.php
     - UserModel.php
  - Repository
     - Impl
         -  UserRepository.php (Concrete Class)
     - UserRepository.php (Interface)

In my controller I use directly the interface `\Repository\UserRepository` on method signature, and symfony framework uses the correct `\Repository\Impl\UserRepository` implementation.

But my problem is about the ParamConverter.

I'm using the annotation `@ParamConverter("model", converter="fos_rest.request_body")`, and when I use the concrete class of the model `\Model\Impl\UserModel`, everything works fine, but when I use the interface (yes, the model has a interface because it has some methods) I got the error `Could not denormalize object of type \Model\UserModel, no supporting normalizer found`.

Is there any configuration I should made?

PS: I'm using symfony 5 with friendsofsymfony/rest-bundle 3.0.0

**Comment by xabbuh** [comment]
If I don't miss anything, this is purely related to the serializer configuration. Which means you will need to make sure that the serializer that you use understands that it needs to deserialize the data into an instance of `Model\Impl\UserModel` when the requested type is `Model\UserModel`.
