### ISSUE TITLE
Interface 'Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface' not found

### ISSUE THREAD

**Issue by kkrasnik** [FriendsOfSymfony/FOSRestBundle#2248]
Interface 'Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface' not found in /application/vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/FlattenExceptionNormalizer.php on line 25

There is no Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface defined in Symfony Serializer component v3.4

**Comment by xabbuh** [comment]
I think this is the same as #2234 and thus fixed by #2236.

**Comment by kkrasnik** [comment]
v2.8.1 fixes this bug

**Comment by paulbriton** [comment]
@xabbuh Do you know when v2.8.1 will be released ?

**Comment by xabbuh** [comment]
@paulbriton done now
