### ISSUE TITLE
Access Denied Listener

### ISSUE THREAD

**Issue by GinoPane** [FriendsOfSymfony/FOSRestBundle#2249]
Hi!

The support for access_denied_listener was dropped, but docs still list it. 

Could you please advise what to use instead of this config:

![image](https://user-images.githubusercontent.com/3897579/85786763-3d6d2680-b733-11ea-8e58-ae9e329f75aa.png)

**Comment by xabbuh** [comment]
Using this config shouldn't be necessary anymore. You can simply remove this option. I have opened #2252 to remove the docs for it.

**Comment by GinoPane** [comment]
Cool, thanks
