### ISSUE TITLE
Class FOS\RestBundle\Tests\Fixtures\User does not exist

### ISSUE THREAD

**Issue by yuseferi** [FriendsOfSymfony/FOSRestBundle#2275]
Hi there, 
I have this problem, hope somebody knows how to resolve it.

definitation:

- **Symfony version:** 4.2
- **PHP:** 7.4
- **part of my composer reqs**
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "doctrine/annotations": "^1.11",
        "friendsofsymfony/rest-bundle": "^2.5",
        "jms/serializer-bundle": "^3.7",
        "nelmio/alice": "^3.5",
        "nelmio/api-doc-bundle": "^3.4",
        "php-http/guzzle6-adapter": "^1.1",
        "phpdocumentor/reflection-docblock": "^4.3.0",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/console": "^4.1",
        "symfony/dotenv": "^4.1",
        "symfony/expression-language": "^4.1",
        "symfony/flex": "^1.5",
        "symfony/framework-bundle": "^4.1",
        "symfony/orm-pack": "^1.0",
        "symfony/serializer-pack": "^1.0",
        "symfony/twig-bundle": "^4.1",
        "symfony/validator": "4.1.*",
        "symfony/yaml": "^4.1",
 - **Part of my composer req-dev**
        "behat/behat": "^3.5",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-extension": "^2.3",
        "behat/symfony2-extension": "^2.1",
        "endouble/symfony3-custom-coding-standard": "^2.17",
        "phpspec/prophecy": "^1.7",
        "phpunit/phpunit": "^7.4",
        "symfony/maker-bundle": "^1.11",
        "symfony/profiler-pack": "^1.0",
        "wiremock-php/wiremock-php": "^2.22",
 - **fos_rest.yaml**
fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  view:
    formats:
      json: true
    view_response_listener:  true
  format_listener:
    rules:
      prefer_extension: false
      fallback_format: json
  serializer:
    serialize_null: true
  service:
    serializer: fos_rest.serializer.jms
  exception:
    enabled: true
    exception_controller: 'App\Controller\ExceptionController::showAction'
    codes:
      'App\Exception\ValidationException': 400

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors

on `APP_ENV=dev` everything goes well, but when I switch to `APP_ENV=prod` I will face 
In EndpointRouterCompilerPass.php line 130:
                                                           
  **Class FOS\RestBundle\Tests\Fixtures\User does not exist** 

**PSR Autoloader**
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\App\\": "tests/unit",
            "Tests\\Behat\\": "tests/behat",
            "App\\Behat\\": "behat/bootstrap/"
        }
    },

I hope somebody knows a solution for this.

Thanks,

**Comment by yuseferi** [comment]
just for the record for guys that could have a similar problem: 

I just updated the version of `"friendsofsymfony/rest-bundle": "^2.8",` and the problem was gone :).

**Comment by fsmeier** [comment]
For the record: It seems that there are folders missing from 2.7.4 to 2.8.x :/
