### ISSUE TITLE
"syntax error, unexpected token match" on PHP 8.0 caused by willdurand/negotiation v2

### ISSUE THREAD

**Issue by mbence** [FriendsOfSymfony/FOSRestBundle#2281]
For php 8.0 willdurand/negotiation v3 is required, but here it is locked at ^2.0

https://github.com/willdurand/Negotiation/releases/tag/3.0.0

**Comment by GuilhemN** [comment]
Please see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2278
