### ISSUE TITLE
Custom array keys are being replaced with indexes starting at 0

### ISSUE THREAD

**Issue by smadaman** [FriendsOfSymfony/FOSRestBundle#2300]
Hi. Since updating to the latest version I now have an issue where custom keys that I have set as strings are just being replaced with indexes.

This is my data in Postman prior to the update
![image](https://user-images.githubusercontent.com/12181026/112089764-62b99300-8be6-11eb-8022-349b50d431d7.png)

And this is my data in Postman after the update
![image](https://user-images.githubusercontent.com/12181026/112089825-7f55cb00-8be6-11eb-9892-001a4edc2896.png)

I have not changed any code at all. I am organising the returning list as:
 - data (A namespaced class)
 - milestoneStatistics (an array with custom keys)
 - each item in milestoneStatistics (A namespaced class)

Is this something that has changed in FOSRestBundle or I guess it could be in another library that this one relies on?

Thanks in advance!

**Comment by xabbuh** [comment]
Without knowing more about your application my guess would be that this is related to the serializer library that you use when generating the response.

**Comment by smadaman** [comment]
No worries, thanks. I'm using the JMS serializer. I might look into that.

Update: JMS Serializer was the problem. They updated it yesterday with a fix. Thanks again
