### ISSUE TITLE
Route annotation triggers deprecation in symfony 5.3

### ISSUE THREAD

**Issue by W0rma** [FriendsOfSymfony/FOSRestBundle#2311]
The `@Route` annotation (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/Controller/Annotations/Route.php#L23) triggers the following deprecation in symfony 5.3:

`Since symfony/routing 5.3: Passing an array as first argument to "Symfony\Component\Routing\Annotation\Route::__construct" is deprecated. Use named arguments instead.`

**Comment by croftman** [comment]
Waiting for that :)
