### ISSUE TITLE
With SF 4.4  Argument 1 passed to FOS\OAuthServerBundle\Entity\ClientManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager

### ISSUE THREAD

**Issue by pankujoshi** [FriendsOfSymfony/FOSRestBundle#2345]
Argument 1 passed to FOS\OAuthServerBundle\Entity\ClientManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of ContainerFuBxdJb\EntityManager_9a5be93 given, called in C:\xampp\htdocs\rest2\var\cache\dev\ContainerFuBxdJb\srcApp_KernelDevDebugContainer.php on line 4451

![image](https://user-images.githubusercontent.com/38710589/139069922-c6219dc7-4c2b-4145-b604-1ad4da8b8fa8.png)

I have install the oauth-server-bundle and created the REST Api with Oauth with the help of this Link: https://www.adcisolutions.com/knowledge/getting-started-rest-api-symfony-4
Now am facing this type error.

**Comment by xabbuh** [comment]
I think https://github.com/FriendsOfSymfony/FOSOAuthServerBundle would be the repo to report any issues with FOSAuthServerBundle.
