### ISSUE TITLE
symfony/serializer 6.1 use NormalizerInterface instead.

### ISSUE THREAD

**Issue by Miller0** [FriendsOfSymfony/FOSRestBundle#2379]
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/b888195589d245002880d07073ef23ab60e3795d/Serializer/Normalizer/FlattenExceptionNormalizer.php#L25

 The "FOS\RestBundle\Serializer\Normalizer\FlattenExceptionNormalizer" class implements "Symfony\Component\Serializer\Normalizer\ContextAwareNormalizerInterface" that is deprecated since symfony/serializer 6.1, use NormalizerInterface instead.

**Comment by goetas** [comment]
Done in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2377
