### ISSUE TITLE
Deprecation warning after updating Symfony from version 6.2 to 6.3

### ISSUE THREAD

**Issue by Heaven31415** [FriendsOfSymfony/FOSRestBundle#2393]
Hi.

Whenever I run any console command in my Symfony project, I receive the following deprecation warning:

`[info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "FOS\RestBundle\FOSRestBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

This started after I updated my Symfony version from 6.2 to 6.3. On 6.2 I didn't see anything similar to that.  I'm using FOSRestBundle version 3.5.0.

This problem was briefly mentioned here: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2389, however I believe it wasn't properly reported, that's why I decided to create another ticket.

**Comment by raziel057** [comment]
@Heaven31415 It's already covered by the PR that is not yet merged: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2392

See the folowing commit: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2392/commits/a4ad08be657d0702aee189b61f851a1e77dfd8e1#diff-dbf75c5359a6a60cd85402ff7bab7f9d7c5ec9a0794c461ccd90b285b9f033e1

**Comment by deluxetom** [comment]
@goetas this issue can be closed
