### ISSUE TITLE
Symfony 6.4 adds `@final` annotation to Route annotation/attribute class

### ISSUE THREAD

**Issue by mbabker** [FriendsOfSymfony/FOSRestBundle#2397]
Symfony 6.4 adds the `@final` annotation to the `Symfony\Component\Routing\Attribute\Route` class (the annotation classes are all moved to a new Attribute namespace with a proxy layer), so anyone using the annotation/attribute classes from this bundle will get unfixable deprecation notices because of that.

**Comment by kevinpapst** [comment]
I am currently investigating all kind of deprecations and luckily this one is easy to solve and also reduces the bundle coupling (which seems to be a good idea in the long run anyway).

So simply search & replace those:

- `#[Rest\Get(` with `#[Route(methods: ['GET'], `
- `#[Rest\Post(` with `#[Route(methods: ['POST'], `
- `#[Rest\Patch(` with `#[Route(methods: ['PATCH'], `
- `#[Rest\Delete(` with `#[Route(methods: ['DELETE'], `

**Comment by mbabker** [comment]
Annotation removed upstream, all good here.

**Comment by kevinpapst** [comment]
@mbabker thanks for sharing feedback with SF Team.
It took me quite a while to replace all annotations in various bundles and to me it feels better to reduce the coupling and stick with the basic SF attributes.

Is there any benefit in using the ones from FOSRest? E.g. NelmioApiDoc supports both versions...

**Comment by mbabker** [comment]
It's all personal choice.  The ones here are just shortcuts that read a little nicer in code (`#[Post('/foo')]` versus `#Route('/foo', methods: ['POST'])]`), some folks make extended attribute classes to shorthand some duplicated config.  It doesn't really matter if you use the core `Route` class or anything subclassing it as most tooling should work with them all.

**Comment by kevinpapst** [comment]
That's what I thought. 
I do see the benefits for reducing redundant configuration and this final was probably too much ... but these occurrences are also good to question the own behavior. 
Thanks for the clarification 👍
