### ISSUE TITLE
Symfony 7 dont support FOSRestBundle

### ISSUE THREAD

**Issue by hhalaoui** [FriendsOfSymfony/FOSRestBundle#2402]
Hi, 
I want to install the bundle, but it is not compatible with Symfony 7.
the output of command : composer require friendsofsymfony/rest-bundle:^3.6 
- friendsofsymfony/rest-bundle 3.6.0 requires symfony/config ^5.4|^6.0 -> found symfony/config[v5.4.0, ..., v5.4.31, v6.0.0, ..., v6.4.0]

**Comment by deluxetom** [comment]
@hhalaoui its almost done https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2400, subscribe to the PR to see when it will be ready

**Comment by W0rma** [comment]
[Version 3.7.0 of this bundle](https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/3.7.0) supports symfony 7.

I guess this issue can be closed.
