### ISSUE TITLE
FOSRestBundle deprecation notice with PHP 8.4 causes call-stack dump on each command

### ISSUE THREAD

**Issue by pgnd** [FriendsOfSymfony/FOSRestBundle#2415]
i've installed Sulu CMS, which requires rest-bundle,

```
composer show | grep -Ei "sulu  |rest-b|framework-b"
	friendsofsymfony/rest-bundle             3.7.1     This Bundle provides various tools to rapidly develop RESTful API...
	sulu/sulu                                2.6.6     Core framework that implements the functionality of the Sulu cont...
	symfony/framework-bundle                 7.1.6     Provides a tight integration between Symfony components and the S...
```

with
```
php -v
	PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS gcc x86_64)
	Copyright (c) The PHP Group
	Built by Remi's RPM repository <https://rpms.remirepo.net/> #StandWithUkraine
	Zend Engine v4.4.1, Copyright (c) Zend Technologies
	    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
	    with Xdebug v3.4.0, Copyright (c) 2002-2024, by Derick Rethans

grep error_reporting /usr/local/etc/php8/conf.d/error_logging.ini
	error_reporting = E_ALL ^ E_DEPRECATED

php -i | grep -i "error_reporting \="
	error_reporting => 22527 => 22527
```

commands dump a call stack on any deprecation.

e.g., if
```
Deprecated: FOS\RestBundle\EventListener\BodyListener::__construct(): Implicitly marking parameter $arrayNormalizer as nullable is deprecated, the explicit nullable type must be used instead in /srv/sulu.app/vendor/friendsofsymfony/rest-bundle/EventListener/BodyListener.php on line 40
```

the output of `bin/console about` is a very verbose:

https://pastebin.com/raw/LvYUS0NW

attempt to install dev-master
```
composer require friendsofsymfony/rest-bundle:dev-master
	./composer.json has been updated
	Running composer update friendsofsymfony/rest-bundle
	Loading composer repositories with package information
	Updating dependencies
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - Root composer.json requires friendsofsymfony/rest-bundle dev-master, found friendsofsymfony/rest-bundle[dev-docs, 0.6.0, ..., 0.13.1, 1.0.0-RC1, ..., 1.8.x-dev, 2.0.0-BETA1, ..., 2.x-dev, 3.0.0-beta1, ..., 3.x-dev] but it does not match the constraint.
	  Problem 2
	    - sulu/sulu is locked to version 2.6.6 and an update of this package was not requested.
	    - sulu/sulu 2.6.6 requires friendsofsymfony/rest-bundle ^3.1 -> found friendsofsymfony/rest-bundle[3.1.0, ..., 3.x-dev] but it conflicts with your root composer.json require (dev-master).

	Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

	Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

checking with Sulu dev,

"For your error it seems related to fos rest bundle not have a 8.4 tag yet. At current state you can ignore the deprecation notice by disable notices in your php.ini. Use a dev branch version, or may make a friendly ping to the maintainer if they may want to tag a new release with the already merged."

**Comment by goetas** [comment]
can you try https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/3.8.0 ?

**Comment by pgnd** [comment]
@goetas 

with
```
composer show | grep rest-bundle
	friendsofsymfony/rest-bundle             3.x-dev d247368 This Bundle provides various tools to rapidly develop RESTf...
```

same 'noisy' result.

and, same with,
```
composer show | grep rest-bundle
	friendsofsymfony/rest-bundle             3.8.0     This Bundle provides various tools to rapidly develop RESTful API...
```

**Comment by pgnd** [comment]
this does _not_ seem to be specific to FOSRestBundle.
presence of _any_ deprecation notice seems to trigger the call stack dump.
asking in #symfony slack ...

**Comment by pgnd** [comment]
fyi, re: fixing the related FOSRestBundle deprecation notice for 8.4 compat, e.g.,

 Fix PHP 8.4 deprecation notices #1903
  https://github.com/Seldaek/monolog/pull/1903

**Comment by xabbuh** [comment]
Does it mean we can close here or is there still anything left to do?

**Comment by pgnd** [comment]
> Does it mean we can close here

up to you, of course.

*i* wouldn't until there's no deprecation notice from FOSRestBundle to trigger this issue ...

tho it seems highly unlikely FOSRestBundle is the cause, i'm just not yet certain what the cause _is_.

EDIT:

it appears that `xedbug` is the culprit here.

it's installed
```
php -v
	PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS gcc x86_64)
	Copyright (c) The PHP Group
	Built by Remi's RPM repository <https://rpms.remirepo.net/> #StandWithUkraine
	Zend Engine v4.4.1, Copyright (c) Zend Technologies
		with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
		with Xdebug v3.4.0, Copyright (c) 2002-2024, by Derick Rethans
```

here, it's NOT explcitily in use, enabled -- or otherwise configured.

but, adding an *explicit* disable via `xdebug.mode` ((https://xdebug.org/docs/all_settings#mode))
```
xdebug.mode = off
```

does the trick; NO call stack dump ... just operation output.

this also works
```
xdebug.mode = trace
xdebug.start_with_request = trigger
```

any other value of `xdebug.mode` other than `=off`, or if it's undef'd, causes the dump.

note, in all cases, the FOSRestBundle deprecation notice DOES persist, regardless of the `error_reporting` setting.

**Comment by xabbuh** [comment]
> note, in all cases, the FOSRestBundle deprecation notice DOES persist

Which deprecation do you mean? If the one from above, can you please check that the `BodyListener` class in your `vendor` directory looks like https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/EventListener/BodyListener.php#L43? What output do you get with `composer show`?

**Comment by pgnd** [comment]
>> note, in all cases, the FOSRestBundle deprecation notice DOES persist

> Which deprecation do you mean? If the one from above

"all cases" was premature. true for the xdebug bits, but i wasn't testing with latest RestBundle code.

i switched back to 3.x-dev branch, and ... no more deprecation notice from FOSRestBundle.

dev branch WORKSFORME until a next tag.

good enuf to close!

**Comment by xabbuh** [comment]
This sounds weird as there are no commits in the `3.x` branch that are not part of the `3.8.0` tag.

**Comment by pgnd** [comment]
just reporting what i _see_, haven't done any further digging.
tbh, too many bits involved in this to chase it ... given it currently works.

if it crops up again, i'll certainly drop a line here.
