### ISSUE TITLE
Error when combining @QueryParam and @Secure annotation

### ISSUE THREAD

**Issue by grEvenX** [FriendsOfSymfony/FOSRestBundle#242]
Not sure if this issue belongs in FOSRestBundle or JMS/CG, the problem is that the @QueryParam implementations cannot be used right now if you also use @Secure annotations from JMS/SecurityExtraBundle.
When I annotate my method with @Secure, the JMS bundle creates a proxy object that contains no annotations.
in QueryFetcher::initParams it tries to read the reflection of: 

```
$this->params = $this->queryParamReader->read(new \ReflectionClass($this->controller[0]), $this->controller[1]);
```

which is the proxy-class and not the controller class itself.

This causes the error:
`No @QueryParam configuration for parameter 'limit'.`

The generated proxy class from the JMS\CG bundle looks like this:

``` PHP
<?php

namespace EnhancedProxy_e8fcdbed4ecc1a6ff7f797867d2ba9a63944f6b6\__CG__\Oyatel\RestBundle\Controller;

/**
 * CG library enhanced proxy class.
 *
 * This code was generated automatically by the CG library, manual changes to it
 * will be lost upon next generation.
 */
class ConferencesController extends \Oyatel\RestBundle\Controller\ConferencesController
{
    private $__CGInterception__loader;

    public function getConferencesAction(\FOS\RestBundle\Request\QueryFetcher $queryFetcher, $limit = 25, $offset = 0)
    {
        $ref = new \ReflectionMethod('Oyatel\\RestBundle\\Controller\\ConferencesController', 'getConferencesAction');
        $interceptors = $this->__CGInterception__loader->loadInterceptors($ref, $this, array($queryFetcher, $limit, $offset));
        $invocation = new \CG\Proxy\MethodInvocation($ref, $this, array($queryFetcher, $limit, $offset), $interceptors);

        return $invocation->proceed();
    }

    public function __CGInterception__setLoader(\CG\Proxy\InterceptorLoaderInterface $loader)
    {
        $this->__CGInterception__loader = $loader;
    }
}
```

Since I'm not a Symfony dev myself I'm unsure about the correct solution.
Is this is the right approach to read the annotations? or is the code-generator in the CG bundle doing it wrong and should keep the annotations in the generated class or something?

**Comment by cedricduffournet** [comment]
I have the same issue in 2.0
