### ISSUE TITLE
Resource Pluralization as an option.

### ISSUE THREAD

**Issue by stephpy** [FriendsOfSymfony/FOSRestBundle#294]
Hi, 

Actually, routing use pluralization automatically for resources. What do you think about an option to be able to deactivate that ? For sure, by default it'll be activated ...

It could be defined on config:

```
fos_rest:
   resource:
       pluralize_path: true
```

And even on RouteResource annotation ?

````
/**
*@RouteResource("User", false) 
*/
````

**Comment by Ener-Getick** [comment]
This issue/PR seems to be abandoned ... I will continue this work in a new PR.

**Comment by lsmith77** [comment]
closed via https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1096
