### ISSUE TITLE
missing xsd file

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#343]
@everzet: did we ever have an XSD file?

in our fixtures we seem to assume so:

```
<routes xmlns="http://friendsofsymfony.github.com/schema/rest"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://friendsofsymfony.github.com/schema/rest http://friendsofsymfony.github.com/schema/rest/routing-1.0.xsd">
```

https://travis-ci.org/FriendsOfSymfony/FOSRestBundle/jobs/3687051

@tobion: i assume we are not seeing those errors because of the loader refactoring in the routing component?

**Comment by Tobion** [comment]
Closing as irrelevant per #1954
