### ISSUE TITLE
Composite ID for resources

### ISSUE THREAD

**Issue by maxpowel** [FriendsOfSymfony/FOSRestBundle#375]
Hi! I'm trying to use an URI like:

/entities/{type}/{id}

Where type is for example "Image" and id is an integer. For example for the Image with id 21 the URI is: /entities/Image/21

I am not able to use an URI like this. Is there a way to use a composite id?

Thank you

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954
