### ISSUE TITLE
Set content-type to application/json + charset=UTF-8

### ISSUE THREAD

**Issue by priestor** [FriendsOfSymfony/FOSRestBundle#438]
Hey guys!

My problem is that I want to send my json response from my API with the Content-Type "application/json; charset=UTF-8".

But I don't know how to do that in this bundle, is there a config parameter? Do I have to implement it my self and change the response with ->headers->set(..) or something?

my default format is json but i need json+utf-8 :))

Can someone help?

**Comment by gondo** [comment]
i was using this setup but after updating from `02fd6423543d673946246c7f74a738099951aaff` to `b38db72be9eed4f5c2135ba6ea19b66eaa1def22`, encoding is broken again
