### ISSUE TITLE
look into supporting JSON API

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#452]
http://jsonapi.org

**Comment by steveklabnik** [comment]
Hey there! I just wanted to let you know that JSON API has hit RC3, and we'd like client libraries to start implementing it like it was 1.0, as a final check that we're good for 1.0. So hopefully that can inform the discussion here a bit.

https://github.com/json-api/json-api/issues/484

**Comment by amenophis** [comment]
@lsmith77: I can start working on this, it is an interresting topic !
How can we start ?

**Comment by jrobeson** [comment]
@amenophis : you will be a hero if you accomplish this!

**Comment by szachara** [comment]
I have read whole json api spec now and it will not be as simple as it looks, there are many complicated scenarios and this spec is really extensive, but I hope we will have some implementation in near future, because I really like this new fresh spec.

**Comment by esistgut** [comment]
Is anyone working on this? JSON API hit the 1.0 stable and Ember Data just pushed the first stable release using it.

**Comment by lsmith77** [comment]
not that I know of .. would be awesome!

**Comment by steffenbrem** [comment]
I am currently working on this, trying to get it out for public. I inspired most of it from the Hateoas bundle from willdurand. 

For example, this is how you would configure the JSON-API serializer for your data models:

```php
/**
 * @Hateoas\Resource(type="posts")
 *
 * @author Steffen Brem <steffenbrem@gmail.com>
 */
class Post
{
    /**
     * @Hateoas\Id
     * @var int
     */
    protected $id;

    /**
     * @var string
     */
    protected $title;

    /**
     * @var string
     */
    protected $description;

    /**
     * @Hateoas\HasMany(includeByDefault=true)
     */
    protected $comments;

    // ...
}
```

**Comment by steffenbrem** [comment]
I am not sure though if it needs to be another `HateoasBundle` or if I should just use `JsonApiBundle` and make it only for `JSON-API`.

**Comment by szachara** [comment]
Hi, 

from my point of view this is the way which I would also went. I really like how the `FOSRestBundle` works. I think that the best name for your bundle would be `JsonApiBundle` and only one think which will do, will be to work with `JSON API`, by `FOSRestBundle` way. 

This problem could be accomplished by so many ways. I prefer to use and extend the `FOSRestBundle` and to use and inspire by the HateoasBundle regarding the work with links. 

When you will have working bundle which will be compatible with `JSON API v1`, so you can work on better abstraction of the code and other enhancements. 

You can use many code from `Hateoas` library, because there is really good code which handles links and mappings between entities and serialization ( through annotations ). 

This is how I'm looking on this enhancement.

And about this unassuming line:
> I hope I can make my work public soon :+1:

I'm really impatient how it will be implemented. ;-)

**Comment by steffenbrem** [comment]
@szachara I will put something public today, for now I am only working with an AnnotationDriver. Currently I've got some basic `JSON-API` serialization going with FOSRestBundle. You can mix anything with it, as you can see is the `title` attribute of a post annotated with `@JMS\SerializedName("tiiitel")`, so you can still use JMS features in it. 

Here is a simple output that the serializer I wrote currently outputs from a simple `Post > Comment` relationship.

```json
{
    "data": [
        {
            "type": "posts",
            "id": 1,
            "attributes": {
                "tiiitel": "My post",
                "description": "This is the first post"
            },
            "relationships": {
                "comments": {
                    "data": [
                        {
                            "type": "comments",
                            "id": 1
                        }
                    ]
                }
            }
        },
        {
            "type": "posts",
            "id": 2,
            "attributes": {
                "tiiitel": "My second post",
                "description": "This is the second post"
            },
            "relationships": {
                "comments": {
                    "data": [
                        {
                            "type": "comments",
                            "id": 1
                        }
                    ]
                }
            }
        },
        {
            "type": "posts",
            "id": 3,
            "attributes": {
                "tiiitel": "My third post",
                "description": "This is the third post"
            },
            "relationships": {
                "comments": {
                    "data": []
                }
            }
        }
    ],
    "included": [
        {
            "type": "comments",
            "id": 1,
            "attributes": {
                "title": "This is a comment title",
                "body": "My body"
            }
        }
    ]
}
```

**Comment by szachara** [comment]
Great start, I have not found any error in serialized output, already now it's valid `JSON API` output. Of course a `links` objects are missing, but when a `relationships` object contains `data` object ( `resource linkage`) , so `links` are optional. 

> You can mix anything with it, as you can see is the title attribute of a post annotated with @JMS\SerializedName("tiiitel"), so you can still use JMS features in it.

This is very important.

**Comment by steffenbrem** [comment]
If anyone wants to discuss about this topic, I created a public repo, which I will soon fill with my work that I have done. See: https://github.com/steffenbrem/JsonApiBundle

**Comment by szachara** [comment]
:+1:

**Comment by lsmith77** [comment]
ok .. closing the ticket as there is now a Bundle for this
