### ISSUE TITLE
Serialization Groups

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSRestBundle#521]
I opened an issue in JMSserializer, but @wiistriker said me that I can to do this directly with FOSRestBundle 

> https://github.com/schmittjoh/JMSSerializerBundle/issues/314

So my question is, how can I use the method serializerGroups. 

> (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/d14f8b35fe4cb113d99bf3b6410c06e8d14fc80c/Controller/Annotations/View.php#L88 )

Because for to use .. 

```
    $view = $this->view($channel, 200);
    return $this->handleView($view);
```

I need the class View, FOSRestBundle / View / View.php...  doesnt it ?:

> https://github.com/FriendsOfSymfony/FOSRestBundle/blob/d14f8b35fe4cb113d99bf3b6410c06e8d14fc80c/View/View.php

Thanks in advance

**Comment by naroga** [comment]
@stof how would one add a SerializationContext without JMS/Serializer? I'm using the default Symfony serializer (since the JMS is released under the Apache license and I can't use in my project), and I can't seem to find a way to exclude a property from being serialized.

**Comment by chadyred** [comment]
No it's simple like this : 

include this class in the class : 

<pre>

	use FOS\RestBundle\Context\Context;
</pre>

and in you action

<pre>

			$context = new Context();

			$context->addGroup('article');

		    $view = $this->view($data, 200);
		     $view->setContext($context);
</pre>

**Comment by paulalbertdev** [comment]
Where is the documentation about this ? I had a hard time to find this solution...
