### ISSUE TITLE
Support trailing slashes on automatic routes for collections

### ISSUE THREAD

**Issue by andyfowler** [FriendsOfSymfony/FOSRestBundle#522]
While there's some academic discussion on the merits of this, it feels like `GET /people` and `GET /people/` (trailing slash) should be synonyms. If nothing else, it makes it more intuitive for consumers that are exploring an API via a browser.

I'm relatively new to this codebase, but it appears this would be an update to `RestActionReader->generateUrlParts()` — glad to submit a patch if others think this  is desired behavior.

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954

With Symfony Core you can add trailing slashes if you wish to.
