### ISSUE TITLE
Be able create multiple viewHandlers

### ISSUE THREAD

**Issue by tarjei** [FriendsOfSymfony/FOSRestBundle#527]
Different bundles needs different variations of viewhandler configurations. It would be nice to have a simple mechanism for creating them. 

My usecase: FOS Comment bundle needs the templating handlers configured with json to be templated, I do not want that in another bundle that I'm implementing now.

**Comment by lsmith77** [comment]
this will hopefully be addressed with https://github.com/FriendsOfSymfony/FOSRestBundle/pull/955
