### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by unusorin** [FriendsOfSymfony/FOSRestBundle#542]
It is possible to implement pagination for large responses ?

Google Search: nada

**Comment by bichotll** [comment]
Just cause I was also looking for a solution:
https://github.com/schmittjoh/JMSSerializerBundle/issues/380#issuecomment-68520209

**Comment by lucasgranberg** [comment]
Just as reference. If you use knp paginator and jmsserializer this solution works: http://stackoverflow.com/questions/27214339/jms-serializer-ignores-mappings-for-knp-paginator

**Comment by mamartins** [comment]
any news on this?

**Comment by lsmith77** [comment]
nope ..

**Comment by hipio** [comment]
A more concrete proposal has been suggested in #1476.
