### ISSUE TITLE
Boolean values on request JSON

### ISSUE THREAD

**Issue by nunojsferreira** [FriendsOfSymfony/FOSRestBundle#740]
I have an entity on which i have a "enabled" value.

I created a form type for that entity and now i am not sure what type of field to use for the boolean values. If it was a standard web project the "checkbox" would work fine, but since its a REST service the "checkbox" type doesn't work as it should.

Using a "checkbox" field i have to remove the attribute from the JSON in order to consider it FALSE. Since i am providing the API for some clients and the client, of course, wants to use the "true" and "false" keywords (or "0" and "1") what can i do to allow this values for booleans?

I already check the issue #296 but doesn't seem to have a proper solution for this case, just and listener that removes attributes that are explicit set to false. Which doesn't seem the right way to do it.

Link to the gist:
https://gist.github.com/3690671

Cheers,
Nuno

**Comment by neFAST** [comment]
Hi @nunojsferreira Did you open an issue on NelmioApiDocBundle repository? Did they fix it?
