### ISSUE TITLE
Using plural name in route with single name in the action

### ISSUE THREAD

**Issue by AyhamAlzoubi** [FriendsOfSymfony/FOSRestBundle#752]
Hey
I am using FostRestBundle with Symfony2

I want to use the route  /users/{id} with methods PUT, POST, DELETE

I have the actions:  

```
deleteUsersAction($id)
postUsersAction($request)
putUserAction($id)
```

can't we have it as: `deleteUserAction($id)`  with the same route  /users/{id}
because it makes sense to have one user has this $id

this works only for PUT but not for POST and DELETE ?

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954
