### ISSUE TITLE
@QueryParam + default = bundle's extension values injected

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSRestBundle#774]
Hi, I'm dealing with dates, so I would like to inject a self initialized parameter (comes from my bundle extension class).
<b>$container->setParameter('today_object', $today); </b>
Parameter to inject; datetime, as %today_object%.

<code>
@QueryParam(name="start", nullable=true, requirements="^(\d{2})([-|\/])(\d{2})([-|\/])(\d{4})?|^(\d{4})([-|\/])(\d{2})([-|\/])(\d{2})?", default="<b>%today_object%</b>")
  
 public function cgetAction(ParamFetcher $paramFetcher)
    {
      ... 
    }
</code>

How could this be achieved, directly in the method annotations?
Like this: <b>default="%today_object%"</b>?
It doesn't work for me.
Thanks in advance.

**Comment by lsmith77** [comment]
I guess we could do this via the expression language?

**Comment by Ener-Getick** [comment]
You can also do this by adding your ``@QueryParam`` dynamically:
```php
<?php

    use FOS\RestBundle\Request\ParamFetcher;
    use FOS\RestBundle\Controller\Annotations\QueryParam;

    class FooController extends Controller
    {
        public function getArticlesAction(ParamFetcher $paramFetcher)
        {
            $dynamicParam = new QueryParam();
            $dynamicParam->name = "dynamic_query";
            $dynamicParam->default = $this->getParameter('today_object');
            $dynamicParam->requirements = "\d+";
            $paramFetcher->addParam($dynamicParam);
        }
    }
```

**Comment by Ener-Getick** [comment]
This was fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1240
