### ISSUE TITLE
Add Error Message To @RequestParam

### ISSUE THREAD

**Issue by bassrock** [FriendsOfSymfony/FOSRestBundle#799]
I think the ability to add custom error messages to each @RequestParam and @QueryParam would be a great improvement. Currently it outputs a default message like: 
``` "Request parameter \"first_name\" is empty" ```

The annotations should probably add 2 new fields:
* Constraint Failed Error Message
* Empty Error Message

This would allow the developer to define custom error messages for api services right in the constraints.  

If the bundle already does something like this let me know. I have tried using the error mapping, but that will only give you a generalized message for all types of that exception.

**Comment by Ener-Getick** [comment]
If you want still want to improve this, it's now easier.

You have to update https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/Annotations/AbstractScalarParam.php
