### ISSUE TITLE
serializerGroups annotation not behaving as expected

### ISSUE THREAD

**Issue by robcaw** [FriendsOfSymfony/FOSRestBundle#822]
I'm trying to set up exclusion policies for my entities using yaml for the properties, and setting the serializerGroups on my view actions.
```
/**
     * @Rest\View(
     *      serializerGroups={"api_message"}
     * )
     * @param Request $request
     * @return \FOS\RestBundle\View\View
*/
```
However, the annotation serializerGroups, although recognised, doesn't set the groups for the serializer. Instead, the View's  SerializationContext must be set:

`$view->setSerializationContext(SerializationContext::create()->setGroups(['api_message']));`

**Comment by robertblock** [comment]
Same problem here.

I have not been able to upgrade from FOSRestBundle 1.2.* since the @Rest\View annotation serializerGroups action does not work after upgrading to 1.3.*, 1.4.* or 1.5.*.

I have no doubt it's my fault, I'm just not sure what I'm doing wrong.

**Comment by lsmith77** [comment]
can you paste your controller code?

**Comment by robertblock** [comment]
Sure. Let me know if this is enough:
```
use Doctrine\DBAL\DBALException;
use JMS\Serializer\SerializationContext;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use FOS\RestBundle\View\View AS FOSView;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use FOS\RestBundle\Controller\Annotations as Rest;
use JMS\SecurityExtraBundle\Annotation as Security;

class StudentRestController extends Controller
{
    /**
     * Get student by id.
     *
     * @Rest\View(serializerGroups={"sg-default", "sg-details"})
     *
     * @ApiDoc()
     *
     * @param Student $student
     * @return FOSView
     *
     * @Security\Secure("ROLE_USER")
     */
    public function getStudentAction(Student $student)
    {
        return FOSView::create()->setStatusCode(200)->setData($student);
    }
}
```

**Comment by robertblock** [comment]
Without looking too deeply into the code, it looks like the inclusion of `$customViewDefined` in `ViewResponseListener` is causing this issue. 

Again, without looking too deeply into the code, there may be a logic error on line 89. I think serializer groups should be applied if `$customViewDefined == true`:

```
if ($configuration->getSerializerGroups() && !$customViewDefined) {
```

should be:

```
if ($configuration->getSerializerGroups() && $customViewDefined) {
``` 

I've never actually contributed to a project, but I can look into the process and give it a go if you'd like me to handle this one?

**Comment by hallabro** [comment]
@robertblock I have the same issue and your change seems to work for me. Until a change has been implementend I will make sure I return a `FOS\RestBundle\View\View` which also seems to work (`return $this->view($data, 200);`).

**Comment by robertblock** [comment]
@hallabro Thanks for the feedback!

I'm curious as to the intention behind `$customViewDefined`. I can't figure out why it was only used in checking whether to use groups when serializing.

**Comment by lsmith77** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/692

the issue is that you are creating the View instance manually instead of letting the Listener create the instance.

**Comment by ghanbari** [comment]
@stof 
Hi, i was confused that when view annotaion is working, i see your answer in top:

>Annotations are meant to configure the View when you don't create it yourself but return only the data and expect the ViewListener to build the View object itself AFAIK

I can use `@View` when return `$view` obj, I can set `statusCode`, `template`, `templateVar` but can not set `serializerGroups` or `serializerEnableMaxDepthChecks` (if i set, these no will work). why?

**Comment by stilllife00** [comment]
Referencing https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1875 which might be related
