### ISSUE TITLE
Inject RequestStack instead of Request

### ISSUE THREAD

**Issue by gitnik** [FriendsOfSymfony/FOSRestBundle#824]
Instead of injecting the Request itself, it is advised to instead inject the RequestStack as this won't lead to issues with wrong/widened scopes

**Comment by lsmith77** [comment]
fixed via https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1104

**Comment by lsmith77** [comment]
some last bits are done with https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1107/files

**Comment by gitnik** [comment]
So I'm guessing this can be closed then?
