### ISSUE TITLE
securityContext has no token

### ISSUE THREAD

**Issue by gnat42** [FriendsOfSymfony/FOSRestBundle#825]
Hello,

  So I'm at a complete loss as to how this has occurred however the DisableCSRFExtension is not working for me. When I went in to debug it I noticed that it is returning from line 37 since $this->securityContext->getToken() is returning false.

  How does it happen that the securityContext has no token, yet I'm allowed through (my other non form based calls return data and are restricted by the ACLs this particular user has. I have a simple test api that returns the users roles and I added a test for whether the securityContext has a token, its returning that it does - somehow the csrf extension thinks it doesn't and I'm confused by the two opposing bits of information I'm getting from debugging. 

Help!?!

For example here's the snippet for the test action:

```

    /**
     * Api Test Action,
     *
     * @ApiDoc(
     *   resource = true,
     *   description = "Test API Access over OAuth2",
     *   statusCodes = {
     *     200 = "Returned when successful",
     *     404 = "Returned when the case is not found",
     *     401 = "Invalid credentials"
     *   }
     * )
     * @REST\GET("/test")
    */
    public function testAction()
    {
        $v = new View();
        $v->setData(array('username'=>$this->getUser()->getUsername(),
                          'roles'=>$this->getUser()->getRoles(),
                          'hasToken'=>($this->get('security.context')->getToken())?'Yes':'No'));

        return $this->handleView($v);
    }
```

**Comment by TrkiSF2** [comment]
@gnat42 thank you for a tip! I had something similar. 

    welcomepagebundle.listener.request:
        class: TB\WelcomePageBundle\Listener\CustomRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ @session, @request_stack, @security.context, @tb_user.user.managment ]

Was from some magical reason destroying my FosOauth API.

**Comment by lsmith77** [comment]
would be good if someone could turn this into a doc PR then!

**Comment by gnat42** [comment]
@TrkiSF2  your constructor looks fine to me. What issue are you experiencing? The way I found the solution to mine was to start dying at various places in the stack track of my issue. Eventually I found myself in the symfony DIC bootstrap code and figured out that I was trying to build forms too early...

What's your particular problem?

**Comment by TrkiSF2** [comment]
@gnat42 I am experiencing the same issue. 

When I call this method from onKernelRequest:

    /**
     * @param GetResponseEvent $event
     */
    protected function trackLoggedInUserVisit(GetResponseEvent $event)
    {
        if ($event->isMasterRequest() && $this->securityContext->isGranted('ROLE_USER'))
        {
            $this->oUserManagment->saveLoginActivity($this->securityContext->getToken()->getUser());
        }
    }
