### ISSUE TITLE
single restful controller routing doc does not show name_prefix snippet

### ISSUE THREAD

**Issue by jrobeson** [FriendsOfSymfony/FOSRestBundle#828]
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/5-automatic-route-generation_single-restful-controller.md

it says

> Notice the name_prefix: my_bundle_ option. It's useful to prefix the generated controller routes to organize your several resources paths. Take care that you can use name_prefix on an import only when the file is imported itself with the type rest. The parent option is used in sub-resources as we will see in the next section for multiple RESTful controller routes.

However, name_prefix is not shown.

**Comment by lsmith77** [comment]
ping

**Comment by lsmith77** [comment]
ping

**Comment by Tobion** [comment]
Closing as automatic route generation is deprecated: #1954
