### ISSUE TITLE
support new validation interfaces added in symfony 2.5

### ISSUE THREAD

**Issue by EduardTrayan** [FriendsOfSymfony/FOSRestBundle#846]
Hi.

I'm use symfony 2.5 and your bundle with version 1.4.2. According to [Symfony 2.5 upgrade plan](https://github.com/symfony/symfony/blob/master/UPGRADE-2.5.md#validator), `Symfony\Component\Validator\ValidatorInterface` marked as deprecated, and I received an exception 
```
ContextErrorException: Catchable Fatal Error: Argument 4 passed to FOS\RestBundle\Request\ParamFetcher::__construct() must implement interface Symfony\Component\Validator\ValidatorInterface, instance of Symfony\Component\Validator\Validator\RecursiveValidator given
```

Also I'm use internal symfony validator service.
How we can use this bundle with symfony 2.5?

**Comment by lsmith77** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/945

**Comment by mpoiriert** [comment]
I just wan to know how the "traverse" and "deep" parameters are supported in 2.5 ?
