### ISSUE TITLE
Add an exclusion strategy to the serialization context

### ISSUE THREAD

**Issue by lucascourot** [FriendsOfSymfony/FOSRestBundle#865]
I'm implementing a fields exclusion strategy as described in this article http://jolicode.com/blog/how-to-implement-your-own-fields-inclusion-rules-with-jms-serializer.

I want to add this feature to all my routes of my API when the "fields" parameter is provided, that's why I don't want to add anything in my controllers.

I found a way to override the default JMS's SerializationContext. I had to extend the `fos_rest.view_response_listener.class` and override the whole `onKernelView` method. Then I added my code after this line https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.4.2/EventListener/ViewResponseListener.php#L98.

``` php
// ...
if ($event->getRequest()->isMethod('GET') && $event->getRequest()->query->has('fields')) {
    $context = $view->getSerializationContext() ?: new SerializationContext();
    $context->addExclusionStrategy(
        new FieldsListExclusionStrategy(
            $event->getRequest()->query->get('fields')
        )
    );
    $view->setSerializationContext($context);
}
// ...
```

But I'm wondering if there is a way to avoid overriding the whole `onKernelView` method for just editing the view's serialization context?

**Comment by bblue** [comment]
Can this issue be re-opened? I need pretty much exactly the same feature as the author (same article even), and I need to access the JMS serialization context (preferably from a controller). 

It appears however that the `$view->setSerializationContext($context);` is no longer available.

I looked into a compiler pass for the JMSSerializationAdapter, but the `convertContext` method is `private`, so no luck there.

As a side-note, the [documentation ](http://symfony.com/doc/current/bundles/FOSRestBundle/view_response_listener.html) still references  `$view->setSerializationContext($context);`

**Comment by Ener-Getick** [comment]
@bblue see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1536
