### ISSUE TITLE
[META] API versioning 

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#890]
I am closing all previous tickets/PRs related to versioning that were open at the time this ticket was opened and simply linking them here for easier access:
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/136
https://github.com/FriendsOfSymfony/FOSRestBundle/issues/329
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/561
https://github.com/FriendsOfSymfony/FOSRestBundle/issues/610
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/632
https://github.com/FriendsOfSymfony/FOSRestBundle/issues/638

Furthermore I would like to keep future discussions here as well.

**Comment by smilesrg** [comment]
@lsmith77 Is there any progress on this? API versioning is a really must-have feature!

**Comment by lsmith77** [comment]
the current state is this:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.5.0-RC3/Resources/doc/3-listener-support.md#media-type-version-extraction
