### ISSUE TITLE
Annotation namespace not loaded

### ISSUE THREAD

**Issue by TNAJanssen** [FriendsOfSymfony/FOSRestBundle#895]
When using this in an composer package i get this error:

  [Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@FOS\RestBundle\Controller\Annotations\POST" in method SomeController::someAction() does not exist, or could not be auto-loaded.

But i only get this error on Linux environment not on a Mac environment, production, testing or development doesn't make any difference! Autoload and installed php, composer version etc is the same...

**Comment by asimsagirabbasi** [comment]
hi , i am facing same prblm every thing is working fine on windows localhost but not in Linux shared hosting. please let me know how i can solve it.thnks
