### ISSUE TITLE
AccessorOrder annotation does not work

### ISSUE THREAD

**Issue by rodrigorigotti** [FriendsOfSymfony/FOSRestBundle#921]
I'm using a couple of FOSREstBundle annotations in my entities, but `AccessorOrder` does not seem to work properly. When request a collection of entities or a single one, the properties' order always falls back to alphabetical when I set it to `"custom"`, along with properties' order.

Entity:

```
/**
 * @JMSSerializer\AccessorOrder("custom", custom={"id", "name", "description"})
 * @JMSSerializer\ExclusionPolicy("all")
 */
class Discipline
{
    /**
     * @JMSSerializer\Expose
     */
    protected $id;

    /**
     * @JMSSerializer\Expose
     */
    protected $name;

    /**
     * @JMSSerializer\Expose
     */
    protected $description;

    // rest of the class omitted for the sake of simplicity
}
```

Call:

```
$ http http://localhost/accessor-order/disciplines/47
```

Response:

```
{
    "entity": {
        "description": "Databases discipline",
        "id": 47,
        "name": "Databases"
    }
}
```

**Comment by lsmith77** [comment]
this is a JMS serializer issue

**Comment by hacfi** [comment]
FYI: Just came across this issue myself and this should work fine (now?) as long as you don’t use the resulting underscore names but the property names of your class instead.
