### ISSUE TITLE
QueryParam annotation: range in requirements ?

### ISSUE THREAD

**Issue by gou1** [FriendsOfSymfony/FOSRestBundle#923]
Hello,

Reading the documentation, I couldn't find how to specify a **range for an integer parameter** via the ParamFetcherListener and **QueryParam annotation**.

Typical use case is when you have offset/limit parameter and you want to specify a max value for limit to avoid users requesting gazillion items at a time. 

Obviously one can do it via a regexp (doable albeit not very practical), or check in the controller itself, but is there a best practice / simplier way to this?

**Comment by cve** [comment]
http://symfony.com/doc/current/reference/constraints/Range.html :)
