### ISSUE TITLE
Switching from `dev` to `prod` database connection error

### ISSUE THREAD

**Issue by eddiejaoude** [FriendsOfSymfony/FOSRestBundle#924]
No database code has been setup yet, this is a new rep, but when going from `dev` to `prod` in the same server, there is a database connection error:

```
[Doctrine\DBAL\Exception\ConnectionException]                              
         An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused  

 [Doctrine\DBAL\Driver\PDOException]        
         SQLSTATE[HY000] [2002] Connection refused  

 [PDOException]                             
         SQLSTATE[HY000] [2002] Connection refused  
```

Does the bundle do something different in `prod` mode?

**Comment by ben25belot** [comment]
Hi Eddie,

I'm sorry to "unearth" this conversation but I have the same problem like you.
I don't use FOSRestBundle but FOSUserBundle and when I switch from dev to prod, I have a database  connection error "SQLSTATE[HY000] [2002] Connection refused" like you.
How did you fix this issue ?

Thank you in advance for your answer
Benji

**Comment by stof** [comment]
@ben25belot if you don't use this bundle, this is clearly the wrong place to ask for support.

**Comment by ben25belot** [comment]
Eddie said his error didn't come from this bundle.
So I have probably the same problem even if I don't use the same bundle. No ?
I wanted to contact Eddie in a different way but I didn't know how.

**Comment by eddiejaoude** [comment]
Sorry, I don't remember exactly what happened, so much has happened since then. I should have made notes at the time :(

**Comment by MisterIcy** [comment]
It's not a FOSRestBundle problem, you just have to cache:clear your production enviroment
(Yeap, I lost a couple of hours to figure this out)
