### ISSUE TITLE
Custom ExceptionWrapperHandler seems to be ignored

### ISSUE THREAD

**Issue by ninjabachelor** [FriendsOfSymfony/FOSRestBundle#926]
Hi,
my app throws an exception like:
```
throw new HttpException( 400, 'My custom message' );
```
I expect the response to be:
```
{"error":{"code":400,"message":"My custom message"}}
```
but I get:
```
{"error":{"code":400,"message":"Bad Request"}}
```
I tried to customize the error message with an ExceptionWrapperHandler, defined as:
```
fos_rest:
    view:
        exception_wrapper_handler: AppBundle\Handler\ExceptionWrapperHandle
```
but this declaration seems to be ignored. Am I missing something?

Thanks

**Comment by lsmith77** [comment]
I made some changes here .. its now also possible to configure a service:
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/942
