### ISSUE TITLE
Documentation bug: ExceptionController support part

### ISSUE THREAD

**Issue by kwn** [FriendsOfSymfony/FOSRestBundle#928]
Decumentation suggests:

"The ExceptionController can be enabled either via the FOSRestBundle configuration and optionally an explicit controller action can be configured as well"

```yaml
fos_rest:
    exception:
        enabled: true
```

If I set config that way I get an exception ```InvalidConfigurationException: Unrecognized options "enabled" under "fos_rest.exception"```. I reviewed the configuration tree builder and indeed, there's no option called "enabled". Is ExceptionController always turned on?

**Comment by lsmith77** [comment]
this is only possible since version 1.5.0 (note there is no stable release yet). I assume you are still on an earlier version. Please check the docs that there installed along with your version of the Bundle.

**Comment by kwn** [comment]
Oh, ok. Thanks for explanation.
