### ISSUE TITLE
Switch the documentation from Markdown to ReStructuredText

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSRestBundle#929]
If FOSRestBundle maintainers agree on this, I'll send a pull request changing its documentation format from Markdown to reStructuredText.

In addition to being the official Symfony doc format, reST will allow us to quickly integrate this documentation on symfony.com bundles section. This will increase the exposure of the bundle and hopefully it will bring in more contributors.

**Comment by lsmith77** [comment]
sounds good to me, ie the integration into symfony.com docs :)

**Comment by lsmith77** [comment]
maybe while you are at it you can also have a look at https://github.com/FriendsOfSymfony/FOSRestBundle/pull/855

in general the docs were created evolutionary ... meaning as the above PR tried to start, we might need to restructure them to better accommodate the fact that the Bundle has grown a lot.

**Comment by willdurand** [comment]
:+1:

**Comment by stof** [comment]
@javiereguiluz What is the ETA for the rendering of the bundle doc on symfony.com after it is converted ? Will we need to setup readthedocs in the meantime (we are already using it for FOSHttpCache and its bundle)

**Comment by javiereguiluz** [comment]
@stof the integration will be immediate. I've successfully tested my local setup with several bundles, so everything is ready.

**Comment by stof** [comment]
great

**Comment by javiereguiluz** [comment]
@lsmith77 given my lack of experience with the bundle, dealing with #855 would take me lot of time. That's why I prefer to quickly integrate FOSRestBundle in symfony.com (done in #930) and then let's discuss about how to improve the contents.
