### ISSUE TITLE
DoctrineParamConverter is always trying to retrieve by ID

### ISSUE THREAD

**Issue by tristanbes** [FriendsOfSymfony/FOSRestBundle#932]
Hi,

I'm building a REST API and here's the problem I deal with:

```
/**
 * Client controller.
 * @RouteResource("Client")
 */
class ClientRestController extends Controller
{
    /**
     * @View(serializerEnableMaxDepthChecks=true)
     *
     * @return Response
     *
     */
    public function getAction(Client $code)
    {
        return $code;
    }
```

`code` is a property of `Client` object, and since the generated route is `/clients/{code}.{_format}` I except Doctrine to do a `findOneByCode()` (or any equivalent involving retrieving the object by the `code` property).

Instead, it tries a `find` which retrieve object via its `id` and naturally throws a `HttpNotFound`

When adding : 

`@ParamConverter("code", class="Model:Client", options={"code" = "code"})`

It has no effect.
But when adding the `repository_method`, it solves the problem.

`@ParamConverter("code", class="Model:Client", options={"code" = "code", "repository_method" = "findOneByCode"})`

Does this bundle in someway interfer with the `DoctrineParamConverter` logic ?
I'm under Symfony2.6 and RestBunde 1.5.*. My bundle cfg can be found there : https://gist.github.com/tristanbes/09ec652f5e83bd0216f1

**Comment by merk** [comment]
Your options is wrong for mapping custom properties, you need to use `options={"mapping"={"code" = "code"}}`

**Comment by tristanbes** [comment]
Thanks @merk , indeed it works better, but as far as I can remember, you don't have to specify custom mapping when the route parameter equals the property in your object. Why do we have to do this when dealing with `FosRestBundle` ?

**Comment by merk** [comment]
To be honest I'm not sure. It shouldnt be modified by the bundle afaik.

Set a breakpoint in here to see whats going on: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Request/ParamConverter/DoctrineParamConverter.php#L125

**Comment by tristanbes** [comment]
Already did, and the it only goes in the `find` method, calls `getIdenfier` which returns the value of my `code` property, then goes to line 96 and do a `find(value)` which is wrong and triggers a `HttpNotFound`.

**Comment by merk** [comment]
Weird. Last time I used the annotation/automatic route generation I wasnt aware of any modification to the attributes routing array.

find() should be returning false if there is no identifier property in the attribute bag..

**Comment by lsmith77** [comment]
I never used param converters .. did you check via ``app/console router:debug [route_name]`` if your expectations are met?

**Comment by tristanbes** [comment]
Yes the route parameters are the right one ( `/clients/{code}.json` )

**Comment by lsmith77** [comment]
can you create a failing test case?

**Comment by bblue** [comment]
I am successfully using the paramconverter and fetching objects by different keys when using the automatic route generation (I'm on 2.0). Never had an issue with this...

Example code below that works.


    /**
     * Find object by different property than its ID
     *
     * @ParamConverter("referral", options={"mapping":{"referral" = "anotherPropertyThanID"}})
     * @param Referral $referral
     */
    public function getAction(Referral $referral)
    {
        // ...
    }

Accessible via http://~/myControllerName/{referral}
