### ISSUE TITLE
Will this bundle follow the version semantics?

### ISSUE THREAD

**Issue by tonivdv** [FriendsOfSymfony/FOSRestBundle#951]
@lsmith77  Maybe it's already the case, but I want confirmation on this. Will this bundle follow the rules of http://semver.org/ ?

Or are there still things in the bundle that needs to be tweaked before enforcing it?

**Comment by lsmith77** [comment]
At this point we are indeed following semver. All "BC breaks" noted in the upgrading guide are essentially considered to be bug fixes.

**Comment by tonivdv** [comment]
Perect. Thanks @lsmith77 .

**Comment by lsmith77** [comment]
just for the record, I do not see bumping the minimal version requirement as a BC break:
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/952/

that being said, I think that FOSRestBundle 1.x will remain compatible with Symfony 2.3, ie. dropping 2.3 support will likely happen in a 2.x version.

**Comment by tonivdv** [comment]
@lsmith77 I agree this is not the same. I was merely referring to the FOSRestBundle API that if I upgrade minor version it should work out of the box. Document I guess will have to point out that 1.5 will be latest compatible with sf 2.2 though (something like that)
