### ISSUE TITLE
FOSUserBundle post method to create new user returns error for repeated password field

### ISSUE THREAD

**Issue by sergiu-popa** [FriendsOfSymfony/FOSRestBundle#956]
Hello,

I'm using this code for a POST method to create a new user:
```php
public function postUsersAction(ParamFetcher $paramFetcher)
{
  $request = $this->getRequest();
  $userManager = $this->container->get('fos_user.user_manager');
  $user = $userManager->createUser();
  $user->setUsername($request->get('username'));
  $user->setEmail($request->get('email'));
  $user->setPlainPassword($request->get('plainPassword'));
  $user->addRole($request->get('role'));
  $validator = $this->get('validator');

  $errors = $validator->validate($user, array('Registration'));
  if (count($errors) == 0) {
    $userManager->updateUser($user);
    $param = array("slug" => $user->getUsername());
    $view = RouteRedirectView::create("byexample_demo_userrest_get_user", $param);
  } else {
    $view = $this->get_errors_view($errors);
  }
  return $view;
}
```
Although I'm sending "plainPassword" in the request, I'm still getting the message error: *Write your password* meaning that the validator fails to validate the password. I know the password field it's a repeated field in the registration form. I also tried to send two parameters: "plainPassword_first" and "plainPassword_second" but to no success.

Any help please?

**Edit**: resolved

**Comment by sergiu-popa** [comment]
Did something change? I'm using this code but the POST parameters is empty. I don't get it... last week this was working fine:

```php
public function postUsersAction(Request $request)
{
  $userManager = $this->container->get('fos_user.user_manager');
  $user = $userManager->createUser();
  $user->setUsername($request->get('username'));
// $request->get('username') is empty
```

**Comment by lsmith77** [comment]
could be related to the following: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/883

**Comment by johndodev** [comment]
Same for me, I tried lot of body_listener config but query remain empty.

**Comment by luxilio** [comment]
What are you using to make the post request? CURL in the console? REST Console in Google Chrome?

**Comment by johndodev** [comment]
I use nelmioApiDocBundle to test POST endpoints, I put a json on "content" field and use this trick:

    $data = json_decode($request->getContent(), true) ?: [];
    $request->request->replace($data);'''

**Comment by luxilio** [comment]
Try using cURL in the console. I had problems with REST Console in Chrome because I didn't check an option (RAW Body checkbox under Request Payload - although I was using the left column Request parameters).

**Comment by johndodev** [comment]
Hm not sure I understood correctly what body_listener should do, I'm out of this issue ;)

**Comment by lsmith77** [comment]
@johndodev by default PHP only decodes urlencode POSTs (ie from an html form) but if you send data as json/xml/etc it will not be decoded and so they will not show in the Symfony request class. this is where the body listener helps .. it looks at the request content type and if its json/xml/etc it will attempt to decode this data to an array and set it on the request instance just as if the data was submitted via an html form.
