### ISSUE TITLE
Manual Array Keys Not Renamed

### ISSUE THREAD

**Issue by bassrock** [FriendsOfSymfony/FOSRestBundle#957]
I am creating a manual array and then outputting it via a Symfony 2 Controller using the @View() annotation. 

When I create the array with mixed types of keys ie camel case and underscores. The serialized array from the View annotation is not renaming the keys to match the default naming property of the application:

```php
$data = array();
$data['net_proceeds'] = $tNetProceeds;
$data['mostRecents'] = $this->getMostRecents(4);
```

Returns:

```json
{
  "mostRecents": [
    
  ],
  "net_proceeds": 0
}
```

And when I create a PropertyNamingStrategyInterface and use it via the configuration like so:

```yml
parameters:
    jms_serializer.camel_case_naming_strategy.class: Acme\APIBundle\Serializer\UnderscoreNamingStrategy
```

Only the actual objects become used by the PropertyNamingStrategyInterface not the outer array.

**Comment by lsmith77** [comment]
can you create a test case? or at least a fork of https://github.com/gimler/symfony-rest-edition to illustrate the problem?

**Comment by bassrock** [comment]
The test case is simple create a controller function that serializes the above array.

**Comment by lsmith77** [comment]
it would still be good if you could provide me with the test case .. time is short, so it will help me spend my time on writing a fix .. that being said .. right now I am not sure how this Bundle is affecting this behavior .. it might just be a JMS serializer issue.
