### ISSUE TITLE
Testing error pages broken

### ISSUE THREAD

**Issue by raistlin** [FriendsOfSymfony/FOSRestBundle#958]
ExceptionHandling of this bundle brokes http://symfony.com/blog/new-in-symfony-2-6-error-page-previews

Steps to reproduce
* In a Symfony 2.6.3 project
* Set up a custom template for 404 error.

````
#app/config/config.yml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
````

Go to http://localhost/app_dev.php/_error/404

**Comment by lsmith77** [comment]
@MalteWunsch can you help us figure out a way to bring this feature to this Bundle? note that the Bundle still supports Symfony 2.3+ versions but of course its sufficient that we ensure that it doesnt break 2.3-2.5 but then works with 2.6+

**Comment by lsmith77** [comment]
sorry .. maybe I got the wrong github account here and the original feature was added by @mpdude to Symfony 2.6

**Comment by mpdude** [comment]
@Maltewunsch and/or me will have a look at this!

**Comment by lsmith77** [comment]
awesome .. thx!

**Comment by lsmith77** [comment]
depending on what needs to change this will be put into a 1.5 bug fix release .. or it will have to wait until 1.6.0

**Comment by lsmith77** [comment]
@mpdude / @maltewunsch ping

**Comment by lsmith77** [comment]
one more ping

**Comment by stof** [comment]
@mpdude @MalteWunsch ping

**Comment by mpdude** [comment]
Yes, sorry for the delay
