### ISSUE TITLE
fos_rest.converter.request_body

### ISSUE THREAD

**Issue by peshi** [FriendsOfSymfony/FOSRestBundle#959]
The service "fos_rest.converter.request_body" has a dependency on a non-existent parameter "fos_rest.converter.request_body.class".

**Comment by peshi** [comment]
Is there anything I missed? Using 'dev-master'

**Comment by xabbuh** [comment]
You could try to update again. The parameter was added back in a336335826934d96ec572bfdb283e047f79becfd.

**Comment by peshi** [comment]
I am using the latest, I still have the issue when it is enabled.

If I disable the body_converter, the issue is gone.
```
fos_rest:
    ...
    body_converter:
       enabled: false
```

**Comment by merk** [comment]
Use the latest stable version.

**Comment by xabbuh** [comment]
@merk Can you reopen? This is indeed an issue (see #961).

**Comment by peshi** [comment]
@xabbuh Good catch, thanks for the solution.

**Comment by merk** [comment]
Sorry, missed that in my glance - PR has been merged
