### ISSUE TITLE
[QueryParam] Nullable array with validation

### ISSUE THREAD

**Issue by eliecharra** [FriendsOfSymfony/FOSRestBundle#960]
In **1.4.2** I had the following behaviour to allow an optional array param and array item validation when array is not null :

```php
use FOS\RestBundle\Controller\Annotations\QueryParam;

     /*
      * @QueryParam(array=true, name="category_ids", requirements="\d+", strict=true, nullable=true, description="Array of container categories ids : category_ids[]=x&category_ids[]=x")
      */
```

Now in 1.5.0 when I submit an empty param I get
```json
{
  "code": 400,
  "message": "Query parameter value of 'category_ids' is not an array"
}
```

Seems like #910 is breaking this in 1.5.0.
I would like to allow an empty array param but dont wanna loose the validation.
If I set strict to false i'm loosing array items validation.

Easy to reproduce with the above annotation.

Is my initial annotation badly crafted or a BC break ?
I have not looked into the code, but it seems like nullable param for an array is not considered.

**Comment by eugef** [comment]
If parameter is array then `strict` is used to determine if parameter is optional or not. 
Probably this is wrong and `nullable` should be used instead (for now `nullable` is not used at all for array parameter validation - see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2437a4fafb232bccac0dff71f9d2ada97e19155c/Request/ParamFetcher.php#L138).

If we use both `strict` and `nullable` options then following configurations are possible that cover all cases:
* `nullable=true` and `strict=true` - array parameter is optional, items validation is strict
* `nullable=false` and `strict=true` - array parameter is required, items validation is strict
* `nullable=true` and `strict=false` - array parameter is optional, items validation is not strict
* `nullable=false` and `strict=false` - array parameter is required, items validation is not strict

@lsmith77 , what do you think?

**Comment by eliecharra** [comment]
> nullable=true and strict=true - array parameter is optional, items validation is strict
> nullable=false and strict=true - array parameter is required, items validation is strict
> nullable=true and strict=false - array parameter is optional, items validation is not strict
> nullable=false and strict=false - array parameter is required, items validation is not strict

@eugef @lsmith77 This behavior is better.
strict param shoud be user for validation **only**.
and nullable param shoud be user for optional purpose

**Comment by lsmith77** [comment]
+1

**Comment by ruscon** [comment]
+1 
Can you add this hotfix to the current release ?

**Comment by eugef** [comment]
@eliecharra , at line https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2437a4fafb232bccac0dff71f9d2ada97e19155c/Request/ParamFetcher.php#L126 `strict` also should be replaced with `nullable`

And probably tests should be adjusted for the new behavior.

**Comment by lsmith77** [comment]
if someone sends a PR I can quickly release

**Comment by eliecharra** [comment]
@lsmith77 PR #963 in progress, i'm fixing tests

**Comment by lsmith77** [comment]
can you all test the PR as well? want to make sure I do not get another regression and I do not have a good code base I can use for testing this beyond our tests.

**Comment by eliecharra** [comment]
Just tried to add a test to cover #910 break but couldn't make it work, if someone has some time ...
