### ISSUE TITLE
trying to add a new user and get an exception

### ISSUE THREAD

**Issue by DorZ11** [FriendsOfSymfony/FOSRestBundle#972]
HI, 

Im new and symfony and fos and also to PHP..
I integrate FOS to my first application and after two days I got problems with my wamp so I reinstall it. after that I created again my db and tried to add user (I didnt tried it before my wamp got reinstalled).
the exception that I get is this:

An exception occurred while executing 'INSERT INTO fos_user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, Title, Description, Location) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["testUser", "testuser", "something@gmail.com", "something@gmail.com", 1, "e27rn8ub08gsw0kckwcso40owkwgg8s", "REOtoKEu7fjpQoQ1Exua+Qc8HRXL2k84Bal0VXgOFXhPGV9PgZ\/n3iqo8jej1libpRZnGwnBTm1VdHtSXzoV9Q==", null, 0, 0, null, null, null, "a:0:{}", 0, null, null, null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'Title' cannot be null 

two more things. I enter to the "Overriding Default FOSUserBundle Templates" post and in it its say that I should have a layout.html.twig in my app/resources folder but I dont have it at all. is it ok? maybe I didnt integrate it right? any way I looked for the issue in google and find that I need to put
parent::__construct();
into my costume user class, but It was already so its not the problem.

hope to get answers fast so I can continue learning.

thanks in advance,
Dor.

**Comment by lsmith77** [comment]
looks like you opened the ticket on the wrong repo.
