### ISSUE TITLE
Array Normalizer doesn't work for multipart/form-data

### ISSUE THREAD

**Issue by AlexStansfield** [FriendsOfSymfony/FOSRestBundle#976]
Just ran into this problem when testing some code. Works fine with json and x-www-form-urlencoded.

The problem appears to be in this line:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener/BodyListener.php#L90

It checks the content type matches multipart/form-data. However any multipart/form-data content type string will also contain a boundary value. 

Perhaps the content-type needs to be exploded on ';' and then the first value matched. I have also noticed some clients adding a charset onto a application/x-www-form-urlencoded content type so it would solve that problem too.

**Comment by lsmith77** [comment]
sounds reasonable .. can you work on a PR?

**Comment by AlexStansfield** [comment]
Sorry only just caught this reply and see @florianv beat me to it.
