### ISSUE TITLE
Annotation prefix does not work

### ISSUE THREAD

**Issue by alex-ception** [FriendsOfSymfony/FOSRestBundle#977]
Hi,

We are trying to use the annotation "Prefix". It seems that it does not work (or we misunderstood something). Here is the code, and below the routing generated.

namespace AppBundle\Controller;
    
    use FOS\RestBundle\Controller\Annotations as Rest;
    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    
    /**
     * UserController
     *
     * @Rest\Prefix("/foo")
     * @Rest\NamePrefix("api_1_users")
     */
    class UserController extends Controller
    {
        /**
         * @Rest\Post("/bar")
         */
        public function createAction()
        {
            var_dump('BRAAAAH');die;
            return $this->render('default/index.html.twig');
        }
    }

And for the routing generated (cache cleared) : 

	$ ./app/console ro:de
	[router] Current routes
	 Name                          Method   Scheme Host Path                              
	 homepage                      ANY      ANY    ANY  /                                 
	 app_user_create               POST     ANY    ANY  /bar     

Any help is welcome.

Thanks

**Comment by florianv** [comment]
I reproduced it with the latest bundle version and it works as expected:

```
Name              Method Scheme Host Path
api_1_userscreate POST   ANY    ANY  /foo/bar.{_format}
```

I think you are already loading the routes before `FOSRestBundle`, so make sure the user controller routes are not already loaded and clear your cache.

**Comment by lsmith77** [comment]
closing due to lack of feedback
