### ISSUE TITLE
Form entity field submit (PUT/POST) as array

### ISSUE THREAD

**Issue by backender** [FriendsOfSymfony/FOSRestBundle#984]
Hi guys,

Not sure if this issue is duplicate but I'm facing the same problem as described in the following stackoverflow question: http://stackoverflow.com/questions/19553884/symfony-forms-fos-rest

Is there a proper way to directly use the from a GET received {"array":{"id":1}} in a PUT/POST that is related to a form field type of "entity" with property id – instead of the {array:1}?

In fact, is writing my own EntityToArray transformer the way to go here, or is already something introduced by this bundle that works out of the box?

**Comment by lsmith77** [comment]
I do not think that we have anything for this in the Bundle. Of course you can customize the response structure via the serializer but it seems it would be more elegant to handle this on the server side, so your approach sounds sensible. If you can find a generic enough solution, we can maybe put it into this Bundle

/cc @webmozart

**Comment by webmozart** [comment]
I agree, writing a transformer sounds like a good solution to me. :)

**Comment by lsmith77** [comment]
closing this .. unless you want to keep it open until a solution is found for entities with composite primary keys?

**Comment by backender** [comment]
The case with the composite primary key seems rather rare. So to me it's ok.
