### ISSUE TITLE
Reorganize Util classes

### ISSUE THREAD

**Issue by florianv** [FriendsOfSymfony/FOSRestBundle#985]
I think there are a lot of classes in the `Util` namespace that could be located in more specific namespaces:

- `FormatNegotiator`, `MediaTypeNegotiatorInterface`, `FormatNegotiatorInterface` could be in a `Negotiation` namespace.

- `ViolationFormatter`, `ViolationFormatterInterface` could go to a `Validator` namespace.

- classes located in `Util/Inflector` could go to `Inflector`

**Comment by Ener-Getick** [comment]
@lsmith77 this has been fixed by #1107.
