### ISSUE TITLE
Using constructor injection in controller doesn't work

### ISSUE THREAD

**Issue by danielrvt** [FriendsOfSymfony/FOSRestBundle#990]
When using constructor injection in my controllers, automatic route generation is not allowing constructor injection, instead of the bundle:controller:action convention, it should use the service_name:actionAction convention.

For instace, supose I have this controller as a service:

```
    dnd_agent_controller:
        class: DnD\RaHApiBundle\Controller\AgentController
        arguments: ["@dnd_agent_repository", "@service_container"]
```
Then, with this routing:
```
agents_resource:
    type: rest
     resource: DnD\RaHApiBundle\Controller\AgentController
```
I'm not getting the dependency injected into my controller. However, If I use the following routing:
```
agents_resource:
  path: /agents
  defaults: { _controller: dnd_agent_controller:getallAction}
```
I do get the dependency injected, but using this, I'm bypassing the automatic route generation.

**Comment by lsmith77** [comment]
simply specify the service name as the resource.

**Comment by xero88** [comment]
Hi,

I got "Bundle "person_controller" does not exist or it is not enabled. " when I do this.
