### ISSUE TITLE
PATCH and collection fields

### ISSUE THREAD

**Issue by alexdrupal** [FriendsOfSymfony/FOSRestBundle#994]
Hi Folks.

I have a form with embedded collection field. I can't modify embedded collection items due to "This form should not contain extra fields" error.
Main form code:
```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('category')
            ->add('location')
            ->add('all_day')
            ->add('start_date', 'datetime', array(
                'widget' => 'single_text'
            ))
            ->add('end_date', 'datetime', array(
                'widget' => 'single_text'
            ))
            ->add('attendees', 'collection', array(
                'type' => new APIEventAttendeeFormType(),
                'cascade_validation' => true,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ))
        ;
    }
```

And I can create new Events with Multiply attendees, But if I want to PATCH any event, it won't allow me to specify attendee id in request. Below is example of request.
```javascript
{
    "event_data":
        {
            "attendees":[
                {"id":"9","email":"fsdfsdffddddsdsss", "phoneNumber":"+4637647"}
            ]
        }
}
```
It throws a message "This form should not contain extra fields". Both forms have "csrf_protection" set to false.

**Comment by tonivdv** [comment]
Hey @alexdrupal ,

When you submit do you do the following ? :

```php
$form->submit(
          $this->request,
          !$this
            ->request
            ->isMethod('PATCH')
        );
```

**Comment by alexdrupal** [comment]
Yes, I have exactly this code

**Comment by tonivdv** [comment]
Ok that's already good. However I'm afraid it will be hard to help without more code snippets. Can you share more?

**Comment by tonivdv** [comment]
Hey @alexdrupal ,

You still have the issue?

**Comment by loconox** [comment]
Hi, I had exactly the same issue. I was trying to update an entity with json data sent in a PATCH request.
I solved my issue by adding options 'allow_add', 'allow_delete' and 'delete_empty' on the collection field.
