### ISSUE TITLE
Related many to one entity is not being recognized

### ISSUE THREAD

**Issue by grzegorztomasiak** [FriendsOfSymfony/FOSRestBundle#995]
I have post a question on stackoverflow, since I am really stuck now.
Please refer to this link: http://stackoverflow.com/questions/29089923/fosrestbundle-post-many-to-one-relation

**Comment by lsmith77** [comment]
this is actually more a question about the Symfony2 form layer than this Bundle in particular. The key question is what array structure is needed and what additional steps might be needed in Doctrine ORM to make the form valid.

**Comment by grzegorztomasiak** [comment]
A guy on stackoverflow helped me out by putting locale: 1 instead of locale: {id: 1} but what if I want to select locale not by id, but by code, e.g. locale: { code: 'en' }, that's not possible.

**Comment by lsmith77** [comment]
then you will likely need to add a transformer. speaking of which, this might be relevant to you https://github.com/FriendsOfSymfony/FOSRestBundle/pull/987
