### ISSUE TITLE
Does the ExceptionController support backtraces?

### ISSUE THREAD

**Issue by felicitus** [FriendsOfSymfony/FOSRestBundle#999]
Hi,

I'm using the FOSRestBundle ExceptionController in my project. Currently, it only returns code and message. Is there any way to configure the ExceptionController so that it returns a backtrace?

Thanks

**Comment by tonivdv** [comment]
Hi @felicitus ,

You want this for debugging purposes?

**Comment by felicitus** [comment]
Yes. When an exception is thrown, I display the backtrace to the user so he can report it to me. My project PartKeepr is usually installed on the user's web server. I'm currently migrating the Project to Symfony2. It would be good to have a configuration option to specify if the backtrace should be returned.

**Comment by tonivdv** [comment]
You can create your custom view. Following page should help you achieve this http://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html

**Comment by felicitus** [comment]
Thanks for pointing that out, I didn't see that. I guess this issue can be closed then.

**Comment by tonivdv** [comment]
Yes you can close it and if you have difficulties again you could reopen it (ps: I don't have to rights to close them :) )

**Comment by felicitus** [comment]
Thank you for your help :+1:
